### ISSUE TITLE
openmm-dev build failure on osx

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1024]
I'm trying to figure out if this build failure is due to my recent installation of `gcc46` on this machine via `macports`:
```
building 'simtk.openmm._openmm' extension
creating build/temp.macosx-10.5-x86_64-2.7
creating build/temp.macosx-10.5-x86_64-2.7/src
creating build/temp.macosx-10.5-x86_64-2.7/src/swig_doxygen
gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch x86_64 -DMAJOR_VERSION=6 -DMINOR_VERSION=3 -I/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/envs/_build/include -I/Users/jenkins-slave/workspace/conda-openmm-dev-osx-2/miniconda/envs/_build/include/python2.7 -c src/swig_doxygen/OpenMMSwig.cxx -o build/temp.macosx-10.5-x86_64-2.7/src/swig_doxygen/OpenMMSwig.o -stdlib=libc++ -mmacosx-version-min=10.7
gcc: error: unrecognized command line option '-stdlib=libc++'
error: command 'gcc' failed with exit status 1
```

**Comment by jchodera** [comment]
Here is the Jenkins build log:
https://jenkins.choderalab.org/job/conda-openmm-dev-osx-2/46/console

**Comment by rmcgibbo** [comment]
have you tried building openmm using macports gcc on mac before? i'd be surprised if it compiled w/o modification to the build scripts.

**Comment by rmcgibbo** [comment]
you can probably fix that with `export CC=clang`, but i'm -1 on macports gcc.

**Comment by swails** [comment]
I'm with @rmcgibbo on this.  The problem here is that Macs give their compilers special flags and some different standard libraries.  For instance, where gcc on Linux platforms need to link to `libstdc++.so`, Apple has decided they're special, and their standard C++ library is just `libc++.so`.

But the MacPorts GCC is as undoctored as possible, which means that it behaves not like the standard Apple compilers that comes with XCode (which supports custom flags and libraries added by Apple), but rather like standard Linux compilers (i.e., those extra flags that Apple added to *its* gcc/clang are not recognized by the MacPorts compilers, and libc++ needs to become libstdc++ once again).

A basic rule of thumb: only use the MacPorts compilers if you need Fortran.  Slightly more in-depth is "if the build works with the XCode compilers, always use that".

What's happening here, I think, is that CMake detects an Apple platform, so it applies some Apple-specific flags (in particular, a directive to make sure that `libc++` is used instead of `libstdc++`).  The "undoctored" MacPorts GCC has no idea what to do with this directive, so it chokes.

Best bet is to deactivate the MacPorts GCC while building the Python extensions (if you use Anaconda this is necessary) and just specify `clang` as the compiler to CMake.

Deactivate as follows:
```
sudo port select gcc none
```

**Comment by jchodera** [comment]
Apologies for not clarifying earlier: I'm certainly not *intending* to compile OpenMM with macports `gcc43`; I just *installed* it on the `osx` build box so I can compile `ambermini`.

I had to `sudo port select gcc gcc43` in order to activate `gfortran` for use in compiling `ambermini`.

The [`openmm-dev` build script](https://github.com/omnia-md/openmm-dev/blob/master/build.sh) explicitly says we should use `clang`:
```
elif [[ "$OSTYPE" == "darwin"* ]]; then
    CMAKE_FLAGS+=" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++"
```
but it looks like this is insufficient to select the compiler used when building the Python wrappers.  I had *thought* that `python setup.py install` would automatically select the appropriate compiler, but it seems to have selected the macports compiler instead.

So, the question is:
* How can we modify the `ambermini` build scripts to correctly use the macports-installed `gfortran` for `gcc43`?
* OR
* How can we modify the `openmm-dev` build script to use the correct system `gcc` in building the Python wrappers?

**Comment by jchodera** [comment]
Also, anything involving `sudo` is probably out since that can't be run from within the build scripts.

**Comment by swails** [comment]
> but it looks like this is insufficient to select the compiler used when building the Python wrappers. I had thought that python setup.py install would automatically select the appropriate compiler, but it seems to have selected the macports compiler instead.

See the discussion in #999 (you need to expand the comments on the outdated diff).  The issue is that `python setup.py`, which uses distutils, automatically uses the same compiler *and* compiler flags that were used to build Python in the first place.  If you use the system Python, then everything goes as expected (i.e., the Mac clang compiler is used to build extensions and everything is fine).

But you're probably using anaconda or miniconda.  Well, Continuum made the rather unfortunate choice to compile using the Mac gcc program (which I think is just a wrapper around clang) to build Python.  Which means that distutils thinks the host compiler is "gcc", not "clang".  So it's picking up the MacPorts gcc.

@rmcgibbo's suggestion should work here -- set the `CC` env variable to `clang`.

**Comment by jchodera** [comment]
> @rmcgibbo's suggestion should work here -- set the CC env variable to clang.

OK, I'll give that a try, though it sounds like it would be safer to leave MacPorts `gcc` deselected and hard-code the paths into the conda build recipe for `ambermini`.  I might try that first, since you already have some hardcoded paths in there.

**Comment by jchodera** [comment]
OK, I think I've got this working.  Thanks!

**Comment by jchodera** [comment]
For reference:
https://github.com/omnia-md/conda-recipes/pull/250
