### ISSUE TITLE
Reformat "landing" page of sphinx docs

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1047]
We might consider reformatting the sphinx docs in such a way that the landing page doesn't hit you with a big block of legal text. It's a little offputting.

(orignally at https://github.com/pandegroup/openmm/issues/992#issuecomment-124269718)

**Comment by peastman** [comment]
The trick will be getting it to be reasonable in both the HTML and PDF versions.  Certain elements in the document get ordered differently in the two cases.  In the PDF you first get the title page, then the table of contents, and then the legalese on its own page.  That's exactly how we want it.  But in the HTML, the legalese gets put right at the top above the table of contents.

**Comment by rmcgibbo** [comment]
Yeah. I agree the content ordering / formatting of the PDF is great.

**Comment by peastman** [comment]
I've been experimenting with this, but haven't found anything that works better.  That text is found in the index.rst file (https://raw.githubusercontent.com/pandegroup/openmm/master/docs-source/usersguide/index.rst), and is placed just above the toctree directive.  In the HTML it ends up above the table of contents (which isn't ideal), and in the PDF it ends up on its own page after the table of contents (which is exactly what we want).

If I move it down to after the toctree directive, then the HTML comes out the way we want: all the legal information is moved to the bottom of the table of contents.  But in the PDF, it gets moved to almost the very end of the document!  It gets appended to the end of the last chapter, just before the bibliography.

**Comment by swails** [comment]
I have an idea how this can be fixed up.  A little hacky, but it should do the job.  I'll try it out and submit a PR if it works.

**Comment by swails** [comment]
OK, I tested this and it "works" in that the legalese is put at the bottom of the HTML TOC page, but it's still put right after the TOC at the beginning of the PDF.

The approach I took was to have conf.py, which gets `exec`ed when Sphinx runs, generate the `index.rst` file in the order that was desired based on the type of document being built.  For HTML docs, it puts the legalese at the bottom of the rst file, but puts it at the top (in the current order we have right now).

So the PDF remains unchanged, but the HTML docs are generated with the legal junk at the bottom of the TOC page, which is basically what we were going after, I think.  It also keeps all of the content in a single place -- `conf.py` (rather than `index.rst`.  It also adds a comment at the top of the generated `index.rst` saying it's autogenerated by `conf.py` and that file should be changed instead if you need to change content.  So while it's a little clunky and potentially confusing at first, it really shouldn't be too bad.

Comments welcome.

**Comment by swails** [comment]
this == #1123 in my previous post -- sorry for the ambiguity.

**Comment by peastman** [comment]
How about this for a simpler approach: just include it twice, before and after the toctree, each one marked off with a ".. only::" directive so it's only included for the appropriate format.  Even better, put the text itself in a macro, then just include that macro twice.

While we're at it, we should also update the copyright date to 2015.

**Comment by swails** [comment]
> How about this for a simpler approach: just include it twice, before and after the toctree, each one marked off with a ".. only::" directive so it's only included for the appropriate format. Even better, put the text itself in a macro, then just include that macro twice.

You obviously know Sphinx better than I do -- I don't know how to do any of that without looking it up, so I'll defer to you.
