### ISSUE TITLE
Extending ffxml to separate charge and Lennard-Jones parameter assignment

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1168]
We have been thinking about ways we can make the `ffxml` format for `simtk.openmm.app.ForceField` a bit friendlier both for users (who often want to "mix and match", such as combining AMBER forcefields with standard or multisite ion parameters) and for tools that need to use small molecules (such as YANK).  

While the `type` and `class` mechansim of the `ffxml` format is very powerful, one of the main sources of complexity right now is the definition of a new atom `type` for each atom appearing in each residue template.  Forcefields like AMBER define a very limited set of atom types (e.g. [`parm96.dat` defines 54 atom types](https://github.com/choderalab/ambermini/blob/master/share/amber/dat/leap/parm/parm96.dat#L2-L55)), and even fewer Lennard-Jones parameters ([`parm96.dat` defines 35 LJ types](https://github.com/choderalab/ambermini/blob/master/share/amber/dat/leap/parm/parm96.dat#L2-L55)).

If we had a mechanism by which the `NonbondedForce` section of the `ffxml` file could also specify a `charge` attribute for each object, and use this to assign charges, the complexity of the resulting `ffxml` files could be considerably simplified, and we could additionally mix-and-match things like the [`gaff.xml`](https://github.com/choderalab/ambermini/blob/master/share/amber/dat/leap/parm/gaff.dat) small molecule forcefield that specifies parameters for small molecules because no name collisions would occur (provided we also permit parameters to be specified in a separate `ffxml` file from residue templates).

This change would allow us to extend the `<Atom>` element tag to permit an additional `charge attribute.  For alanine, for example, this would change from
```XML
  <Residue name="ALA">
   <Atom name="N" type="0"/>
   <Atom name="H" type="1"/>
```
to
```XML
  <Residue name="ALA">
   <Atom name="N" type="0" charge="-0.41570"/>
   <Atom name="H" type="1" charge="0.27190"/>
```
The atom types and classes would be redefined to match the AMBER atom type names and LJ classes, changing from:
```XML
 <AtomTypes>
  <Type name="0" class="N" element="N" mass="14.00672"/>
  <Type name="1" class="H" element="H" mass="1.007947"/>
  <Type name="2" class="CT" element="C" mass="12.01078"/>
  <Type name="3" class="H1" element="H" mass="1.007947"/>
```
to
```XML
 <AtomTypes>
  <Type name="N" class="N" element="N" mass="14.00672"/>
  <Type name="H" class="H" element="H" mass="1.007947"/>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="H1" class="H1" element="H" mass="1.007947"/>
```
The `<NonbondedForce>` section of the `ffxml` would then be simplified by utilizing the smaller number of LJ atom classes, and either omit the charge altogether:
```XML
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom class="N" sigma="0.324999852378" epsilon="0.71128"/>
  <Atom class="H" sigma="0.106907846177" epsilon="0.0656888"/>
  <Atom class="C" sigma="0.339966950842" epsilon="0.4577296"/>
  <Atom class="H1" sigma="0.247135304412" epsilon="0.0656888"/>
```
or specify a keyword that says the charge should be obtained from the `charge` attribute of the `<Atom>` tag:
```XML
<NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom class="N" charge="atom@charge" sigma="0.324999852378" epsilon="0.71128"/>
  <Atom class="H" charge="atom@charge" sigma="0.106907846177" epsilon="0.0656888"/>
  <Atom class="C" charge="atom@charge" sigma="0.339966950842" epsilon="0.4577296"/>
  <Atom class="H1" charge="atom@charge" sigma="0.247135304412" epsilon="0.0656888"/>
```
Other syntax could be used to denote the attribute of interest, such as XPath syntax (is this `Atom/@charge`?) that could let us extend the `<Atom>` tag in the future with additional atom-specific information (such as AMOEBA multipole parameters).

Questions for the implementation:
* Can this simply be a backwards-compatible extension to the `ffxml` format, rather than a new non-backwards-compatible revision?  
* Even if this is not a revision, should we start adding an attribute that specifies the version of the `ffxml` spec we are using, such as
```XML
<ForceField version="1.0">
```
in order to better handle revisions in the future?
* Should we modify `NonbondedGenerator` to handle these extensions, or is this better handled by adding a custom `<Script>` section to the `<NonbondedForce>` sections of the `ffxml` files?  If a `Script`, how would we access the `<Atom>` `charge` attribute?
 * Can we easily change the behavior to allow residue templates to be specified in a different file from the parameters to facilitate mix-and-match use without causing problems?  We would still want an `Exception` to be thrown on atom type or class name collisions.
* Are there other opportunities for generalization we can exploit along the same lines?

**Comment by jchodera** [comment]
(Tagging @rafwiewiora)

**Comment by peastman** [comment]
That would clash pretty badly with some of the basic concepts that ForceField is organized around.  Let me suggest an alternative design that I think would achieve the same goals while being both more general and more consistent with the design of OpenMM.

Here's a typical `<Atom>` tag in the `<NonbondedForce>` section:

```XML
<Atom type="0" charge="-0.4157" sigma="0.324999852378" epsilon="0.71128"/>
```

`type` can be replaced with `class` if you prefer to specify it that way.  But either way, it specifies a set of atoms, and a set of parameters to use for them in the `NonbondedForce`.

Let's change it so the tag can include only a subset of the parameters.  You could then use separate tags for the Coulomb and LJ parameters:

```XML
<Atom type="0" charge="-0.4157"/>
<Atom type="0" sigma="0.324999852378" epsilon="0.71128"/>
```

Of course, those two tags could be in different files.  Either or both of them could be specified by `class` instead of `type`.  So for example you could specify LJ parameters by class in one file, and charges by type in a different file.  But however you did it, you would need to make sure every atom had exactly one value for every parameter.  Otherwise, it would throw an exception.

This could also work for other forces that involve per-particle parameters: `CustomNonbondedForce`, `AmoebaMultipoleForce`, `GBSAOBCForce`, etc.

**Comment by jchodera** [comment]
@peastman: Can you clarify how this would help?  With your proposal, we would be able to split definitions into different files, but would still have to have a unique atom `type` or `class` for every atom of every residue we define.  As a result, it doesn't help us "mix and match" either, since even GB parameters need to have an entry for every atom of every residue we define---we can't simply let these be assigned by atom `class` (AMBER type name) because `charge` is integral to the entries of `GBSAOBCForce` as well.  So I don't quite understand how this proposal would help.

I'm very curious why you think this would clash with the basic principles of `ForceField`.  I don't see it that way at all!  It's a fantastic design, since it compartmentalizes the definition of each `Force` into a separate XML element, which makes it very extensible.

What we are proposing here is simply allowing the `<Atom>` elements to have additional XML node attributes that *will also be available* to the `ForceGenerator` classes in generating the parameters they use.  In this case, it is simply the partial charge, but it could potentially be other properties in the future.  The `ForceGenerator` simply needs a scheme to use both the information in the `<Force>` block, as well as any additional attributes in the `<Atom>` block, to decide what parameters to construct.

The beauty of the approach I propose is that it also solves our GB problem, since the same issue applies to GBSA parameters.  By letting the `<GBSAOBCForce>` section omit the `charge` and letting the [`GBSAOBCGenerator`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1223) use the `charge` attribute of each `<Atom>` to construct the parameters, we can have a single set of GB parameters for each GBSA model, rather than also needing to generate parameters specific for each forcefield residue set as well.

**Comment by jchodera** [comment]
In terms of implementation, we would need to extend [`_TemplateAtomData`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L283-L290) to include a `dict` for additional attributes the user might specify, perhaps `attributes`.

Then, in [`NonbondedGenerator`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1175-L1177), we handle the cases where the `charge`, `sigma`, or `epsilon` is not a number but a string such as `attribute@charge` to extract the `attributename` of `charge`, and instead look up `atom.metadata[attributename]`.

There are some additional changes that would need to be made---everything is assumed to be numbers right now, for example---but I don't think it would be hugely difficult, and it would give us significantly more flexibility, while solving a number of headaches related to small molecules and GBSA parameters.

**Comment by peastman** [comment]
That would also be a way of doing it.  (Allowing arbitrary per-particle parameters in `<Residue>` tags is certainly better than a hardcoded `charge` attribute as you originally suggested.  I always prefer general purpose mechanisms over specialized ones for particular use cases!)  I think the two are roughly equivalent to each other.  What you're proposing is essentially the same as having an atom type for every AMBER-type/charge combination.  That is, instead of

```XML
<Atom name="N" type="N" charge="-0.4157"/>
```

as you suggested, have

```XML
<Atom name="N" type="N -0.4157"/>
```

In the same file, you would also have a `<NonbondedForce>` tag that species

```XML
<Atom type="N -0.4157" charge="-0.4157"/>
```

Your approach would be a bit more concise, since it wouldn't require that additional `<NonbondedForce>` tag.  As for which is more powerful, I'm not certain.  I'm pretty certain that anything you can do with your approach, you can also do with my approach.  But is there anything you can do with my approach but not yours?  I'm not certain about that.

**Comment by jchodera** [comment]
I think I'm still missing how your proposal would allow for true "mix and match" of the sort we need.

Suppose we want to specify OBC GB parameters based on AMBER atom types so that, in addition to including a file that defines, say, amber96 residue templates, we can also include a ffxml file that specifies a small molecule (without GB parameters).  In my proposal, both the residue template file and the small molecule file contain `<Atom>` tags with associated charges in the residue template definitions.

In your proposal, we would need to additionally define new atom types like `"N -0.4157"` in the `<AtomTypes>` block
```XML
<AtomTypes>
    <Type name="N -0.4157" class="N" element="N" mass="14.00672"/>
```
 *and* add an element to the `<NonbondedForce>` block:
```XML
<Atom type="N -0.4157" charge="-0.4157"/>
```
We would be *required* to define the atom types used by the residues in the residue xml file and the small molecule in the small molecule XML file, but we would also need to define the `<NonbondedForce>` terms and `<GBSAOBCForce>` terms in both files.  I don't think that helps us at all---at least not in the way I was hoping to simplify things.

Should I take a stab at coding up my approach?  Or are you wedded to making the changes yourself here?

**Comment by Lnaden** [comment]
As I understand the argument, and what I would also like to see, is to reduce the amount of required entries in `<AtomTypes>` and subsequent `<NonbondedForce>` entries, while still maintaining full charge assignment flexibility in the `<Residue>` tags. 

Would it be possible to extend the `<Residue>` tag to overwrite the charge in the `<NonbondedForce>` tags, essentially treating the `<NonbondedForce>` as a default value? In practice, it would look something like

```xml
<ForceField>
 <AtomTypes>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="HT" class="HT" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.13"/>
    <Atom name="HT1" type="HT"/>
   </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom type="CT" charge="0" sigma="0.3399" epsilon="0.3598"/>
  <Atom type="HT" charge="0.13" sigma="0.1069" epsilon="0.0657"/>
 </NonbondedForce>
</ForceField>
```
For this, the CT atom name has the default charge of 0, but the assignment in the `<Residue>` overwrites the default value for this specific CT1 atom on this residue with "-0.13". Meanwhile, the HT atom has default charge of "0.13" and the residue reads the default value for the given atom type since no specific charge was assigned with HT1. This would reduce the number of atom types needed, while still preserving backwards compatibility and, and not requiring any fundamental changes to the `<NonbondedForce>` tag processing.

I don't know how feasible this approach is without knowing how the tags are processed, but how viable would this approach be?

**Comment by jchodera** [comment]
@Lnaden: My proposal is very similar, since we would allow force terms like `<NonbondedForce>` to access arbitrary `<Atom>` attributes based on keywords used instead of specifying a charge:
```XML
<ForceField>
 <AtomTypes>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="HT" class="HT" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.1325"/>
    <Atom name="HT1" type="HT" charge=+0.1305/>
   </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom class="CT" charge="@charge" sigma="0.3399" epsilon="0.3598"/>
  <Atom class="HT" charge="@charge" sigma="0.1069" epsilon="0.0657"/>
 </NonbondedForce>
</ForceField>
```
The proposals are a bit different: Your proposal would allow only some residue template `<Atom>` definitions to override the default charges, though the attribute name would have to be the same as the force parameter name, which could lead to unintended collisions; my proposal would allow arbitrary attributes to be used, where collisions could be avoided if needed.  I'm not sure the difference is very major.

**Comment by peastman** [comment]
> but we would also need to define the <NonbondedForce> terms and <GBSAOBCForce> terms in both files.

You would only need to define charges (along with corresponding atom types) in those files.  The other parameters (sigma, epsilon, radius, etc.) would be specified by class, so they would only appear once (in the generic force field definition).

But I do agree that your design would be more concise and generally more convenient to work with.  So let's investigate that a bit further.  Here are some questions.

- Should you be able to specify a parameter both in the residue template and again in a force definition, as @Lnaden suggests, and have the latter override the former?

Unless there's a good reason to allow it, I'm inclined to say no.  That's the sort of feature that makes it very easy for people to make mistakes.  You edit the charge in one place, not realizing it's having no effect because it's overridden someplace else.

To be clear, I'm fine with letting some atom types be specified one way and others the other way.  But for any given atom, each parameter should be specified exactly once.  If the same parameter for the same atom was specified in two different places, there's a good chance it indicates a mistake by the user.

- Should you have to explicitly specify what parameters you're using, or should it just match them by name automatically?  I'm thinking of something like

```XML
<UseTemplateParameter name="charge" localName="charge"/>
```

inside the `<NonbondedForce>` tag.  The advantage would be that the name wouldn't have to be the same.  For example, `<AmoebaMultipoleForce>` specifies the charge with an attribute called `c0`, whereas `<AmoebaGeneralizedKirkwoodForce>` specifies it with an attribute called `charge`.  This might be an unnecessary complication, though, and we should just fix `<AmoebaMultipoleForce>` to accept `charge` as well.

**Comment by rafwiewiora** [comment]
@jchodera: Just to check I'm following here, I'm getting a bit confused about the type/class distinction. In your proposal, class specifies LJ parameters and type will here further specify bonding parameters, is this right? I.e. `<HarmonicBondForce>`, `<HarmonicAngleForce>` and `<PeriodicTorsionForce>`, which are currently specified by classes, in your proposal would be specified using types? Am I getting this right? 

Why specify element and mass in Types, while those are the same within a Class? Shouldn't you replace `<AtomTypes>` with `<AtomClasses>`? What I'm wondering is: the differences between Types only become clear when you specify the bonding parameters for them - why do you need to also list them at the beginning of the file? Is this some kind of a 'Type-initialization'? A mechanism to protect from errors - you have to list the Types you'll be using before you use them to make sure you don't miss anything?

**Comment by peastman** [comment]
In OpenMM, an atom type is a "thing".  It has properties, like an element and a mass.  An atom class is not a "thing".  It's just a label you can use as a shortcut to refer to multiple atom types at once.

**Comment by jchodera** [comment]
@rafwiewiora: In the new scheme, I was conceiving of translating the AMBER atom types to the OpenMM atom types directly, and using OpenMM atom classes (which are just shortcuts) to refer to the Lennard-Jones atom types, where some AMBER atom types all map to the same Lennard-Jones atom class.   For AMBER `parm96`, for example, there are 54 atom types and 34 atom classes for Lennard-Jones.

**Comment by jchodera** [comment]
@peastman: It sounds like we are debating between two main approaches.

**Proposal 1: Allow some `<*Force>` entries to access atom attributes in their own attributes.**
Continuing with our artificial example, this would be:
```XML
<ForceField>
 <AtomTypes>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="HT" class="HT" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.1325"/>
    <Atom name="HT1" type="HT" charge=+0.1305/>
   </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom class="CT" charge="@charge" sigma="0.3399" epsilon="0.3598"/>
  <Atom class="HT" charge="@charge" sigma="0.1069" epsilon="0.0657"/>
 </NonbondedForce>
</ForceField>
```
where the defining characteristic is that each attribute used in `<Atom>` elements of `<NonbondedForce>` or similar forces could refer to attributes of the corresponding `<Residue>` template `<Atom>` elements.  We could even make this more general by permitting algebraic formulas that could be evaluated with `eval`, like
```XML
  <Atom class="CT" charge="@charge * @shielding" sigma="0.3399" epsilon="0.3598"/>
```
though this may be of limited additional utility.

This does have the drawback of permitting some entries to use `<Atom>` attributes and using others to use hardcoded charges, but this may not be as much of a drawback as expected, since users will generally not be producing their own `ffxml` files.

**Proposal 2: Allow some `<*Force>` entries to separately define which attributes will be pulled from `<Atom>` attributes.**
@peastman suggests using a `<UseParameterTemplate>` element, such as
```XML
<ForceField>
 <AtomTypes>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="HT" class="HT" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.1325"/>
    <Atom name="HT1" type="HT" charge=+0.1305/>
   </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <UseParameterTemplate name="charge" localName="charge"/>
  <Atom class="CT" sigma="0.3399" epsilon="0.3598"/>
  <Atom class="HT" sigma="0.1069" epsilon="0.0657"/>
 </NonbondedForce>
</ForceField>
```
This does reduce a lot of repetition, which I like, but I'd love to find a more obvious syntax for this. Perhaps
```XML
  <UseAtomAttributes parameter="charge" attribute="charge"/>
```
Also, I wonder if this would be harder to universally implement than option 1, but it may be of little practical difference.

**Comment by jchodera** [comment]
Other minor extensions I would love to make:

**Specify residue template bonds using atom names.**  This should be a no-brainer.  Instead of
```XML
<ForceField>
 <AtomTypes>
  <Type name="tip3p-O" class="OW" element="O" mass="15.99943"/>
  <Type name="tip3p-H" class="HW" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
  <Residue name="HOH">
   <Atom name="O" type="tip3p-O"/>
   <Atom name="H1" type="tip3p-H"/>
   <Atom name="H2" type="tip3p-H"/>
   <Bond from="0" to="1"/>
   <Bond from="0" to="2"/>
  </Residue>
 </Residues>
 <HarmonicBondForce>
  <Bond class1="OW" class2="HW" length="0.09572" k="462750.4"/>
 </HarmonicBondForce>
 <HarmonicAngleForce>
  <Angle class1="HW" class2="OW" class3="HW" angle="1.82421813418" k="836.8"/>
 </HarmonicAngleForce>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom type="tip3p-O" charge="-0.834" sigma="0.31507524065751241" epsilon="0.635968"/>
  <Atom type="tip3p-H" charge="0.417" sigma="1" epsilon="0"/>
 </NonbondedForce>
</ForceField>
```
I should be able to write
```XML
<ForceField>
 <AtomTypes>
  <Type name="tip3p-O" class="OW" element="O" mass="15.99943"/>
  <Type name="tip3p-H" class="HW" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
  <Residue name="HOH">
   <Atom name="O" type="tip3p-O"/>
   <Atom name="H1" type="tip3p-H"/>
   <Atom name="H2" type="tip3p-H"/>
   <Bond from="O" to="H1"/>
   <Bond from="O" to="H2"/>
  </Residue>
 </Residues>
 <HarmonicBondForce>
  <Bond class1="OW" class2="HW" length="0.09572" k="462750.4"/>
 </HarmonicBondForce>
 <HarmonicAngleForce>
  <Angle class1="HW" class2="OW" class3="HW" angle="1.82421813418" k="836.8"/>
 </HarmonicAngleForce>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <Atom type="tip3p-O" charge="-0.834" sigma="0.31507524065751241" epsilon="0.635968"/>
  <Atom type="tip3p-H" charge="0.417" sigma="1" epsilon="0"/>
 </NonbondedForce>
</ForceField>
```

**Comment by kyleabeauchamp** [comment]
+1 on name-based residue template bonds.  IMHO it adds a huge amount readability to the FF files.

**Comment by jchodera** [comment]
> +1 on name-based residue template bonds. IMHO it adds a huge amount readability to the FF files.
> 
Any other extensions we can make that would add readability or convenience at this point?

We will need to extend the Residue format to include titratable sites, but that will be discussed separately.

**Comment by peastman** [comment]
I was actually thinking of your other suggestion:

```XML
<Atom class="CT" sigma="0.3399" epsilon="0.3598"/>
```

You would simply omit `charge`, and instead it would use the attribute with the same name from the residue template.  The @ syntax is less concise and more complex.  And while the idea of being able to put mathematical expressions in attributes is interesting, I can't think of any use cases where it would be useful enough to justify the very significant complexity it would add.

> Specify residue template bonds using atom names.

Yes, I've regretted for years that I didn't originally make it work that way.  The only question is how to maintain backward compatibility, since it would need to figure out which method you were using.  This would only be an issue if someone used numbers as their atom names, but I can't rule out the possibility that someone may have done that.

**Comment by jchodera** [comment]
> You would simply omit charge, and instead it would use the attribute with the same name from the residue template.

So you favor "Proposal 2" above, where we also add the element
```XML
 <UseAtomAttributes parameter="charge" attribute="charge"/>
```
since the attribute name may differ from the parameter name.

Does this sound reasonable to everyone?  I'm OK with it.

> Specify residue template bonds using atom names.

We can just use different attributes:
```XML
   <Bond fromName="O" toName="H1"/>
   <Bond fromName="O" toName="H2"/>
```

**Comment by jchodera** [comment]
> Specify residue template bonds using atom names.

Alternatively, we can use an attribute to specify what convention is being used:
```XML
   <Bond attribute="name" from="O" to="H1"/>
   <Bond attribute="name" from="O" to="H2"/>
```

**Comment by peastman** [comment]
> So you favor "Proposal 2" above, where we also add the element

Whether we should also add that element is an open question.  It's one of the things I asked about.

**Comment by jchodera** [comment]
I believe Proposal 2 would *necessitate* adding something that allows us to translate between parameter names and attribute names, for exactly the reason you described.

**Comment by peastman** [comment]
No, it could simply require the names to be the same.  As I discussed.

**Comment by jchodera** [comment]
> No, it could simply require the names to be the same. As I discussed.

You suggested fixing an unrelated API issue as a possible workaround:
>  For example, <AmoebaMultipoleForce> specifies the charge with an attribute called c0, whereas <AmoebaGeneralizedKirkwoodForce> specifies it with an attribute called charge. This might be an unnecessary complication, though, and we should just fix <AmoebaMultipoleForce> to accept charge as well.

While I am fully supportive of fixing the `AmoebaMultipoleForce` API, I think that the ease with which other `Force`s may have parameters named differently really necessitates we have some way of specifying the translation between `<Atom>` attributes and parameters.

One could also argue that requiring an explicit element like
```XML
 <UseAtomAttributes parameter="charge" attribute="charge"/>
```
when we want to use `<Atom>` attributes reduces the potential for the `ffxml` to have subtle unexpected behavior where these attributes are silently grabbed.

You could also think about later having a more complex extension where other parameters are more complex combinations of `<Atom>` or `<Bond>` attributes.

**Comment by peastman** [comment]
> You suggested fixing an unrelated API issue as a possible workaround:

Well, I mentioned it because it was the only case I could think of where this would be an issue!

Generally speaking, if you're creating a force field, you can name attributes on the residue templates however you want.  In particular, could can chose them to match the attribute on the force.  Of course, if the force happens to be a custom force, the attribute name is simply the same as the per-particle parameter name, which you can choose however you want.  So the only situation where this would be a problem is if you want to use the value for two different forces, *and* neither of those is a custom force.

By the way, you seem to be using the word "attribute" to mean something different than I am, which I think may be leading to some confusion.\.  In an XML file, an "attribute" is a name/value pair placed between the `<` and `>` characters of a tag.  When I speak of an "attribute", I mean a feature of an XML file.  When I speak of a "parameter", I mean a feature of a Force object.  A force field definition uses attributes to specify values of parameters.

**Comment by jchodera** [comment]
> By the way, you seem to be using the word "attribute" to mean something different than I am, which I think may be leading to some confusion.. In an XML file, an "attribute" is a name/value pair placed between the < and > characters of a tag. When I speak of an "attribute", I mean a feature of an XML file. When I speak of a "parameter", I mean a feature of a Force object. A force field definition uses attributes to specify values of parameters.

I think we are using them the same way.  In the `ffxml` file, we have a residue template with `<Atom>` elements:
```XML
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.1325"/>
```
Here, `charge` is an attribute of the `<Atom>` element.

On the other hand, `charge` is also a parameter for the `NonbondedForce`.  But they could be named differently, as you point out, for `AmoebaMultipoleForce` where the corresponding parameter is called `c0`.  Having an element that specifies how `<Atom>` attributes are translated into `Force` parameters is useful if we want to allow flexibility in how `Force` objects specify parameters without requiring `<Atom>` attributes duplicate information unnecessarily.

> So the only situation where this would be a problem is if you want to use the value for two different forces, and neither of those is a custom force.

I could certainly see wanting to mix `AmoebaMultipoleForce` and `NonbondedForce` at some point.

Are we all decided, then?   On a scheme like
```XML
<ForceField>
 <AtomTypes>
  <Type name="CT" class="C" element="C" mass="12.01078"/>
  <Type name="HT" class="HT" element="H" mass="1.007947"/>
 </AtomTypes>
 <Residues>
   <Residue name="EXP">
    <Atom name="CT1" type="CT" charge="-0.1325"/>
    <Atom name="HT1" type="HT" charge=+0.1305/>
   <Bond fromName="CT" toName="HT">
   </Residue>
 </Residues>
 <NonbondedForce coulomb14scale="0.833333" lj14scale="0.5">
  <UseAtomAttributes parameter="charge" attribute="charge"/>
  <Atom class="CT" sigma="0.3399" epsilon="0.3598"/>
  <Atom class="HT" sigma="0.1069" epsilon="0.0657"/>
 </NonbondedForce>
</ForceField>
```
where the `attribute` of `<UseAtomAttributes>` refers to the attribute of the `<Atom>` element in `<Residue>` and `parameter` refers to the `NonbondedForce` parameter for the particle.

If so, it would be great to move ahead with an implementation.

**Comment by peastman** [comment]
> I could certainly see wanting to mix AmoebaMultipoleForce and NonbondedForce at some point.

That would be a rather strange thing to do!  But in any case, I already suggested changing the XML format for AmoebaMultipoleForce to use the attribute `charge`, because that's what it should really have been called all along.  So that still isn't a meaningful counterexample.

I also raised questions about values overriding each other, which no one has responded to yet.  And along the same lines, should you be able to specify some atoms one way and others a different way?  Or should everything be done the same way?

**Comment by jchodera** [comment]
> That would be a rather strange thing to do! 

I could envision a forcefield that uses Lennard-Jones terms along with some point multipoles, but it may be fine to instead use `CustomNonbondedForce` to implement the Lennard-Jones term.

> But in any case, I already suggested changing the XML format for AmoebaMultipoleForce to use the attribute charge, because that's what it should really have been called all along. So that still isn't a meaningful counterexample.

Just to think through this: Suppose we fix the `AmoebaMultipoleForce` API to accept both `charge` and `c0`.  What happens if we want to use the `c0` attribute for something else in the future, like a Fourier expansion force?  Or if both `c0` and `charge` attributes are specified?  Which one would have precedence?  Or would this be disallowed?

I think it's less ambiguous to *require* `<UseAtomAttributes>` to specify when we are using atom attributes instead of specifying them.  This makes it much less ambiguous where they are coming from. 

> I also raised questions about values overriding each other, which no one has responded to yet. 

I should have been more explicit in my support of your stance on this.  I think we want it to be very obvious when `<Atom>` attributes will be selected for `Force` parameters, so I like your `<UseAtomAttributes>` proposal, rather than allowing the more flexible case where they are only overridden if parameters are omitted, which would allow.  But that may be only because I can't think of a case where allowing more flexibility isn't important.

> And along the same lines, should you be able to specify some atoms one way and others a different way? Or should everything be done the same way?

We do have to be a bit careful about one specific case: Mixing and matching different files.  If we want to be broad in our support of allowing the user to mix-and-match mutliple files, we may want to allow current-style `tip3p.xml` (where all charges are specified in the `<NonbondedForce>` entries) and new-style AMBER forcefields (where charges will be specified in the `<Atom>` `charge` attributes).  I don't know enough about how `ffxml` file lists are processed now to know if these are processed a file at a time, where we can enforce that everything in one `ffxml` file must be processed the same way, or if we process everything at once after merging it?

Also, implementation complexity should also be considered.  If it would be significantly simpler to implement the more flexible approach, maybe that is best; alternatively, if the more rigid approach is simpler, maybe that is best.

We may also want to think ahead to how we envision users to extend `ForceField` with their own `ForceGenerator` handlers that go along with `Custom*Force` terms. I could envision people wanting to provide these together at some point in the future.

**Comment by peastman** [comment]
> What happens if we want to use the c0 attribute for something else in the future, like a Fourier expansion force?

We wouldn't do that, because it's already used for something else.  You might as well ask, "What happens if we want to add a new attribute called 'd1', even though we're already using that attribute for the first dipole component?"  We simply wouldn't do that.  When defining new attributes, we can call them whatever we want.

**Comment by jchodera** [comment]
Fair enough, but what about the rest of the comment?  Addressing that singular question doesn't get is much closer to an actually decision or implantation here, and it would be great to be able to move forward.

**Comment by peastman** [comment]
My thought is that `<UseTemplateParameter>` adds a small amount of complexity both for the implementation and for the user.  I don't object to that if there's a good reason, but I've yet to see a single case where there's actually a meaningful benefit from it.  (By the way, I don't like the name `UseAtomAttributes` because it's ambiguous and confusing.  The residue templates contain tags called `<Atom>`, and the force also contains tags called `<Atom>`, and they all have attributes.  It isn't obvious what the name refers to.)

I agree with you about the importance of mixing files, which argues against requiring everything to work the same way.  tip3p.xml defines its own atom types, along with NonbondedForce parameters for them, and we shouldn't require they be defined in exactly the same way as whatever force field you're combining it with.  But it should still require that for *each atom*, it only be defined in one way.  If the residue template has a `charge` attribute and then the NonbondedForce also has a `charge` attribute for the same atom type, it should throw an exception.

> We may also want to think ahead to how we envision users to extend ForceField with their own ForceGenerator handlers that go along with Custom*Force terms.

I'm not sure what you mean by that?  We already allow users to add ForceGenerators.  We also already have generators for all the Custom\*Force classes that can be implemented in a generic way.

**Comment by jchodera** [comment]
> My thought is that `<UseTemplateParameter>` adds a small amount of complexity both for the implementation and for the user. I don't object to that if there's a good reason, but I've yet to see a single case where there's actually a meaningful benefit from it.

What if we punt on its implementation until it is clear that we need it?

> By the way, I don't like the name UseAtomAttributes because it's ambiguous and confusing. 

Fair enough, but `UseTemplateParameter` was no less ambiguous or confusing to me.

>  If the residue template has a charge attribute and then the NonbondedForce also has a charge attribute for the same atom type, it should throw an exception.

This sounds reasonable to me.

> We already allow users to add ForceGenerators. We also already have generators for all the Custom*Force classes that can be implemented in a generic way.

I had totally forgotten that you already have readers for `Custom*Force` classes!

**Comment by peastman** [comment]
As a compromise, what if we say the names have to match, but still require you to include the tag

```XML
<UseTemplateParameter name="charge"/>
```

That avoids the complexity and confusion of doing name translation, but also eliminates the possibility of it automatically picking up an attribute you didn't want it to, just because they have the same name.  And if some day we find a use case for which name translation is important, would could always add an optional `localName` attribute then.

> Fair enough, but UseTemplateParameter was no less ambiguous or confusing to me.

Feel free to suggest other names.  `<UseResidueParameter>`?  `<UseAttributeFromResidue>`?  Something else?

**Comment by jchodera** [comment]
That sounds like a great proposal.

I really like `<UseAttributeFromResidue>`, since I think this is easiest to comprehend.

**Comment by peastman** [comment]
So it shall be then!  I'll get started on it.

**Comment by jchodera** [comment]
One other thing that bears on this: We want to relax the constraint that the atom types have to be specified in the same file as they are used, so that we can have one file define types but another file add more residues that use the same types.  This is important for allowing us to combine a `gaff.xml` that specifies atom types with a `obc-gbsa.xml` that specifies GBSA parameters with a `molecules.xml` that specifies new molecules, for example.

This also opens the question of how and whether we want to partition files for our AMBER conversion (#1054 and #1134).  We may want to keep the old files for backwards-compatibility, for example, but include a new set of files that better partition parameters and residues to be more flexible in "mix and match" support.

**Comment by jchodera** [comment]
Also, are we in agreement to also allow bonds between atom names while maintaining backwards-compatibility?  My suggestion was to add `fromName` and `toName` attributes:
```XML
   <Bond fromName="O" toName="H1"/>
   <Bond fromName="O" toName="H2"/>
```
An exception could be thrown if both `fromName` and `from` are specified, or both `toName` and `to`.

**Comment by jchodera** [comment]
Closing this to create issues for the other extension to `Bond` and `ExternalBond`.
