### ISSUE TITLE
Which residues should be specified in residues.xml?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1169]
@rafwiewiora is working on adding negatively charged versions of cysteine and histidine required for the multisite ion parameters (#1032).  Since these new residue definitions do not appear in [`residues.xml`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/data/residues.xml), bonds are not automatically perceived for these residues.  He can add these residue definitions to `residues.xml`, but this brings up a larger question:

**Which residues should appear in `residues.xml`?**
* Is there a PDB official spec as to which residues can omit their `CONECT entries?
* Only the 20 natural amino acids?
* Common residues for which forcefields often provide residue definitions?
* Everything in [`components.cif`](http://deposit.pdb.org/cc_dict_tut.html), which has everything that appears in the PDB?

**Comment by peastman** [comment]
Here's what it says at http://www.wwpdb.org/documentation/file-format-content/format33/sect10.html#CONECT:

> CONECT records are present for:
>
> - Intra-residue connectivity within  non-standard (HET) residues (excluding water).
> - Inter-residue connectivity of HET  groups to standard groups (including water) or to other HET groups. 
> - Disulfide bridges specified in the  SSBOND records have corresponding records.

HET groups are defined at http://www.wwpdb.org/documentation/file-format-content/format33/sect4.html#HET:

> HET records are used to describe non-standard residues, such as prosthetic groups, inhibitors, solvent molecules, and ions for which coordinates are supplied. Groups are considered HET if they are not part of a biological polymer described in SEQRES and considered to be a molecule bound to the polymer, or they are a chemical species that constitute part of a biological polymer and is not one of the following:
>
> - standard amino acids, or
> - standard nucleic acids (C, G, A, U, I, DC, DG, DA, DU, DT and DI), or
> - unknown amino acid (UNK) or nucleic acid (N) where UNK and N are used to indicate the unknown residue name.

**Comment by jchodera** [comment]
Thanks for locating this!

Do alternative protonation states of standard amino acids count as "standard" or nonstandard?  

My understanding from @rafwiewiora is that, in the RCSB, these CYS and HIS residues that have `CONECT` records to `Zn` only have `CONECT records for the bonds to zinc, and are not considered nonstandard amino acids.  That suggests that we too should consider them as standard amino acids and supply definitions in `residues.xml` for these alternative protonation states.

The complication is that we need to detect when they are different from the default protonation state.  We already have code in `Modeller` to determine whether [`CYS` residues should be `CYX`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L673-L678) or [`HIS` residues should be `HIP`, `HID`, or `HIE`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L679-L695); we should presumably add similar logic to select whether standard amino acid residues are bonded to metal ions, either by explicit `CONECT` residues or via distances (since some PDB files omit the `CONECT` distances).  In those cases, the residue variant reflecting `CYX` or `HIN` should be selected as well.

**Comment by peastman** [comment]
The PDB defines exactly what atoms and bonds are expected in each residue.  For example, here's the definition of HIS:

ftp://ftp.wwpdb.org/pub/pdb/data/monomers/HIS

If you have any atoms that aren't included there, then you need to mark it as a heterogen and include CONECT records.

residues.xml was generated from those files, so it already includes everything that's considered a standard bond.  It tolerates missing atoms, so that allows it to handle alternate protonation states.  If a hydrogen is present, it will add a bond to it.  But if it isn't present, that's OK.

When you have a Zn, that's generally treated as a separate residue, and in fact is generally part of a separate chain.

**Comment by rafwiewiora** [comment]
Ok, so let me explain a bit more about what I'm doing now - this is the last step I'm trying to clear up now and will be putting up a PR with mods to Modeller for the dummy atoms zinc approach - see #1032. 

You get a PDB off the database and according to the rules that @peastman mentioned if there's an ion coordination, you must have CONECT records between an atom on a standard residue and the ion (for example the S on CYS and Zn) - the fact that a residue ligates an ion doesn't make it a non-standard residue. so that's right - you only need to CONECT the one bond. Compliance in the whole database with this (for zinc-containing structures, check whether for each zinc there is at least one CONECT record) is about 96%. I think with such high compliance, we can for now decide to use the CONECT records for everything, with warnings to the user if the records are not complete.

For the methyltransferase simulations we're doing, we only care about cysteine-Zn and histidine-Zn bonding for now. In the dummy atom approach, we must have the amino acids negatively charged. CYM (-ve cysteine) is already specified in the forcefields, however a negatively charged HIS (which we'll call HIN) is not - this needs a separate .xml, which I have made from the Amber one. 

**The big question** is how do we specify which of the CYS and HIS residues should become CYM and HIN? My first approach was to do this manually, by modifying the pdb file. But this is what has led to @jchodera opening this issue - if you want to have CYM and HIN in your pdb, you need to add these residues to residues.xml (and also to hydrogens.xml for `Modeller.addHydrogens`) - you could also generate a CONECT record for those residues, but I'm gonna assume that's too much manual work. We could require the user to specify extra bond definitions for CYM and HIN via `Topology.loadBondDefinitions` and extra hydrogen data via `Modeller.loadHydrogenDefinitions` if you don't want to have to add these residues to residues.xml and hydrogens.xml ? 

Alternatively this CYM and HIM specification would be done at `Modeller.addHydrogens` level / some other Modeller level. CYS/CYX already does a good job with this, as it uses the bonding information - if you run `modeller.addHydrogens()` on zinc-cysteine bonding-containing structures, it classifies those CYS's as CYX. Similarly this can be done for HIS-Zn coordination. This just needs adding CYM and HIN as new variants. Those would be determined either by checking for bonding to metals or manually by passing those in `variants` to `modeller.addHydrogens(variants = variants)` - I would be more comfortable with having the user specifically ask for these via the `variants` - an automatic recognition might be next step, when this ion modeling is more general. 

Please check my understanding here: As I see it, the residues in a topology always keep the names they came with from the original PDB, and if you write a PDB out they are returned with those names. (i.e. the standard amino acid names as in residues.xml). `addHydrogens` only adds hydrogens according to the right variant, but does not pass any information further about what the variant choice was. 'forcefield.createSystem' then uses positions and bonding of hydrogens while comparing every residue to forcefield templates and effectively determines at this step what variant to use in the System - is this right? 

If so, how will the difference between CYX and CYM be told ? If charges are not taken into account in residue - template comparison then they are the same. No problem for HIN with that of course, because you remove a proton. Should I introduce a way for the 'CYM-information' to be encoded in the topology in a different way - say via changing `residue.name` to CYM? How would then the ForceField deal with this? Should this CYS to CYM transformation be done by `addHydrogens` really or be part of `addExtraParticles`?

Also, should `PDBFile.writeFile` discard the information that we had CYM or HIN and write them as CYS and HIS, or should they be written out as CYM and HIN? Obviously this is only a protonation state difference, but if my dummy atoms on the zinc get written to the PDF, shouldn't I also have information there that for that model to work those particular residues must be negatively charged. A treatment of those amino acids as 'non-standard' and having a CONECT record for them does not convey that information.

**Comment by peastman** [comment]
First, we need to be very careful about names.  The PDB standardizes what different residue names correspond to.  In the "not so good" old days, people tended to just make up new residue names, which led to a lot of grief.  (AMBER is especially notorious about this!)  But there's been a steady movement away from this toward using standard names.

I bring this up because, according to the PDB, HIN is N-ACETYL-L-ALANYL-ALPHAL-PHENYLALANYL-CHLOROETHYLKETONE (ftp://ftp.wwpdb.org/pub/pdb/data/monomers/HIN), and CYM is S-METHYLCYSTEINE (ftp://ftp.wwpdb.org/pub/pdb/data/monomers/CYM).  So we shouldn't use those names to refer to anything other than those molecules.

You said that `addHydrogens()` doesn't pass along any information about what variant was used for each residue.  But of course, it does pass that along in the form of what hydrogens it added.  That's the whole point after all.  And that's exactly the format you want it to be in to communicate the information to a ForceField.  The two different protonation states differ both in the atoms and the bonds that are present, and that's what the ForceField uses to select a template.

**Comment by rafwiewiora** [comment]
> You said that addHydrogens() doesn't pass along any information about what variant was used for each residue. But of course, it does pass that along in the form of what hydrogens it added. That's the whole point after all. And that's exactly the format you want it to be in to communicate the information to a ForceField. The two different protonation states differ both in the atoms and the bonds that are present, and that's what the ForceField uses to select a template.

OK, I wasn't realizing there is a difference between cysteine bonded to something and cysteine negatively charged, in that there won't be that external bond in the negatively charged one. That's sorted then! I will add negative-cysteine and negative-histidine as variants then and put up the PR later tonight.

**Comment by peastman** [comment]
Before you get too far into implementing this, I want to make sure the approach will really work the way you want it to.  In particular, do you *really* want a bond between the residue and the Zn?

That has several consequences.  First, it means that ForceField will try to add bonded energy terms between them (bonds, angles, torsions).  Presumably there won't be any parameter definitions involving Zn, so they won't actually get added.  More important, that bond will be taken into account when calculating nonbonded exceptions (1-2, 1-3, and 1-4 bonded pairs).  So there won't be a nonbonded interaction between the Zn and a few of the atoms in the side chain.  Is that really what you want?

This all relates to one of the irritating things about PDB: it uses CONECT records for lots of different things.  Not just covalent bonds, but also sometimes (but not reliably!) for ionic bonds, hydrogen bonds, etc.  And there's no way to tell what a given record corresponds to.  At least not without doing a lot of analysis and applying chemical knowledge to try to figure it out.

PDBx improves this a lot.  It has a whole ontology of different types of connections (http://mmcif.wwpdb.org/dictionaries/mmcif_mdb.dic/Items/_struct_conn_type.id.html).  So when OpenMM loads a PDBx file, it only adds bonds to the topology for actual covalent bonds.  But when it loads an old style PDB file, it adds a bond for every CONECT record, which isn't always what you really want.

**Comment by jchodera** [comment]
@rafwiewiora: We should definitely take a look at what PDBx files do with bonds to Zn.

@peastman: I think @rafwiewiora wants to *remove* the bonds to Zn as he processes them, replacing the CYS or HIS residues with negatively charged versions, allowing him to use his multisite ion model (which uses electrostatic interactions in place of bonds).  It is just typical of PDB files to use `CONECT` entries to represent bonds to Zn.

We should take care to think of how this method can be generalized to all multisite ion models (e.g. Ca2+, Mg2+, etc.)

**Comment by rafwiewiora** [comment]
@peastman: As @jchodera said and as explained in #1176 - I am removing those bonds and only using that info to calculate the positions for dummy atoms. 

I will soon do similar analyses for other ions of the PDB database and see how this is done for them. 

I think this is good to to close, I ended up not needing any mods to residues.xml in #1176. Should I close?

**Comment by peastman** [comment]
If you're satisfied with the state of this, then go ahead and close it.
