### ISSUE TITLE
processAmberForceField.py does not add loop closing bonds

### ISSUE THREAD

**Issue by juliebehr** [pandegroup/openmm#1181]
Using these input files:
[ADP.prep] (http://personalpages.manchester.ac.uk/staff/Richard.Bryce/amber/cof/ADP.prep) -- renamed ADP.in
[frcmod.phos] (http://personalpages.manchester.ac.uk/staff/Richard.Bryce/amber/cof/frcmod.phos)
parm94.dat

    python processAmberForceField.py ADP.in frcmod.phos parm94.dat

the resulting ffxml is missing the three bonds defined in "LOOP CLOSING EXPLICIT" in ADP.in

Also, because the atom type names are just an enumerated index (it would be preferable to have some prefix), loading with amber99sbildn.xml into a ForceField object leads to:

    ValueError: Found multiple definitions for atom type: 0

**Comment by jchodera** [comment]
Any chance you can post or link the resulting `ffxml` file? (Maybe as a [gist](https://gist.github.com/) if it's not online somewhere?)

**Comment by juliebehr** [comment]
output ffxml file here : [ADP-not-fixed.xml] (https://github.com/juliebehr/AURKA_UMN/blob/master/simple/ADP/ADP-not-fixed.xml)

**Comment by jchodera** [comment]
Thanks!

@peastman: We didn't want to attempt a fix directly since you're working on this code now, but we could take a stab at it when you are done.  There are a few main problems:
* The `LOOP` section of [ADP.prep](http://personalpages.manchester.ac.uk/staff/Richard.Bryce/amber/cof/ADP.prep) is incorrectly parse.
```
LOOP CLOSING EXPLICIT
 C1*  C2*
 C4   C5
 C4   N9
```
* The resulting `ffxml` file contains two `ExternalBond` entries that shouldn't be there.
```
   <ExternalBond from="0"/>
   <ExternalBond from="35"/>
```
I'm not sure how we automatically detect when they should and shouldn't appear.
* With the current atom-number-based type names, we would need a way to add a prefix to the type names, but once we change to the new AMBER type name scheme, we shouldn't require this.  We would however need a way to make sure we don't redefine atom types, so we have to think of a way to enable parameter definitions to be split from residue definitions (as discussed in #1168).

**Comment by peastman** [comment]
I'm not doing anything on processAmberForceField.py.  If you want to try to fix it, go ahead.

**Comment by jchodera** [comment]
Ah, OK!  Do you mind if we also rewrite `processAmberForceField.py` for clarity?  I'm afraid it has some idioms that make comprehension perhaps more difficult than necessary for people new to the code.

I was thinking that basing this on the refactored version that @kyleabeauchamp and @juliebehr created for the old `gaff2xml` would be a good way to go:
https://github.com/choderalab/openmoltools/blob/master/openmoltools/amber_parser.py

**Comment by swails** [comment]
Refactoring would probably be safer with some tests thrown in for good measure.  Refactoring an untested code can be risky.

**Comment by jchodera** [comment]
There are lots of tests in the old gaff2xml (now openmoltools).  I would want to port those over as well.

**Comment by peastman** [comment]
> Refactoring would probably be safer with some tests thrown in for good measure. Refactoring an untested code can be risky.

Agreed!  I originally wrote that script for my own use, and only included those features needed for the specific input files I was processing.  It was never intended to be a generally useful conversion script for other people to use.  If you plan to make it into that, tests will be essential.

**Comment by jchodera** [comment]
Great!  Would you prefer we
1. Propose exactly what we'll change before starting to make the changes?
2. Start to refactor in a PR and discuss as the refactoring proceeds?
3. Create a PR for the refactored code and tests and then discuss?

Also, are you OK with us just creating a `devtools/parameter-conversion/amber/` directory and putting code and tests there?  Or should this be broken off into a different repo if it will grow in complexity for converting both polymeric and small molecule AMBER forcefields?

**Comment by peastman** [comment]
Let's discuss first.  What do you have in mind?

**Comment by jchodera** [comment]
Will start a new thread for that.

**Comment by jchodera** [comment]
We'll be tackling this with ParmEd, I think.  You can go ahead and close this, @juliebehr
