### ISSUE TITLE
Dummy atoms in OpenMM

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1193]
Is it possible to have the option of element==None for dummy atoms when loading PDB files ?

**Comment by jchodera** [comment]
We realized today at the OpenMM Jülich workshop that we don't seem to have a codepath in the `PDBFile` loader that would allow one to specify some atoms should match dummy atoms.

**Comment by peastman** [comment]
The question is, how would you specify it?  Ideally we'd just say that if the "element" field of the ATOM record is empty, that's a dummy atom.  Except a lot of PDB files found in the wild leave that field empty, so instead it tries to guess the element based on the atom name.

I suppose we could make up some magic code that you put in that field to indicate a dummy atom.  Do you know how other programs handle this?

**Comment by swails** [comment]
At least in Amber (and probably other programs) the dummy atom is part of the residue template. 

Of course all that differentiates a dummy atom from a regular one is a type that has no charge or LJ terms.

**Comment by peastman** [comment]
But what does it expect to be in the PDB file?  How does it recognize which atoms in the PDB are dummy atoms?

**Comment by leelasd** [comment]
@swails  Dummy atoms can also be a point charge/LJ sites that people are using for simulating halogen bonds, lone pairs of nitrogen and sulphur. It would be great if OpenMM can have a **X** atom type that can have any mass, charge or LJ values.

**Comment by jchodera** [comment]
Here's another idea: In PDB files that specify the element column for *any* atom record, assume that records missing the element are dummy atoms.

**Comment by swails** [comment]
> Here's another idea: In PDB files that specify the element column for any atom record, assume that records missing the element are dummy atoms.

Are you sure that all tools that add atoms (like modeling in missing loops, hydrogens, etc.) will add the element column for you?  Rosetta?  reduce?

**Comment by swails** [comment]
> @swails Dummy atoms can also be a point charge/LJ sites that people are using for simulating halogen bonds, lone pairs of nitrogen and sulphur. It would be great if OpenMM can have a X atom type that can have any mass, charge or LJ values.

I usually see this done with virtual sites, which are different (and far superior for this type of thing).  OpenMM provides very flexible support for virtual sites, and I can't really see much of an argument for using a dummy atom to model lone pairs and off-center charges.

**Comment by jchodera** [comment]
> Are you sure that all tools that add atoms (like modeling in missing loops, hydrogens, etc.) will add the element column for you? Rosetta? reduce?

No, but I'm saying that this is *a* way to allow programs to specify dummy atoms *without* introducing a new special dummy atom element label.

We should see if we can answer @peastman's question about how other programs handle dummy atoms.

Yet another alternative would be to add an optional argument to `PDBFile` to allow one to specify atom names, element names, or atom indices to be interpreted as dummy atoms.

**Comment by jchodera** [comment]
> I usually see this done with virtual sites, which are different (and far superior for this type of thing). OpenMM provides very flexible support for virtual sites, and I can't really see much of an argument for using a dummy atom to model lone pairs and off-center charges.

I don't have an opinion as to whether virtual sites (whose geometries are rigidly defined) or dummy atoms (which act like real point masses with valence terms) are the best way to model intermolecular interactions.  I haven't seen extensive scientific comparisons of the two approaches.

There is clearly value in supporting science based on both approaches by allowing OpenMM to simulate both.  Lots of models of both kinds exist, and people may want to use them.

In our case, all of the [multisite ion models](https://github.com/pandegroup/openmm/issues/1032) we are looking at use the dummy atom approach with flexible valence terms, so we'd like to start by implementing these before also testing virtual-site-based approaches (which are still tricky because there is only one real atom that must define a coordination geometry around it).

>  I can't really see much of an argument for using a dummy atom to model lone pairs and off-center charges.

I can't quite tell if this means you personally don't see the value of the flexible dummy atom approach, or if you are suggesting there is no point in adding support for this into OpenMM.  At the recent workshop in Jülich, there was at least one other group that was interested in this.

**Comment by swails** [comment]
> But what does it expect to be in the PDB file? How does it recognize which atoms in the PDB are dummy atoms?

The feeling I get here is that people are putting dummy atoms on a pedestal as though they are somehow special-er than real atoms.  The way I see it, dummy atoms are just *some atom* (can be any mass, any charge, any vdW parameter) that is added for some kind of convenience.  The usual candidates I've seen dummy atoms used for:

1. For "inactive" atoms in one end-point of an alchemical simulation added to make sure that the total degrees of freedom are the same in each end-state.
2. Provide a reference point (usually held in place via restraints or constraints) to define a reaction coordinate using internal coordinates (so that directionality is preserved as the molecule rotates) with a well-defined direction when calculating a PMF (steered MD, umbrella sampling, etc.)

In Amber, if you want *any* atom to appear in the prmtop, it must first appear in a residue template.  It makes no distinction for dummy atoms.  If you want a dummy atom added to your system, you either include it in a residue template, or define the dummy atom as a new residue with a single atom.  Something like:

```
ATOM    287  H8    G A   9      12.123   2.638   5.140  1.00 10.00           H  
ATOM    288  H1    G A   9       8.472  -1.192   1.514  1.00 10.00           H  
ATOM    289  H21   G A   9       7.713  -2.801   4.518  1.00 10.00           H  
ATOM    290  H22   G A   9       7.435  -2.689   2.795  1.00 10.00           H  
ATOM    291  P     G A  10       6.766  -0.522   8.783  1.00 10.00           P  
ATOM    292  OP1   G A  10       6.193   0.083  10.006  1.00 10.00           O  
ATOM    293  OP2   G A  10       6.312  -1.867   8.356  1.00 10.00           O  
ATOM    294  O5'   G A  10       6.528   0.489   7.576  1.00 10.00           O  
ATOM    295  C5'   G A  10       6.394   1.886   7.816  1.00 10.00           C  
ATOM    296  DU   DU A  11       x.xxx   y.yyy   z.zzz  1.00 10.00   <whatever> <-- dummy atom
```

Then there is a residue template for DU with a single atom, DU, that has a defined mass, charge, and atom type as provided by an frcmod file.  If you want to create a bond between DU and another atom (although usually you use restraints to avoid introducing unwanted exceptions), then you can either use the "bond" command directly in tleap or include DU as part of a pre-existing residue template whose bonding pattern is already defined.

This approach is a little clunky, but it gives all the flexibility that someone could want in "dummy" atoms.  This type of approach should already be supported by OpenMM (isn't it what you're trying to do with the multi-site ion model -- build residue XML files with the dummy atoms built-in?)  To me, "dummy atom" is not well-defined, and simply refers to the collection of all atoms that are not *not* dummy atoms.

My view is obviously limited by my experience with Amber, but I am having a hard time seeing why dummy atoms need to have (or even *should* have) special rules.  I've never really found it a challenge to introduce dummy atoms when I needed them (I've done both including them in residue templates *and* as a separate, single-atom residue).

**Comment by jchodera** [comment]
> This type of approach should already be supported by OpenMM (isn't it what you're trying to do with the multi-site ion model -- build residue XML files with the dummy atoms built-in?)

The issue here is when using the OpenMM `app` layer's `PDBFile > Modeller > ForceField` workflow, template matching is done based on `element` and bond connectivity.  The sample residue definition templates we created at the OpenMM workshop used the special element 0 (dummy atom), but `ForceField` would not match the residue because PDBFile` simply has no way to identify dummy atoms in the resulting `Topology` object.

We simply need a way to allow the user to specify dummy atoms in a convenient manner in the `Topology` generated from a `PDBFile`.  The rest of the `Modeller > ForceField` workflow should work fine.

**Comment by swails** [comment]
> I can't quite tell if this means you personally don't see the value of the flexible dummy atom approach, or if you are suggesting there is no point in adding support for this into OpenMM. At the recent workshop in Jülich, there was at least one other group that was interested in this.

Me personally, of course :).  It's a bold claim to say it's never needed, but lone pairs and off-center nonbonded sites are poster children for virtual sites.

> The issue here is when using the OpenMM app layer's PDBFile > Modeller > ForceField workflow, template matching is done based on element and bond connectivity.

Oh, wow, not at *all* what I expected.  Why do the residue XML files even both specifying atom names, then?  Are they used for anything?  Just a fall-back if elements are unknown?

Is this still a huge problem, though?  What keeps you from defining a residue containing only a single carbon atom and just treating that as a dummy?  Or defining a residue template with an extra carbon atom that you are using as a dummy?  You are still free to define a carbon atom type with any mass and parameter sets you want, right?  Is that not a dummy atom (i.e., an atom whose element doesn't matter and has no meaning, but is a special spherical 'probe' in your system)?

**Comment by swails** [comment]
But I guess `PDBFile` only assigns bonds that it knows about from the PDB?  So if a residue *has* an extra carbon that is forming bonds with other atoms in that residue for whatever reason, they would need to be added as `CONECT` records or OpenMM would fail to match that residue template?

**Comment by jchodera** [comment]
> Oh, wow, not at all what I expected. Why do the residue XML files even both specifying atom names, then? Are they used for anything? Just a fall-back if elements are unknown?

I don't think it's used as a fall-back.  `element` [is set to `None`](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L190-L194) (dummy) if no `element` attribute is specified in the `<Type/>` XML tag.

> Is this still a huge problem, though? What keeps you from defining a residue containing only a single carbon atom and just treating that as a dummy? Or defining a residue template with an extra carbon atom that you are using as a dummy? 

Not sure I follow.  Generally, the multisite ion models select a specific mass for these dummy atoms.  You currently can't overwrite an atom's mass in the residue's `<Atom/>` definition, though that would be a good idea for an `ffxml` interface extension.

> But I guess PDBFile only assigns bonds that it knows about from the PDB? So if a residue has an extra carbon that is forming bonds with other atoms in that residue for whatever reason, they would need to be added as CONECT records or OpenMM would fail to match that residue template?

Yes.  The problem again is that residue templates match only bonds and element types, which is generally very useful since we don't have to worry about atom name translations.  But when the residue template contains element types that `PDBFile` doesn't know about, it breaks our current workflow.

The solution for this case is pretty simple: Extend `PDBFile` to provide one or more ways for the user to specify dummy atoms (`element = None`).

**Comment by swails** [comment]
> Not sure I follow. Generally, the multisite ion models select a specific mass for these dummy atoms. You currently can't overwrite an atom's mass in the residue's <Atom/> definition, though that would be a good idea for an ffxml interface extension.

No, but the `Residue` XML section specifies atom types for each atom in the template, and you can define the mass in an `AtomType` tag, yes?  And the element can be specified separately.  So you can put in a template that atom type 280 or whatever is a Carbon with mass 15 dalton (for instance).

> Yes. The problem again is that residue templates match only bonds and element types, which is generally very useful since we don't have to worry about atom name translations.

Do we have a good idea for when atom name translations actually cause problems?  I don't feel like that gives Amber users much trouble (as I rarely if ever see an instance on the mailing list where this approach would solve a naming problem)...  But maybe it's much too late to change how OpenMM works in that regard now, anyway.

> The solution for this case is pretty simple: Extend PDBFile to provide one or more ways for the user to specify dummy atoms (element = None).

Isn't `element = None` indicative of a virtual site?  At least that's the assumption I've been working on for some time...

**Comment by jchodera** [comment]
> No, but the Residue XML section specifies atom types for each atom in the template, and you can define the mass in an AtomType tag, yes? And the element can be specified separately. So you can put in a template that atom type 280 or whatever is a Carbon with mass 15 dalton (for instance).

I think that would cause `ForceField` to break because elements (except for the special `element = None`) are hard-coded into [element.py](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/element.py).  See [this code](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L190-L194).

> Do we have a good idea for when atom name translations actually cause problems? 

Protons, mainly.

> I don't feel like that gives Amber users much trouble (as I rarely if ever see an instance on the mailing list where this approach would solve a naming problem)... 

What do AMBER users do with protons?  They either delete them or use `reduce`.  This avoids the need for that.

I believe some CHARMM forcefields also used atom names distinct from the PDB standard.

> But maybe it's much too late to change how OpenMM works in that regard now, anyway.

I consider this to be a huge advance.  It was inspired by the Desmond `viparr` approach, which also uses the element-and-bond graph.

**Comment by jchodera** [comment]
> Isn't element = None indicative of a virtual site? At least that's the assumption I've been working on for some time...

It doesn't have to be, though you are right that the current behavior of `addExtraParticles` assumes that `element = None` means these sites must be generated from virtual site rules:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/modeller.py#L978-L981

**Comment by peastman** [comment]
`element = None` indicates an "extra particle".  An extra particle is any particle that doesn't represent a physical atom.  That could be a virtual site, a Drude particle, or possibly something else.

>  So you can put in a template that atom type 280 or whatever is a Carbon with mass 15 dalton (for instance).

Correct.  There's no requirement that the mass agree with the canonical mass of the element.

Anyway, there's been a lot of discussion here, and I think some of it has kind of confused the issue.  If your force field involves extra particles of any sort, there are multiple workflows you might consider:

1. Load a PDB file that doesn't include the extra particles, then use `addExtraParticles()` to add them.

2. Load a PDB file that already includes the extra particles.

The problem is that we don't have good support for the second one.  There's no way to indicate to `PDBFile` that a particular atom should be an extra particle.  It always tries to fill in the element one way or another.  This isn't a fatal problem: after it's loaded, you can edit the `Topology` to set the element to `None`.  But it would be convenient if there were some way `PDBFile` could do that automatically.  So the question is, how?

**Comment by jchodera** [comment]
Here are some ideas:
* A. Have `PDBFile` perceive a predefined element name (e.g. `X`) as a dummy atom when it appears in the `element` field
* B. Have `PDBFile` perceive a user-specified list of element names as dummy atoms when they appear in the `element` field, using an optional `dummy_elements=` argument to `PDBFile`
* C. Have `PDBFile` interpret dummy atoms as those for which element fields are left unspecified in files where there is at least *one* specified element field
* D. Have `PDBFile` accept an optional argument specifying the list of atom names to be perceived as dummy elements

**Comment by peastman** [comment]
Something along the lines of (A) seems reasonable.  (B) seems unnecessarily complicated: as long as we pick something unlikely to cause confusion, I don't think there's a need for multiple codes or an extra argument.  I'm not confident that (C) and (D) will be sufficiently robust.

How about "EP" (for "extra particle")?  There are only three elements whose symbols start with E, all of which are incredibly exotic (europium, erbium, and einsteinium), so that's unlikely ever to be confused.  I believe Amber also uses the code "EP" to refer to virtual sites (or "extra points", as they call them) in some files.

**Comment by jchodera** [comment]
What about going with (B) but setting `dummy_elements='EP'` by default?  This gives us a very reasonable default that acts like (A) but gives the user flexibility to accommodate their own schemes.

**Comment by swails** [comment]
> What about going with (B) but setting dummy_elements='EP' by default? This gives us a very reasonable default that acts like (A) but gives the user flexibility to accommodate their own schemes.

+1.

ParmEd uses EP the same way that Amber does.  I'm still not sure if using EP here will be a good or bad thing for ParmEd's interoperability with OpenMM (since right now, ParmEd assigns that as the "zero" element).  So being able to turn that off if I need to would save me potential headache.  This seems like a nice approach.

**Comment by rafwiewiora** [comment]
I'm going to PR this, because it's necessary for handling the multiSite metal models in PDB files. 

To confirm, you guys settled on:
- EP element 
- `dummy_elements=EP` argument to `PDBFile`. Both for reading and for `.writeFile`? 

Basically whatever is passed as `dummy_elements` will be translated to `element = None` by `PDBFile` and vice versa at writing. So I should also be able to specify `dummy_elements=None` if I want?

**Comment by jchodera** [comment]
Correct.

**Comment by peastman** [comment]
Yes, except let's call the argument `extraParticleIdentifier`.  OpenMM calls these "extra particles", not "dummy atoms", and it uses camel case for names,

**Comment by rafwiewiora** [comment]
Sounds good.
