### ISSUE TITLE
Problems using processCharmmForceField.py for implementing OPLS-AA/M force field

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1200]
In Julich CECAM workshop, I tried implementing the OPLS-AA/M forcefield in OpenMM, with John's help. 
I used CHARMM formatted OPLS-AAM parameter files to get the xml file. processCharmmForceField.py is a slightly modified version of openmm/devtools/processCharmmForceField.py script (Thanks to John and Peter). I am getting this error that has nothing to do with force field file.
It would be great if I could get some feedback on rectifying this error.

```
Traceback (most recent call last):
  File "simulatePdb.py", line 10, in <module>
    simulation = Simulation(pdb.topology, system, integrator)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/simtk/openmm/app/simulation.py", line 77, in __init__
    self.context = mm.Context(system, integrator)
  File "/Users/Sriram/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 5076, in __init__
    this = _openmm.new_Context(*args)
Exception: All Forces must have identical exceptions

```

I have setup a github repo of the files used. 
https://github.com/leelasd/OPLS-AAM

**Comment by swails** [comment]
The way you have to implement OPLS-AA, due to their use of geometric combining rules, is through the `CustomNonbondedForce`.  In general, though, you need `CustomNonbondedForce` due to CHARMM's extensive use of NBFIX.  So then what you have is `CustomNonbondedForce` controlling the general Lennard-Jones interactions, and `NonbondedForce` controlling the electrostatic interactions (so you can get either GRF or PME for long-range electrostatics).

Some of the complication, and what is causing your error here, is that OPLS-AA has scaled 1-4 interactions, which are normally implemented via the `NonbondedForce` exception list (note I say "exception" instead of "exclusion" since some of these pairs are not fully excluded, but have interactions that differ from the standard Lennard-Jones interaction of those atom types).  `CustomNonbondedForce` does not permit exceptions -- it *only* has exclusions.  And for efficiency's sake, OpenMM requires that the list of exceptions/exclusions be the same for *every* nonbonded force in your `System` (with the sole exception that I know of being interactions in `CustomGBForce` that are explicitly labeled as no-exception).  But since the exceptions in `NonbondedForce` can be arbitrary, `NonbondedForce` can still (and should still) be used to compute the 1-4 Lennard-Jones interactions.

Looking at your script, [this part](https://github.com/leelasd/OPLS-AAM/blob/master/processCharmmForceField.py#L488-L489) is your problem.  You are only adding exclusions to `CustomNonbondedForce` when the exception in `NonbondedForce` is an *exclusion*.  Ergo, your `CustomNonbondedForce` does not have exclusions where your `NonbondedForce` has exceptions, giving you this error message.

The solution is to very simply remove the conditional there and just translate *all* exceptions from `NonbondedForce` into exclusions in `CustomNonbondedForce`.

One other thing I'll point out is that ParmEd actually supports the OPLS-AA force field in OpenMM (and it has been validated).  You can see where [I set the 1-4 exceptions according to the combining rule](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L2318-L2377) and then [where I build the `CustomNonbondedForce` for the L-J interactions](https://github.com/ParmEd/ParmEd/blob/master/parmed/structure.py#L2533-L2600)

**Comment by leelasd** [comment]
Thank you very much Jason !! I added the exceptions like you suggested and generated the oplsaam.xml file. But when i tried to do run the simulatePDB.py, I got the following error. 

```
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

pdb = PDBFile('input.pdb')
forcefield = ForceField('tip3p.xml','opls-aam.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
simulation = Simulation(pdb.topology, system, integrator)
simulation.context.setPositions(pdb.positions)
simulation.minimizeEnergy()
simulation.reporters.append(PDBReporter('output.pdb', 1000))
simulation.reporters.append(StateDataReporter(stdout, 1000, step=True, potentialEnergy=True, temperature=True))
simulation.step(10000)

$[1]+  Abort trap: 6           python simulatePdb.py >&log
```
All the files are https://github.com/leelasd/OPLS-AAM

**Comment by rmcgibbo** [comment]
The RMS force at the first step in your simulation is 2.8e8 kJ/mol/nm, and the system explodes in 1 step.

**Comment by leelasd** [comment]
Oh Wow !! We used the same parameter file to run protein simulations in NAMD without any such problems. Any suggestions about why this problem is arising ??

**Comment by swails** [comment]
> Any suggestions about why this problem is arising ??

Exclusions are probably wrong.

You can walk through the forces (by assigning force groups) and compute the net force and energy that come from each one and check which one is the culprit.  That should help narrow it down a bit.

**Comment by rmcgibbo** [comment]
Running the following in your repo:
```
import numpy as np
from simtk.openmm.app import *
from simtk.openmm import *
from simtk.unit import *
from sys import stdout

def getForceByClass(system, klass):
    for i in range(system.getNumForces()):
        f = system.getForce(i)
        if isinstance(f, klass):
            return f

pdb = PDBFile('input.pdb')
forcefield = ForceField('tip3p.xml','opls-aam.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=PME, nonbondedCutoff=1*nanometer, constraints=HBonds)
for i in range(system.getNumForces()):
    force = system.getForce(i)
    force.setForceGroup(i)


print('How many harmonic bonds?  ', getForceByClass(system, HarmonicBondForce).getNumBonds())
print('How many harmonic angles? ', getForceByClass(system, HarmonicAngleForce).getNumAngles())
print('How many torsions?        ', getForceByClass(system, PeriodicTorsionForce).getNumTorsions())
    
    
integrator = LangevinIntegrator(300*kelvin, 1/picosecond, 0.002*picoseconds)
context = Context(system, integrator)
context.setPositions(pdb.positions)

for i in range(system.getNumForces()):
    mean_magnitude = np.mean(np.linalg.norm(context.getState(getForces=True, groups=1<<i).getForces(asNumpy=True)._value, axis=1))
    print('Force %d (%20s): mean magniude: %.3g' % (i, system.getForce(i).__class__.__name__, mean_magnitude))
```


```
How many harmonic bonds?   0
How many harmonic angles?  0
How many torsions?         0
Force 0 (   HarmonicBondForce): mean magniude: 0
Force 1 (  HarmonicAngleForce): mean magniude: 0
Force 2 (      NonbondedForce): mean magniude: 9.91e+07
Force 3 (PeriodicTorsionForce): mean magniude: 0
Force 4 (  CustomTorsionForce): mean magniude: 0
Force 5 (    CMAPTorsionForce): mean magniude: 0
Force 6 (     CMMotionRemover): mean magniude: 0
Force 7 (CustomNonbondedForce): mean magniude: 9.92e+07
```

**Comment by rmcgibbo** [comment]
- No harmonic bond forces.
- Not angles
- No torsions
- Lots of explosive nonbondeds.

**Comment by swails** [comment]
How many exceptions?  Pure TIP3P is not interesting -- when you do flexibleConstraints off, there are no bonds (there are no torsions or angles, anyway).  And there should be no exceptions -- just exclusions.  It's a good first step to get "right", but there are still lots of ways to get TIP3P right and proteins wrong. :)

**Comment by rmcgibbo** [comment]
The PDB contains a whole solvated protein.

**Comment by swails** [comment]
Haha... then something is *very* not right :)

**Comment by leelasd** [comment]
OK wow that is absolutely insane result. I used the processCharmmForceField.py to convert par file and  It seems like there is a glitch in the conversion script !! Any other suggestions about using these par and top files for OpenMM ??

**Comment by rmcgibbo** [comment]
Start small, debug incrementally.

**Comment by swails** [comment]
I think @peastman wrote those scripts to work on the Drude FF from CHARMM.  I have readers in ParmEd that are a little more general I think; I just have to add some code to dump (and read) XML files for OpenMM.

In the meantime, just go through CHARMM unless you're willing to put in the time and effort to debug the conversion...

**Comment by leelasd** [comment]
Thanks @rmcgibbo and @swails, I will start with a small peptides in gas phase and will slowly start debugging. I will try these suggestions and let you know.
@swails  It would be awesome if you can make parmed dump the xml file. In fact, I overheard people at CECAM Macromolecular simulation work shop  discussing about implementing that capability.

**Comment by jchodera** [comment]
It would be great if we could get the OPLS-AA/M forcefield into OpenMM.

I had hoped the conversion scripts in `openmm/devtools/forcefield-scripts/` could be adapted for this purpose, but it's clear there is a long way to go to change them from one-off conversion scripts to something more generally useful.

We need to decide whether we want to standardize on using ParmEd for parameter conversion or doing a major cleanup of these scripts.

Tagging @ChayaSt and @rafwiewiora, who are working on the CHARMM and AMBER forcefield conversions in my lab, respectively.

@swails: What do you think about us standardizing on ParmEd?  Is this something where we could help out with the `ffxml` generation component?  Or should we just work out an automation scheme for converting and adding provenance data to the various CHARMM and AMBER forcefields?

**Comment by swails** [comment]
> @swails: What do you think about us standardizing on ParmEd? Is this something where we could help out with the ffxml generation component? Or should we just work out an automation scheme for converting and adding provenance data to the various CHARMM and AMBER forcefields?

Fine by me!  I'd like to see ParmEd be a one-stop-shop for file conversions (aided by integration with InterMol), so it seems to fit into the mission statement there rather nicely.  It also has a good deal of the functionality for reading CHARMM and AMBER file formats (all except prep, which can be added easily enough).

I haven't started writing XML readers or writers yet, so if someone wanted to start in with they're more than welcome.  You can also let me do it, and I'll bump it higher on my priority list (the only complication is going to be when do we use a built-in script to build a custom nonbonded force when `NonbondedForce` is insufficient, and I think I know the places this needs to be done).

**Comment by peastman** [comment]
If the plan is to use ParmEd for this rather than updating the conversion script, can this issue be closed?

**Comment by jchodera** [comment]
Yep!
