### ISSUE TITLE
CustomNonbondedForce.addInteractionGroup should accept arbitrary iterables

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1213]
`CustomNonbondedForce.addInteractionGroup` only seems to accept `list` arguments, but not `set`:
```
>>> from simtk import openmm
>>> force = openmm.CustomNonbondedForce('r')
>>> force.addInteractionGroup(set([0,1,2]), set([1,2,3]))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/choderaj/anaconda/lib/python2.7/site-packages/simtk/openmm/openmm.py", line 7859, in addInteractionGroup
    return _openmm.CustomNonbondedForce_addInteractionGroup(self, *args)
TypeError: in method 'CustomNonbondedForce_addInteractionGroup', argument 2 of type 'std::set< int,std::less< int >,std::allocator< int > > const &'
>>> force.addInteractionGroup([0,1,2], [1,2,3])
0
```

**Comment by peastman** [comment]
That's pretty strange.  The C++ method takes `std::set<int>` objects, and I don't think we're doing anything to customize the SWIG wrapping.  So the Python version ought to take a set.

**Comment by swails** [comment]
> That's pretty strange. The C++ method takes std::set<int> objects, and I don't think we're doing anything to customize the SWIG wrapping. So the Python version ought to take a set.

I think that would need to be specified through the SWIG typemaps, right?

**Comment by rmcgibbo** [comment]
There are default typemaps for STL containers.

**Comment by swails** [comment]
And it's understood how to take a Python set -> STL set?  (By implementation, I believe a Python set is equivalent to a STL unordered_set)

**Comment by rmcgibbo** [comment]
I had just assumed, but I didn't verfy.

**Comment by jchodera** [comment]
Any other ideas here?

**Comment by philiptzou** [comment]
I try to fix this problem by adding prepended code to Python wrapper and it looks work.

https://github.com/pandegroup/openmm/compare/master...philiptzou:pull-request-ordered-set-fix

Yeah but just looks. The thing I'm not sure about is whether the order of the input is crucial or not? I mean, does the expected energy changes if the internal order of either or both sets changed?

For example, will the expected energy results be the same for these two case?

### CASE 1

```python
from simtk import openmm
force = openmm.CustomNonbondedForce('r')
force.addInteractionGroup([0,1,2], [1,2,3])
```

### CASE 2

```python
from simtk import openmm
force = openmm.CustomNonbondedForce('r')
force.addInteractionGroup([0,2,1], [3,2,1])
```

If the expected results are different, perhaps we should mark this issue wontfix since Python don't have an "ordered set" and that's why the first SWIG maps `list` to `std::set` but `set` to `std::unordered_set`.

**Comment by peastman** [comment]
Nice!  The order isn't important, just which atoms it contains.

**Comment by philiptzou** [comment]
@peastman OK, so I think now it is good for a pull-request.
