### ISSUE TITLE
Excessive nonbonded forces with Amber14/lipid14 force field

### ISSUE THREAD

**Issue by dr-nate** [pandegroup/openmm#1218]
Hi all,

I'm tracking down a strange issue (with the help of @rmcgibbo ) that I believe is related to how input files are parsed by openmm and/or ParmEd, or alternatively some fundamental incompatibility with the code and newer amber forcefield (less likely), or some issue generated before that (even less likely, see below).

Basically, I was trying to run some simulations with the newest amber lipid forcefield lipid14, but I was getting NaN's pretty quickly (within the first few steps, seen via a force reporter). This is seems exclusively due to excessive nonbonded forces (resulting in 10^19 kJ/mole PE). It seems to be hardware agnostic, as I've reproduced it on CPU, GPU, and on my MacBook with Reference. However, when I feed the same files to Amber pmemd, the energies are fine, leading me to believe this is a OpenMM/Parmed parsing issue. 

I'm using a recent dev version of OpenMM (8eaf3c9c14b3a42db4c26af127533d846c63736f) and parmed 2.0beta3 in anaconda (np19py34_3).

I've tried to create a minimal system in which this happens, just a bunch of lipids and some water:
https://gist.github.com/dr-nate/3a8602d081be5601c2d8
https://gist.github.com/dr-nate/854c0c83b56abeeb5e68
https://gist.github.com/dr-nate/d03e15cf837ec871eea2

I generated the membrane in VMD, used Ambertools `charmmlipid2amber.py` to convert to Amber and fed that into tleap, loading `source leaprc.ff14SB` and `source leaprc.lipid14` and `loadamberparams frcmod.ionsjc_tip3p`.  Here's an OpenMM input file to get you started:

```
# OpenMM Imports
import simtk.openmm as mm
import simtk.openmm.app as app
from parmed import load_file, unit as u

# Load the Amber files
print('Loading AMBER files...')
prmtop = app.AmberPrmtopFile('structure.prmtop')
inpcrd = app.AmberInpcrdFile('structurewbox.inpcrd')

# Create the OpenMM system
print('Creating OpenMM System')
system = prmtop.createSystem(nonbondedMethod=app.PME,
                                nonbondedCutoff=8.0*u.angstroms,
                                constraints=app.HBonds,
)

system.addForce(mm.MonteCarloMembraneBarostat(1*u.atmospheres, 0, 300*u.kelvin, 1, 0, 25))

integrator = mm.LangevinIntegrator(
                        300*u.kelvin,       # Temperature of heat bath
                        1.0/u.picoseconds,  # Friction coefficient
                        timestep*u.femtoseconds, # Time step
)

platform = mm.Platform.getPlatformByName('CUDA')
prop = dict(CudaPrecision='mixed')
simulation = app.Simulation(prmtop.topology, system, integrator, platform, prop)

simulation.context.setPositions(inpcrd.positions)
simulation.context.setVelocitiesToTemperature(300*u.kelvin)
simulation.step(500)
```

Replace the top of the file with this to try with ParmEd to load the files:

```
# Load the Amber files
print('Loading AMBER files...')
parm = load_file('structure.prmtop', 'structurewbox.inpcrd')

# Create the OpenMM system
print('Creating OpenMM System')
system = parm.createSystem(nonbondedMethod=app.PME, 
    nonbondedCutoff=8.0*u.angstroms, constraints=app.HBonds)
```

You can see the extreme energy if you put a line like

```
simulation.context.getState(getEnergy=True).getPotentialEnergy()
```
in your file or use an interactive IPython session.

```
import IPython as ip
ip.embed()
```

You can specifically look at the different force groups if you do:

```
for i in range(system.getNumForces()):
    force = system.getForce(i)
    force.setForceGroup(i)

# 3 is nonbonded forces
simulation.context.getState(getEnergy=True, groups=(1<<3)).getPotentialEnergy()

```

**Comment by mpharrigan** [comment]
Set the box vectors?

**Comment by mpharrigan** [comment]
Works in parmed because of https://github.com/ParmEd/ParmEd/blob/4240fd33130d2f59a11fd76f3781d02905a3773f/parmed/structure.py#L1848 ?

**Comment by dr-nate** [comment]
I should stress that in my testing it *doesn't* work in both OpenMM or ParmEd, and was just tossing out the possibility that it was broken in both.

Box dimensions was one of the first things I suspected, like having a 10x error due to nm vs Å or something. But as far as I could tell that wasn't it.

**Comment by mpharrigan** [comment]
Oh, I thought it worked with the parmed version

**Comment by swails** [comment]
[OpenMM also sets default unit cell dimensions](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L837-L839). ParmEd will set them from the inpcrd file if you instantiate the `AmberParm` with both a prmtop and inpcrd file name (which is the correct way to do it following any NpT simulation where the box dimensions change from what tleap set them to).

First I'll share some cute little functionality that ParmEd has to aid in debugging sessions like these.  The first is built into the `parmed` interpreter: the `energy` command.  There are 3 variants of this command that you can use:

1. `energy` -- by itself, it uses the sander Python API to compute energies
2. `energy omm decompose` -- Uses OpenMM through the ParmEd interface to compute energies
3. `energy omm decompose applayer` -- Uses the `AmberPrmtopFile` inside OpenMM to set up the `System`, and computes the same decomposed energies.

It's a great way to compare the different implementations side-by-side.  So I did that:

```
swails@batman ~/BugHunter/OMMLipid $ parmed -p structure.prmtop -c structurewbox.inpcrd -n
Loaded Amber topology file structure.prmtop with coordinates from structurewbox.inpcrd

Reading input from STDIN...
> energy omm decompose
Computing a single-point energy for structure.prmtop
Bond     =         9453.9625416     Angle    =        13568.3724098
Dihedral =         7784.8072362     Nonbond  = 5769895202804831232.0000000
TOTAL    = 5769895202804861952.0000000
> energy omm decompose applayer
Computing a single-point energy for structure.prmtop
Bond     =         9411.6614307     Angle    =        13568.3724309
Dihedral =         7784.8072108     Nonbond  = 5769895202803462144.0000000
TOTAL    = 5769895202803492864.0000000
> energy
Computing a single-point energy for structure.prmtop
Bond     =         9453.9630590     Angle    =        13568.3690039
Dihedral =         7784.8060506     1-4 vdW  =         2053.5182285
1-4 Elec =        -3771.5670336     vdWaals  = 5770554204783616000.0000000
Elec.    =       -20537.1393336
TOTAL    = 5770554204783624192.0000000
```

The starting structure is **very** highly strained.  So sander, ParmEd/OpenMM, and OpenMM/OpenMM agree -- you have almost a mole of vdW energies.

If you don't believe that, [listen to cpptraj](https://gist.github.com/swails/9f5a23f1216e69e77f5b) where I ran the `checkoverlap` command to look for close contacts that would blow up MD simulations.

**Comment by rmcgibbo** [comment]
@swails, your hostname is "batman"?

**Comment by kyleabeauchamp** [comment]
Have u seen his logo?

**Comment by swails** [comment]
Some other nifty things you can do with ParmEd:

```Python
import parmed as pmd

system = pmd.load_file('system.xml') # Automatically detects file-type from contents and deserializes

parm = pmd.load_file('structure.prmtop', 'structurewbox.inpcrd')

# Pretend system came from parm in a previous script... or you can just call
# createSystem again and make it here

print pmd.openmm.energy_decomposition_system(parm, system)
```

It will give output where it automatically separates each force into its own group, creates a context, computes the energies for each one, and returns a list of tuples.  Here's an example of it in action:

```python
In [5]: import parmed as pmd

In [6]: import simtk.openmm.app as app

In [7]: parm = pmd.load_file('structure.prmtop', 'structurewbox.inpcrd')

In [8]: system = parm.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=8*pmd.unit.angstrom)

In [10]: pmd.openmm.energy_decomposition_system(parm, system)
Out[10]: 
[('HarmonicBondForce', 9453.962541632283),
 ('HarmonicAngleForce', 13568.372409783631),
 ('PeriodicTorsionForce', 7784.807236159451),
 ('NonbondedForce', 5.76989520280349e+18),
 ('CMMotionRemover', 0.0)]
```

You can also use ParmEd to effectively zero-out the L-J interactions, which should show that OpenMM gives the same *electrostatic* energy as sander (above):

```Python
In [11]: pmd.tools.addLJType(parm, ':*', epsilon=0).execute()

In [12]: system = parm.createSystem(nonbondedMethod=app.PME, nonbondedCutoff=8*pmd.unit.angstrom)

In [13]: pmd.openmm.energy_decomposition_system(parm, system)
Out[13]: 
[('HarmonicBondForce', 9453.962541632283),
 ('HarmonicAngleForce', 13568.372409783631),
 ('PeriodicTorsionForce', 7784.807236159451),
 ('NonbondedForce', -24309.309903006364),
 ('CMMotionRemover', 0.0)]
```

If you add up the 1-4 and normal electrostatics, the OpenMM and sander are within 1 kcal/mol of each other.  (You can also use ParmEd to increase the 1-4 scaling constants to nearly infinite in order to further separate the electrostatic energy to match sander, but that's unnecessary).

**Comment by swails** [comment]
(I'm not ignoring the Batman questions -- I'm just saving the important stuff for last).

**Comment by swails** [comment]
The final comment I'll make about this system is that it *seems* to have come from CHARMM-GUI (which I think is the recommended way to prepare Lipid 14 -- use CHARMM GUI, then use charmmlipidtoamber.py or whatever it's called, then feed that to leap and get drowned in a million warnings about split residues until a magic prmtop/inpcrd pops out).

CHARMM-GUI is *known* to make very highly strained systems, that it almost seems like only CHARMM itself is capable of minimizing.  I think you can also use sander to minimize the system as well.  But OpenMM seems to struggle on the GPU platforms (probably because the forces are so utterly immense, and may overflow the force accumulators which I think are integers).  At least in Amber, you have to minimize those systems in pmemd CPU before feeding it to the GPU, because the GPU minimizer fails with highly strained systems (and there are no plans to fix it).

A workaround if you need to stay in OpenMM is to transfer the L-J terms from `NonbondedForce` into a new `CustomNonbondedForce` that implements soft cores, then zero-out the epsilons in the actual nonbonded force.  This way, atoms will still push each other apart, but it's something more like [a Hawaiian volcano](http://dosecc.com/wp-content/uploads/2014/10/Hawaii-Volcano1.jpg) than [Mt. St. Helens](https://i.ytimg.com/vi/IhU6jml6NY4/maxresdefault.jpg)

**Comment by swails** [comment]
> @swails, your hostname is "batman"?

Yes.  And my shitty old laptop's hostname is "Robin".  And the external HDDs I have attached to each machine is named Alfred.

And my *really* shitty laptop I got from who knows where that I was able to use for 7 minutes before it died was named Catwoman.  (It may have died right after I assigned the hostname.)

> Have u seen his logo?

That's only one Batman-related logo -- and here it is:

```

                 ./       |      |        \.
               .:(        |i __ j|        ):`.
             .'   `._     |`::::'|     _.'    `.
           .'        "---.j `::' f.---"         `.
     _____/     ___    ____      __    __  ____   ___    
    |      \   |   |  |     `__'|  \  /  ||    | |   \    
    |  .-.  | .'   `| | .-.  |-/|   \/   || ___| |  . \   
    |  |_|  | |  i  | | |_| /"":|        || |    | | \ \  
    |       / | .^. | |    /::::|        || |__. | |  \ \ 
    |  ----'  | | | | |    \ :: |        ||  __| | |  |  )
    |  |     .' ''' `.|  |\ \   |  i  i  j| |    . | /  /  
    |  |     |   _   ||  | \ \  |  |\/|  || |__. | |.  / .
   [|  |     |  | |  ||  |  \ \ |  |  |  ||    | |    /   ].
  ] `--'     :--' `--::--'   \_|`--' ::--"|____|-"-- /    :[
  |      __  ::-'''`.:' "--.    .----::.----:: ,.---._    :|
  [  .-""  "`'              \  /      "      `'       `-. :].
 ]:.'                        \/                          `.:[
 |/                                                        \|

ParmEd: a Parameter file Editor

```

And as much as it may seem related, it's actually not :):

BATMAN

Shave off the bottom hump on the B and you have P.  A and M are the same, T can be largely reused to form an R, and the back of the N matches the back of the D.  That's why the R, D, and E look the worst and the P looks like someone forgot to connect the lines in the middle.

P.S. -- This is why, in my less-lazy days, I would replace my *actual* prompt with `bash$` wherever I copied and pasted.  But whatever.  I'm not embarrassed.  Just means my office is the batcave.

**Comment by swails** [comment]
[There are 8 logos `parmed` has to choose from at startup total](https://github.com/ParmEd/ParmEd/blob/master/parmed/tools/logos.py)

**Comment by dr-nate** [comment]
This is a great writeup Jason. Troubleshooting problems is always tricky, and that's a whole bunch of new tools for me to use. I'll close this since it's indeed my problem.
