### ISSUE TITLE
Conda on travis fails due to change in default install path

### ISSUE THREAD

**Issue by jhprinz** [pandegroup/openmm#1241]
This is not really an OpenMM Bug, but it affects all omnia conda installable packages somehow. It seems that miniconda has changed its default install path from `~/miniconda` to `~/miniconda2` (at least for python 2.7) and this caused all travis builds to fail immediately. 

fixing to `export PATH=$HOME/miniconda2/bin:$PATH`

solved it for me. Hope this avoids some trouble.

Correction: You need to fix it everywhere in your scripts of course...

**Comment by rmcgibbo** [comment]
Yay. I suspect this means that Python3 will soon be the default.

**Comment by jchodera** [comment]
You can get around this by adding `-p miniconda` to the installation command, I think.

Also:
* I wish they would tell us these things ahead of time
* Maybe we should see if we can standardize an omnia `devtools/` tree that can be a git subproject in simple projects, where project-specific differences are encoded as environment variables?

**Comment by rmcgibbo** [comment]
- Personally, I don't really see it as a problem." Live on the bleeding edge, die on the bleeding edge." This is what you expect when you have the CI servers always asking for "latest" (`Miniconda-latest.sh`) and an active project. The alternative of complete stability is RHEL, and then you get ancient packages.
- They really don't have the capability to reach out _to us_ -- they're giving away this product for free with no strings attached or mailing list that we're required to sign up for -- but you always have the ability to reach out to them. n.b. someone filed an issue about this: https://github.com/ContinuumIO/anaconda-issues/issues/513. I've also always had positive interactions with Continuum people in twitter.
- The git subproject thing is not a bad idea.

**Comment by jchodera** [comment]
> The git subproject thing is not a bad idea.

I think I created this empty project a while ago with the goal of importing some sort of basic skeleton there:
https://github.com/omnia-md/devtools

**Comment by mpharrigan** [comment]
Some potential problems with using a submodule:

1. travis.yaml and appveyor.yaml aren't in a subdirectory. you'd have to set up a symlink or something
2. there's actually not that much boilerplate / common code: it's just installing miniconda and running conda-build. conda recipes, building docs, deployment are all different among projects
3. no way (?) to test changes to the submodule. you'd have to somehow trigger a build from an omnia project that pulls in the proposed changes in the submodule

I'm -1 on submodules. I'm +1 making ci similar among projects so that if someone implements a change on one project (e.g. msmbuilder switching to built-in travis support for deployment), it can easily be copied over to other projects

We just had an issue where I copied over improvements from msmbuilder appveyor support to mdtraj and it broke it because mdtraj uses a directory named `appveyor-ci/` instead of `appveyor`. A submodule may be overkill in a scenario where consistent directory naming would have sufficed

**Comment by jchodera** [comment]
Here's what I am thinking of:
https://github.com/omnia-md/devtools

I'll try to answer the list of issues you raise:
> travis.yaml and appveyor.yaml aren't in a subdirectory. you'd have to set up a symlink or something
Unlike the boilerplate in `devtools/`, these YAML files contain information that must be tailored to the project---such as the project name.  The good news is that these files hardly ever need to change---just create it once, tailor it, and forget about it.
> there's actually not that much boilerplate / common code: it's just installing miniconda and running conda-build. conda recipes, building docs, deployment are all different among projects
There's a fair amount.  For both travis and appveyor, we have to
* configure the build environment
* upload the package to binstar
* build and upload docs to S3 (if relevant)
> no way (?) to test changes to the submodule. you'd have to somehow trigger a build from an omnia project that pulls in the proposed changes in the submodule
We can have a simple skeleton project on github under `omnia-md/` that demonstrates how to use it and is automatically tested via travis and appveyor.
> We just had an issue where I copied over improvements from msmbuilder appveyor support to mdtraj and it broke. 
This is one of the problems with the "just copy things around" solution: It's very fragile unless you are super diligent about always updating things, and always updating things takes lots and lots of times if you have a couple dozen projects to worry about.

**Comment by jchodera** [comment]
I think this can be closed and the discussion migrated to https://github.com/omnia-md/omnia-md
