### ISSUE TITLE
Nose-Hoover thermostat?

### ISSUE THREAD

**Issue by swails** [pandegroup/openmm#1306]
Does anybody have a `CustomIntegrator` implementation of the Nose-Hoover thermostat that they would be willing to share?

**Comment by jchodera** [comment]
I haven't seen one, but I also wouldn't recommend Nosé-Hoover for new production simulations not intended to replicate earlier results due to its ergodicity problems.

**Comment by jchodera** [comment]
[This paper from Scheraga](http://www.ncbi.nlm.nih.gov/pmc/articles/PMC2577381/) describes a useful discrete-timestep implementation (Eqs 6-17) that may aid your implementation.  It looks like it should be straightforward to implement.

**Comment by swails** [comment]
The iso-kinetic integrators proposed out of Tuckerman's lab are built from NHC integrators.  So I wanted that as a starting-point for building those integrators (which, as far as I've been able to tell from the articles, don't have those ergodicity problems).

**Comment by jchodera** [comment]
You mean [these isokinetic thermostats](http://scitation.aip.org/content/aip/journal/jcp/118/6/10.1063/1.1534582)?

**Comment by jchodera** [comment]
An interesting [analysis of these thermostats for a simple system](http://arxiv.org/abs/1004.4294).  

Behavior looks pretty good, though I am always worried about recommending these in general for cases in which we simulate two uncoupled subsystems (as in alchemical free energy calculations, where the ligand is partially or fully decoupled from the rest of the system) since there is no way for energy exchange to occur between uncoupled modes unless stochastic thermostats are coupled to each degree of freedom.

**Comment by swails** [comment]
Thanks!
