### ISSUE TITLE
Improved SWIG wrappers break example plugin

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1343]
@rmcgibbo b0baa00d77e2b5b8a43cabe932c1ffca9a7dd7fc broke the python bindings for the example plugin (see https://github.com/peastman/openmmexampleplugin/issues/14), as `stripUnits` has been removed. I don't quite understand what you've changed to handle units on the C side. Can you take a look at the example plugin?

I also think it would be a good idea to add the example plugin to the Travis-CI.

**Comment by rmcgibbo** [comment]
Do you want to try adding Travis-CI?

![](https://media.giphy.com/media/aZ4sQUpybai5y/giphy.gif)

**Comment by peastman** [comment]
@rmcgibbo do you have any thoughts about the best way to fix it?

**Comment by swails** [comment]
[Here is what @rmcgibbo did.](https://github.com/pandegroup/openmm/blob/master/wrappers/python/src/swig_doxygen/swig_lib/python/typemaps.i#L21-L112)

He implemented the Python code through the equivalent syntax in the C API and then added it to a whole bunch of type maps to intercept the variables before they hit the core OpenMM API and remove the units.  A clever approach, but it was a pain to do (at least from an outsider's view looking in), and there were residual typemaps he had to add afterwards (exposed through the addition of extensive unit tests).

The easiest thing to do, probably, is just copy the `typemaps.i` file from OpenMM into the plugin to expose it in Python land.

**Comment by rmcgibbo** [comment]
Thats a good idea. The other possibilities would be to
- modify the example plugin just to reimplement the remover stripUnits finction, but otherwise do nothing (still use the pythonprepen)
- have openmm install typemaps.i somewhere in the include/ tree during installation, so that the plugin could use it without neeedIng it's own copy in its source tree

**Comment by swails** [comment]
> modify the example plugin just to reimplement the remover stripUnits finction, but otherwise do nothing (still use the pythonprepen)

I thought about that, but it won't work if compactdefaultargs is off (which happens by default now), right?  Or you mean stripUnits specifically for each function?

> have openmm install typemaps.i somewhere in the include/ tree during installation, so that the plugin could use it without neeedIng it's own copy in its source tree

I like this idea.

**Comment by rmcgibbo** [comment]
Yeah, my first option requires continuing to use the old (and less good)
swig option.

**Comment by swails** [comment]
Installing the OpenMM `typemaps.i` file somewhere it can be included sounds like a win to me.

**Comment by peastman** [comment]
Sounds reasonable.  Where should we install it?  At the top level "include" folder, next to OpenMMSwigHeaders.i?  Or inside a "swig" subdirectory?  And if the latter, should we also move OpenMMSwigHeaders.i into that directory?

**Comment by rmcgibbo** [comment]
I'm not really sure what the purpose of `OpenMMSwigHeaders.i` being installed is, but if it wouldn't be too disruptive, I think having them both inside a `swig/` directory would probably be ideal.

**Comment by peastman** [comment]
It's installed for the same reason: so plugins can include it.  Otherwise, SWIG couldn't match up types between them.  For example, if your plugin had a Force subclass, SWIG would create a completely new Force wrapper class that was different from the one in the main openmm module, and you would get an error when you tried to use it somewhere that required a Force like System.addForce().

I don't think it's too disruptive.  The current version of the example plugin is written to work with 6.3.  And we'll create a new version that's designed to work with 7.0.  We never guarantee backward compatibility for plugins, so requiring minor changes like this is ok.
