### ISSUE TITLE
Bromine miss interpreted as Boron in PDB

### ISSUE THREAD

**Issue by sqamara** [pandegroup/openmm#1392]
I think I found a bug when making a PDBFile.  When given the residue Br it interprets it as B. 

Here is a gist exemplifying this https://gist.github.com/sqamara/6ed6ddfc904a5224e558

**Comment by peastman** [comment]
The problem is that your HETATM record is missing the element specification.  That's supposed to go in columns 77-78.  See http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#HETATM.  If it's missing, PDBFile will try to guess an element based on the atom name, but that isn't reliable.
