### ISSUE TITLE
MD simulation of a small molecule in gas phase

### ISSUE THREAD

**Issue by leelasd** [pandegroup/openmm#1398]
I am trying to perform a gas phase MD calculation at 298.15 Kelvin for Aniline. Potential energies seem to be deviating a lot (+-25%). Is there any thing I am missing ? Any suggestions are highly appreciated 
[XML](https://gist.github.com/leelasd/e6138765544df44f2c73) and [PDB](https://gist.github.com/leelasd/0acabe62a135927c8964) files are here. 

```
import mdtraj as md
from simtk.openmm import app,KcalPerKJ
import simtk.openmm as mm
from simtk import unit as u
from sys import stdout,exit
def Minimize(simulation):
	simulation.minimizeEnergy()
	position = simulation.context.getState(getPositions=True).getPositions()
	energy=simulation.context.getState(getEnergy=True).getPotentialEnergy()
	app.PDBFile.writeFile(simulation.topology, position, open('gasmin.pdb', 'w'))
	print 'Energy at Minima is %3.3f kcal/mol'%(energy._value*KcalPerKJ)
	return simulation

temperature=298.15*u.kelvin
pdb = app.PDBFile('anilin.pdb')
modeller = app.Modeller(pdb.topology, pdb.positions)
forcefield = app.ForceField('anilin.xml')
system = forcefield.createSystem(modeller.topology, nonbondedMethod=app.NoCutoff,  constraints=None)
integrator = mm.LangevinIntegrator(temperature, 1/u.picosecond,  0.001*u.picoseconds)
simulation = app.Simulation(modeller.topology, system, integrator)
simulation.context.setPositions(modeller.positions)
simulation=Minimize(simulation)
simulation.context.setVelocitiesToTemperature(temperature)
simulation.reporters.append(app.PDBReporter('gas_output.pdb', 100))
simulation.reporters.append(app.StateDataReporter('data.txt', 100, progress=True, temperature=True, potentialEnergy=True, density=True,totalSteps=10000,speed=True))
simulation.step(50000)
```

**Comment by peastman** [comment]
What do you mean when you say the potential energies are "deviating"?  What are they deviating from?

In a constant temperature simulation, the potential energy will naturally fluctuate.  The smaller your system, the larger the relative magnitude of those fluctuations.  What is happening that you think is wrong?

**Comment by leelasd** [comment]
Hi Peter, 

I meant to say the std in Energy and Temperature is high. I am trying to do calculate Heat of Vaporisation of Aniline. For that I am trying to calculated the gas phase average Potential energy of Aniline at 298.15 K.  Average values of Energy and Temperature from simulation were 38.52 +- 10.28 KJ/mol and  273.995143 +- 62.780194. This introduces almost 3 kcal/mol uncertainty in the calculation. Is there any way to minimise this uncertainty.

**Comment by peastman** [comment]
How about running a longer simulation?  The relative fluctuations in the energy scale as O(sqrt(N)) in the number of particles.  Since you're simulating a very small molecule in gas phase, N is tiny and the relative fluctuations are large.  But you're trying to measure its average value.  The uncertainty in that scales as O(1/sqrt(t)) in the length of the simulation.  So you can always reduce it by increasing the simulation length.

I have a couple of suggestions about your script.  You aren't specifying a platform, which means it will try to pick the fastest one available.  If you have a GPU, that will be either CUDA or OpenCL.  But since your system is so tiny, it will actually be much faster to use the CPU platform, or even Reference.  You can specify that by passing `mm.Platform.getPlatformByName('CPU')` as a fourth argument to the Simulation constructor.  If it was using the GPU before, that should make it a lot faster.

I also noticed the way you're converting the energy: `energy._value*KcalPerKJ`.  That's not very safe, because it depends on what the current units are.  A better way to write it is `energy.value_in_unit(u.kilocalories_per_mole)`.

**Comment by leelasd** [comment]
Thanks for the suggestions Peter, I added these options to the script. 
I ran a 1ns simulation and the average values for Pot. Energy and Temperature  are  still 42.869718+-10 KJ/mol and  296.368481+-67.634491 Kelvin. 
I am benchmarking OpenMM with our own Monte Carlo code (BOSS). Average values from the two packages are close but the standard deviation in energy from OpenMM is very big.

**Comment by peastman** [comment]
My point is that the standard deviation *should* be large.  That simply comes from the fact that you have a tiny system.  Making the simulation longer doesn't change that.  But it does give you a more accurate estimate of the mean (and also of the standard deviation).

**Comment by leelasd** [comment]
Ok I get it now. Thanks for the insights Peter.

**Comment by peastman** [comment]
Can this be closed?

**Comment by leelasd** [comment]
Sure Peter !!
