### ISSUE TITLE
Feature Request: Covalent bonds through periodic boundary conditions

### ISSUE THREAD

**Issue by leeping** [pandegroup/openmm#1411]
Hi there,

I'm running a kind of calculation where a molecule is covalently bonded to itself through a periodic box (think of an infinitely long carbon nanotube or something like that).  I don't think OpenMM currently supports covalent bonds going through the periodic boundary, because when I run the simulation the system folds in on itself (i.e. atoms A and B on opposite sides of the periodic box, which are bonded to each other, both move toward the center of the box).

I think this situation could be fixed if we applied the minimum image convention before computing the displacement vectors that go into our bonded energy terms, and from the user's perspective it should be a simple on/off switch.  Is this a suggestion that makes sense?  How hard would it be to implement?

Thanks,

- Lee-Ping

**Comment by rmcgibbo** [comment]
Would that be a big performance hit?

**Comment by swails** [comment]
> Would that be a big performance hit?

We're talking about bonded terms.  Those are already practically free compared to any of the nonbonded terms.  I can't imagine using MIC displacements for computing bonds, angles, and torsion angles is going to introduce a noticeable performance hit.

**Comment by leeping** [comment]
Hopefully this won't be too difficult to implement either.  We already have periodic distances for the custom external force.

**Comment by swails** [comment]
It would probably be time-consuming, though.  There are a lot of places this needs to be updated (harmonic/custom bonds, angles, periodic,R-B,custom,cmap torsions) on 4 different platforms (for many the CPU implementation is just the Reference implementation.

**Comment by peastman** [comment]
And most of the time, it would be incorrect to do this.  It's only in very specialized cases like this one where it ever makes sense to apply periodic boundary conditions to bonded terms.  And even in this case, it's only a few bonds that are supposed to wrap.  Most of the bonds in the system should be handled in the standard way.

**Comment by leeping** [comment]
Because of this, I think the default should be for the feature to be disabled, but the user could turn it on when they need it. :)  Something like `forcefield.createSystem(periodicBonds=True)`.

Of course it would be great if you could implement the feature in a matter of minutes - but if it's more difficult than that (and/or not worth it from your perspective), then I'd be happy to implement it myself.  Then I would write unit tests and contribute the feature in the usual way.  Let me know what you prefer.

Thanks,

- Lee-Ping

**Comment by peastman** [comment]
Like I said, it's not just a matter of a global option.  It's something that should only apply to a handful of specific bonds.  And even then, it shouldn't apply generic periodic boundary conditions.  The bond isn't supposed to connect whatever periodic copy happens to be closest, it's supposed to connect one specific periodic copy.

**Comment by swails** [comment]
> On Mar 10, 2016, at 4:51 PM, peastman <notifications@github.com> wrote:
> 
> Like I said, it's not just a matter of a global option. It's something that should only apply to a handful of specific bonds. And even then, it shouldn't apply generic periodic boundary conditions. The bond isn't supposed to connect whatever periodic copy happens to be closest, it's supposed to connect one specific periodic copy.
> 

We've discussed this before. In principle you're right. In practice I can't envision the two definitions EVER being different. Although I'm certainly curious to hear them if they do exist. 

For true covalent bonds that is. For bonds that are really intermolecular restraints the counter examples abound. 

It would still be useful to have pbc-aware bonded terms.

**Comment by peastman** [comment]
Here's a simple example.  Consider an infinite chain in a square box.  It stretches across the box from one side to the other, and connects to the next copy of itself when it reaches the end.

Now rotate the chain by 90 degrees.  The bonds that cross the box boundary will spontaneously break and reconnect to a different periodic copy.  Now you have an infinite chain running along a different axis.

If you're running an MD simulation, and if the bonds are fairly strong, this would be unlikely to happen since there would be a huge energy barrier.  But if the bonds are weak (perhaps they're just there as restraints), or if you're doing Monte Carlo, it could easily happen.

**Comment by leeping** [comment]
Hi Peter,

In the kinds of simulations that I'm trying to do, I am trying to represent covalent bonds across the box boundary.  I agree there are hypothetical situations where atom "A" could switch which periodic copy of atom "B" it is bonded to, but because the periodic copies are separated by a lattice vector (which is much longer than a covalent bond), usually it is unambiguous which periodic copy should be bonded, especially if the initial coordinates are set up correctly.

Thanks,

- Lee-Ping

**Comment by swails** [comment]
> Here's a simple example. Consider an infinite chain in a square box. It stretches across the box from one side to the other, and connects to the next copy of itself when it reaches the end.
> 
> Now rotate the chain by 90 degrees. The bonds that cross the box boundary will spontaneously break and reconnect to a different periodic copy. Now you have an infinite chain running along a different axis.

I don't think this can happen in MD even with the smallest permissible box size.  The box can't be any smaller than ~1.5 to 2 nm, as that would require a L-J cutoff of smaller than 0.75 nm.  As a result, the rotation angle at which the periodic image would "switch" would introduce a prohibitively high strain energy for all but the weakest of bonds. And if this *can* happen, your simulation is hosed anyway, even if you did do the *right* thing (whatever that is).

As it stands now, OpenMM is incapable of conveniently simulating infinite surfaces while other packages can.  The formalism for supporting such simulations is, IMO, straightforward.  Maybe it's worth introducing something like `CustomPBCBondForce` and `CustomPBCAngleForce`, or allowing `CustomBond/Angle/TorsionForce` to access either a MIC PBC value or the "canonical" value.

**Comment by swails** [comment]
@leeping -- you *can* actually get OpenMM to do your bidding here, although it is NVT only and will be a little bit of a pain to implement.

Basically the trick is to use `CustomCompoundBondForce` and build the imaging directly into your energy expression.  Since this force gives you direct access to the x-, y-, and z-coordinates of the atoms in the bond, angle, and/or torsions in the expression, you can simply compute the MIC distance from that by hard-coding the unit cell dimensions into the energy expression (it will obviously be much easier to hard-code support for an orthorhombic UC, but such a restriction is a small price to pay to get something off the ground sooner rather than later).

In the meantime, I still think either adding a new `Custom*Force` for MIC-bonded terms, or exposing PBC-specific geometries in the existing `Custom*Force` objects, would be a very convenient extension that would not compromise @peastman's sensibilities of having the existing code suddenly adopt the possibility of doing the wrong thing :).

**Comment by rmcgibbo** [comment]
I thought there was a new periodicdistance function in some of the custom
forces?

**Comment by swails** [comment]
Just `CustomExternalForce` -- and that's distance from a fixed point in space.

**Comment by swails** [comment]
BTW -- congrats Dr. Robert!

**Comment by rmcgibbo** [comment]
> Just CustomExternalForce -- and that's distance from a fixed point in space.

Got it.

Also, thanks :)

**Comment by leeping** [comment]
Yes, congratulations. :D  I was sad that I couldn't make it to your farewell party.  I'm not sure if you'll be around tomorrow - I'm coming by for a visit.

@swails:  That's a cool idea. :)  Unfortunately I am doing NPT simulations which is an important aspect of the project.  I considered using `periodicDistance`, but it would still be quite difficult to use this cleverly to get a periodic torsion to work.

**Comment by swails** [comment]
> @swails: That's a cool idea. :) Unfortunately I am doing NPT simulations which is an important aspect of the project. I considered using periodicDistance, but it would still be quite difficult to use this cleverly to get a periodic torsion to work.

Then you'd also need to add in a CustomIntegrator that also effectively implemented a MC barostat.  It really would be nice if the unit cell vectors were accessible from custom forces (and the `usesPeriodicBoundaryConditions` for those forces appropriately set based on whether that information is required or not).

What do you think about some of these proposals, @peastman? (Specifically making UC parameters available as global variables in custom forces/integrators and/or providing a way to use MIC displacements for bonded terms as part of a custom energy expression)

**Comment by leeping** [comment]
I thought that a standard integrator with a MC barostat should serve this purpose already, although I'm not sure if a periodic bonded force would decrease the acceptance probability of the MC moves.  It seems that a MC move should not introduce major stretches in the periodic bonds; rather, the "periodic molecule" should be scaled in the box.

On the other hand, I just realized that my NPT simulation only has volume fluctuations along directions where there are no periodic bonds, so it's not urgent for me to have this.  :)

**Comment by swails** [comment]
Then see if a membrane barostat will work for you with the MIC displacements implemented by hand in the customcompoundbondforce. That should get you off the ground immediately if you need it.

**Comment by leeping** [comment]
That's true.  I think we could try getting periodic bonds to work using customcompoundbondforce while we wait for the feature (I talked to Peter yesterday and he said it wouldn't be difficult to do).

**Comment by peastman** [comment]
> It seems that a MC move should not introduce major stretches in the periodic bonds; rather, the "periodic molecule" should be scaled in the box

MonteCarloBarostat always moves molecules as a whole.  It scales their center positions, but doesn't change the relative positions of atoms inside them.  There are two reasons for this: 1) it gives better acceptance rates, and 2) it doesn't mess up constrained distances.

There's nothing really difficult about adding an option to apply periodic boundary conditions in a bonded force.  It's just a lot of small changes needed in a lot of places.

**Comment by peastman** [comment]
To make sure I'm clear on exactly what this would involve, we're talking about adding a boolean "apply periodic boundary conditions" option to the following classes: CustomBondForce, CustomAngleForce, CustomTorsionForce, CustomCompoundBondForce, and CustomCentroidBondForce.  If you enable the option, it applies to *all* bonds in that particular force object.

Would that be sufficient for your needs?  Does it also need to work with standard (rather than custom) forces?  If so, which ones?

**Comment by leeping** [comment]
Hi Peter,

I was actually thinking about having this for all of the standard bonded forces, for example HarmonicBondForce, HarmonicAngleForce, AmoebaBondForce, PeriodicTorsionForce and so on.  You are right that if we enable this option, then it applies to all bonds in that force object.

If we have this for the standard bonded forces, then it makes sense to have them for the custom bonded forces as well.  By "bonded" I mean that the groups of atoms involved in the interaction are specified at the start of the simulation, rather than determined on-the-fly by a cutoff.

Thanks,

- Lee-Ping

**Comment by swails** [comment]
Of course, if you have the Custom force support in place, you can always implement the "standard" forces very easily.  In fact, the only one you really *need* is `CustomCompoundBondForce`, and then you can introduce new functions `periodic_distance`, `periodic_angle`, and `periodic_torsion` to complement `distance`, `angle`, and `torsion`.

That may actually be the most flexible, since then you get to *explicitly* specify which measurements use PBC and which don't, rather than using a sledgehammer on all of them.  May also be easier from an implementation perspective, although @peastman would have to weigh in on that one.

I actually like that approach myself, since it seems minimally invasive and a rather natural extension to the existing API.  The question is whether

```Python
force = CustomCompoundBondForce(2, '0.5*k*periodic_distance(p1, p2)**2')
force.addPerBondParameter('k')
```
is more inconvenient than
```Python
force = HarmonicBondForce(usePBC=True)
```
by enough of a margin to justify the latter.  (Of course, for torsions it's a little worse:
```Python
force = CustomCompoundBondForce(4, '0.5*k*(1+cos(periodic_dihedral(p1, p2, p3, p4)*per-phase))')
force.addPerBondParameter('k')
force.addPerBondParameter('per')
force.addPerBondParameter('phase')
```
vs
```Python
force = PeroidicTorsionForce(usePBC=True)
```
)

**Comment by peastman** [comment]
An advantage of the latter approach is that you can create your System with a standard ForceField, then just call a few methods to enable PBC.  You don't need an entirely custom definition for all your forces.

**Comment by swails** [comment]
> An advantage of the latter approach is that you can create your System with a standard ForceField, then just call a few methods to enable PBC. You don't need an entirely custom definition for all your forces.

True.
