### ISSUE TITLE
Harmonize platform properties

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1450]
We might consider harmonizing how we handle platform properties.

Currently, each property has its platform name as a prefix, which requires that any use of properties have a lot of platform-specific code. Not all capabilities are available on all platforms, and using properties that are not available will result in an exception, but exception handling can not be effectively used because of the inconsistencies in property names.

What about
* retain old property names for compatibility but mark them as "deprecated"---they might be removed in future
* introduce new property names which are coherent among platforms, and a `setProperty` flag that allows us to ignore exceptions if the property is not available
* introduce an API call that allows us to query if the platform has this property/capability

* CC #909: Standardize approach for handling precision

**Comment by peastman** [comment]
How about this:

1. Remove the platform name from all properties, so e.g. `CudaPrecision` will become just `Precision`.
2. For backward compatibility, make all the relevant methods tolerate names prefixed with the platform name (ignoring case).  So if a) there is no property with the specified name, and 2) the name you specified starts with the platform name, and 3) there does exist a matching property without the platform name, then it will accept that as a match.
3. Continue to rely on exceptions for cases where no match is possible.  (For example, if you specify the `DeviceIndex` property but get the CPU platform, it will throw an exception.)

> introduce an API call that allows us to query if the platform has this property/capability

Once the names are unified, this can be done simply by checking for the property name.  For example, `'Precision' in platform.getPropertyNames()`.

**Comment by jchodera** [comment]
This sounds like it would work, but doesn't (2) present an overengineered solution? What about having some aliases, where `CudaPrecision` is interpreted as `precision`?  Is that simpler than doing something that will *expand* the number of degenerately-treated platform properties (including ones added in the future)?

**Comment by peastman** [comment]
I suppose we could just have a hardcoded list of translations for the existing properties.  In some ways I find that uglier, but the effect would be pretty much the same.

**Comment by peastman** [comment]
Two additional points.

Each platform class defines static methods that return the names of its properties.  For example, `CudaPlatform::CudaDeviceIndex()` returns "CudaDeviceIndex".  The return values will of course change, but I suggest keeping the method names the same.  There's really not much advantage to changing them, since you already have to know what class you're calling it on, and it would just create extra compatibility problems (or duplicated methods).  And the return value doesn't need to be identical to the method name: that's the whole reason the methods exist.

Second, I think we should leave the "OpenCL" prefix on the properties `OpenCLPlatformIndex` and `OpenCLPlatformName`.  That clarifies that we're using the word "platform" in the OpenCL sense, not the OpenMM sense.

**Comment by peastman** [comment]
Ditto for `CudaCompiler` and `CudaHostCompiler`.  Those are really intrinsically CUDA-specific properties, and those names clarify what they refer to.

**Comment by mpharrigan** [comment]
+1 keeping those prefixes in those specific cases
