### ISSUE TITLE
Prmtop simulation fails with CUDA, works ok with CPU

### ISSUE THREAD

**Issue by jaimergp** [pandegroup/openmm#1478]
Hi guys,

I am trying to extend a NAMD 25ns simulation I did months ago in my desktop computer (i7-4790, 16GB RAM, Nvidia 970). I am using OpenMM 7.0-rc1 (conda build), CUDA 7.5 as provided by an Arch-Linux installation with Nvidia drivers 364.19. I am also using parmed to load the binary coordinates and velocities.

However, the simulation always fails with ValueErrors ("Energy is NaN") with CUDA. After a long debugging session, I found out that it works OK if I just change the platform from CUDA to CPU.

For example, with CUDA, the simulation fails after 50 fs if I impose no constraints nor rigid water. However, it fails immediately with rigid water and HBonds constraints. This is not the case with the CPU implementation.

During those 50 fs, the CUDA implementation reports absurd temperatures and energies, that continue rising and rising, until they hit the NaN threshold. CPU, however, lists correct temperatures (~300K).

I've attached a Zip containing the input files and an IPython notebook with the minimal code. 

Am I doing something wrong here? Thanks in advance!

[AmberRestartNaNEnergies.zip](https://github.com/pandegroup/openmm/files/247315/AmberRestartNaNEnergies.zip)

**Comment by peastman** [comment]
I figured out the problem.  It's one that's come up before.  It has a very easy workaround, but I've never come up with a fully satisfactory "fix" for it.

First, I'll jump to the punchline: swap the order of your calls to `setPeriodicBoxVectors()` and `setPositions()` and everything will work fine.  Or call `setDefaultPeriodicBoxVectors()` on the System before you even create the simulation.

Now the story that leads up to it.  Internally, the CUDA and OpenCL platforms store atom positions translated into a single periodic box.  That's important for maintaining accuracy when working in single precision.  So you call `setPositions()`, and it wraps them to the currently specified box dimensions.  The default box vectors specified in your System (which it got from sys.top) roughly correspond to a 10.9 nm cube, so that's what it gets wrapped to.  But then you immediately call `setPeriodicBoxVectors()` with a totally different set of vectors: a 104 nm cube.  And clearly your positions were intended to be in a box that size, since a lot of coordinates are much larger than 10.

So if you first set the box vectors, then the positions, everything is fine.  The positions get wrapped to the correct box dimensions.  But if you set the positions before the box vectors, they get wrapped to a much smaller box, which totally messes them up.

**Comment by jaimergp** [comment]
Hello @peastman! Thanks a lot for your time. That was indeed the problem, both in the minimal code sample and my full script. It's so interesting how a tiny change can make such a huge difference.

I don't know about any methods that could help workaround the issue, but maybe a special method called `self.consolidate()` to be called internally, before launching a simulation when a GPU platform is in use? This is a wild guess and probably not what you want, but I don't know how to help back... Maybe it's just a documentation thing, like writing a section called __Known caveats__ or something like that.

Anyway, thanks a lot once again!

**Comment by swails** [comment]
@peastman -- IIRC, `Context` keeps track of which box (or how many translations in each vector direction, perhaps) each particle is in so that it can "unwrap" the particle back when calling `getState()` (if wrapping is turned off), right?

Why can we just have `setPeriodicBoxVectors` do that same unwrapping *before* setting the new box vectors, set the new box vectors, then re-wrap if using either of the GPU platforms?

**Comment by peastman** [comment]
> Why can we just have setPeriodicBoxVectors do that same unwrapping before setting the new box vectors, set the new box vectors, then re-wrap if using either of the GPU platforms?

That would make sense.  So I guess the principle would be that if you query the positions, then change the box vectors, then query the positions again, they should be unchanged.  The challenge, though, is whether that can be done without losing precision in the process.  Let me look into it.

**Comment by peastman** [comment]
The fix is merged.  Give it a try.
