### ISSUE TITLE
Consider re-implementing Continuous2DFunction and Continuous3DFunction

### ISSUE THREAD

**Issue by jlmaccal** [pandegroup/openmm#1507]
The current implementation of of `Continuous2DFunction` and `Continuous3DFunction` on GPUs has poor performance due to global memory latency.

`Continuous2DFunction` has to access 16 floats = 64 bytes per grid point, while `Continuous3DFunction` has to access 64 floats = 256 byes per grid point. In either case, for even relatively small grids the full set of coefficients will not fit into L1 cache, which causes poor performance, as seen in #1502.

It seems like we could get improved performance by accessing the grid itself, which is 16x or 64x smaller, and doing the fitting and interpolation on the GPU. This would add more compute, but this should be much less costly than the global memory latency. Of course at some point, the grid itself will be too large for L1 cache, but there isn't really a way around that.

**Comment by peastman** [comment]
I don't think that would be practical.  It uses natural splines, which means that to find the coefficients for one patch, you need four complete rows and four complete columns from the original grid.  It isn't local.

**Comment by jlmaccal** [comment]
I don't understand your argument. It's not local now either, but it needs 16x or 64x as much data. Assuming the table itself fits in cache, wouldn't this lead to a big improvement?

**Comment by peastman** [comment]
The point is that calculating the spline coefficients for a patch is a very expensive operation, and the cost of doing it scales with the total size of the grid.  Loading data from global memory has a latency of a few hundred clock cycles, but that can be partly masked by occupancy.  Recomputing the spline coefficients could easily take thousands of clock cycles.

Also, this one particular example isn't representative of all situations.  It just happens to be a case where the original tables would fit in cache, but the spline coefficients don't.  If the tables were a little smaller, or if there were only one of them instead of two, then the cache hit rate would be a lot higher.  Conversely, if the tables were a bit larger then even the original tables would be too big for cache.
