### ISSUE TITLE
DCDReporter with a truncated octahedron box

### ISSUE THREAD

**Issue by isjoung** [pandegroup/openmm#1510]
DCDReporter writes trajectories in an orthogonal box even if the box is truncated octahedron. I used AMBER topology file (prmtop) with a truncated octahedron box and saved trajectories using `DCDReporter`. cpptraj program in AmberTools also gives a warning in the process of the tracjectory.
```
Warning: Trajectory box type is 'Orthogonal' but topology box type is 'Trunc. Oct.'.
```
I checked visually using VMD and the boundary of the water box looks orthogonal.

**Comment by peastman** [comment]
Can you provide directions on how to reproduce this?  I checked the code, and it writes both box lengths and angles:

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/dcdfile.py#L138-L145

> I checked visually using VMD and the boundary of the water box looks orthogonal.

That doesn't mean the unit cell is rectangular.  It always wraps coordinates to a rectangular volume, but for a triclinic unit cell, adjacent volumes will be staggered relative to each other.  See http://docs.openmm.org/7.0.0/userguide/theory.html#periodic-boundary-conditions.

**Comment by isjoung** [comment]
Test files are attached.
[dcdtest.tar.gz](https://github.com/pandegroup/openmm/files/303919/dcdtest.tar.gz)

The trajectory can be converted into amber text format trajectory file:
```
cpptraj
> parm model.prmtop
> trajin trajectory.dcd
> trajout trajectory.mdcrd
> go
```
The box information in `trajectory.mdcrd` is changed to an orthogonal box.

>That doesn't mean the unit cell is rectangular. It always wraps coordinates to a rectangular volume, but for a triclinic unit cell, adjacent volumes will be staggered relative to each other.

If it is true, isn't there any risk in analyzing the trajectory file?

**Comment by swails** [comment]
@isjoung was right -- even though `DCDFile` had the *ability* to write arbitrary box shapes, `DCDReporter` was only passing in box lengths, which were interpreted as the lengths of an orthorhombic cell.  #1512 fixes this.

But what @peastman was saying is that a "triclinic" shape always looks rectangular-ish.  When it's, for instance, a truncated octahedron, the equivalent triclinic cell looks like a slanted version of an orthorhombic cell.  They're exactly equivalent representations, but non-orthorhombic cells look like "staggered" tessellations rather than the familiar regularity of a unit cell with right angles.  [See this example for a 2-dimensional analogy](http://pubs.acs.org/appl/literatum/publisher/achs/journals/content/jpccck/2016/jpccck.2016.120.issue-4/acs.jpcc.5b12054/20160129/images/medium/jp-2015-12054v_0006.gif)

**Comment by peastman** [comment]
They aren't even slanted.  There's an equivalent representation where each periodic box is rectangular, but they're staggered relative to each other.  See figures 6 and 7 at http://www.rug.nl/research/portal/files/3218542/1997JComputChemBekker.pdf.
