### ISSUE TITLE
LocalEnergyMinimizer fails to minimize with Drude particles

### ISSUE THREAD

**Issue by mvanvleet** [pandegroup/openmm#1511]
Using either the DrudeSCFIntegrator or the DrudeLangevinIntegrator, the LocalEnergyMinimizer subroutine fails to correctly minimize (either the atomic or virtual) sites of a system. A minimum working example is given here for the water dimer using the SWM4NDP model:

[drude_minimizer.zip](https://github.com/pandegroup/openmm/files/303486/drude_minimizer.zip)

which outputs as follows:

```
Minimizing...
----
Coordinates and energies before minimization:
(0.8552, 2.5319000000000003, 2.2608) nm
(0.91, 2.5144, 2.3376) nm
(0.8026, 2.608, 2.2863) nm
(0.8556512408218999, 2.5439194146197, 2.2817826982183504) nm
(0.8552, 2.5319000000000003, 2.2608) nm
(0.8492000000000002, 2.3889, 2.0055) nm
(0.7915000000000001, 2.3536, 2.0733) nm
(0.8896000000000002, 2.4646000000000003, 2.0485) nm
(0.8456516062641501, 2.3971864223658, 2.0282261286666) nm
(0.8492000000000002, 2.3889, 2.0055) nm
-2032.85055345 kJ/mol
----
Coordinates and energies after LocalEnergyMinimizer:
(0.8551999704244236, 2.531900195976075, 2.260800451756365) nm
(0.9099999977857649, 2.5143999827768675, 2.33759996354917) nm
(0.8026000013111838, 2.607999978433201, 2.286299968885833) nm
(0.8556512231935605, 2.543919522246498, 2.2817829507974823) nm
(0.8552000439085916, 2.5318998969246214, 2.2607996779704265) nm
(0.8491999912763981, 2.388900115694063, 2.0055002278656575) nm
(0.7915000119966211, 2.3535999936161547, 2.073299965372238) nm
(0.8895999909363373, 2.464600001609725, 2.048500042243112) nm
(0.8456516017207123, 2.397186489620751, 2.028226264619432) nm
(0.8491999923728902, 2.388899834972972, 2.0054997023643453) nm
-9.82241286565 kJ/mol
----
Coordinates and energies after simulation.minimizeEnergy:
(0.8410445840972143, 2.5245334271710496, 2.2764572065426605) nm
(0.9326683107635286, 2.5240325900523954, 2.30526542355249) nm
(0.8228905670576157, 2.6164219907679516, 2.2551811749311588) nm
(0.8561139168957205, 2.543277914810875, 2.278002129056226) nm
(0.8408992790330531, 2.5225595924801767, 2.273134386763173) nm
(0.8589206398703804, 2.408505824738055, 2.02090781369903) nm
(0.7987440328938786, 2.334300490176868, 2.017063744909525) nm
(0.8480070512821346, 2.4436441720319357, 2.111123130848168) nm
(0.8443393679268947, 2.4004928159000296, 2.038623374198271) nm
(0.859405542833805, 2.4081650934312133, 2.019184150017638) nm
-22.2599039274 kJ/mol
```
Site positions are largely unchanged using LocalEnergyMinimizer, however are minimized correctly using simulation.minimizeEnergy.

Note that, by removing the Drude sites and using a LangevinIntegrator, both LocalEnergyMinimizer and simulation.minimizeEnergy correctly minimize particle positions and yield similar results.

**Comment by peastman** [comment]
Fixed by #1522.  This was another manifestation of the same problem as before, when a Drude particle is exactly on top of its parent atom.  When using PME, the reciprocal space term includes all interactions, even ones that are supposed to be excluded (like between a Drude particle and its parent).  So we have to subtract them off in real space.  But if they're at exactly the same position, that produces a nan.

My previous fix (in #1509) was to make it skip those interactions.  But that isn't quite right.  As the distance goes to zero, the force also goes to zero, so skipping the interactions produces the correct force.  But the energy actually goes to a nonzero value, so that still needs to be subtracted.

By the way, Simulation.minimizeEnergy() is just a convenience function that calls LocalEnergyMinimizer.  It doesn't matter which one you use.
