### ISSUE TITLE
CustomCentroidBondForce errors

### ISSUE THREAD

**Issue by juanmit** [pandegroup/openmm#1571]
Hi,

I am trying to set up position restraint simulations in my system using CustomCentroidBondForce.
However, it always gives me errors as followings:

NotImplementedError: Wrong number or type of arguments for overloaded function 'CustomCentroidBondForce_addBond'.
  Possible C/C++ prototypes are:
    OpenMM::CustomCentroidBondForce::addBond(std::vector< int,std::allocator< int > > const &,std::vector< double,std::allocator< double > > const &)
    OpenMM::CustomCentroidBondForce::addBond(std::vector< int,std::allocator< int > > const &)

`rest_force=mm.CustomCentroidBondForce(2,"0.5*k*(r-r0)^2")`
`rest_force.addPerBondParameter('r0')`
`rest_force.addPerBondParameter('k')`
`system.addForce(rest_force)`
`rest_force.addBond(ind1,ind2,[dist_ref,force_constant])` ----error comes from this line

Please help me out. Thanks a lot.

--Hongbin

**Comment by jchodera** [comment]
I believe the atom indices have to be vectorized into a list.

Change this line
```python
rest_force.addBond(ind1,ind2,[dist_ref,force_constant])
```
to this:
```python
rest_force.addBond([ind1,ind2],[dist_ref,force_constant])
```

**Comment by juanmit** [comment]
You are absolutely right!!!! Thanks a lot!!!!!

--Hongbin

**Comment by juanmit** [comment]
I have a follow-up question about CustomCentroidBondForce. 
How to define/set_up the reaction coordinate? Let's say along Z-axis only. 
Thanks a lot. 

--Hongbin

**Comment by jchodera** [comment]
> How to define/set_up the reaction coordinate? Let's say along Z-axis only. 

Can you elaborate on what you're trying to do?

**Comment by juanmit** [comment]
Sorry about the confusion. 

I am trying to get a PMF of a ligand binding system. For testing, I started with the position where the ligand binds the receptor. 
So now I would like to get more samples by "dragging" the ligand away with a specific direction, but can not find any descriptions about it.  

--Hongbin

**Comment by jchodera** [comment]
That's not an easy problem, since if you really want a "specific direction", you will need to define a direction vector with respect to several collections of atoms in the receptor. 

If you can get by with defining the direction vector with individual atoms in the receptor and ligand, I'd check out [`CustomManyParticleForce`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomManyParticleForce.html#simtk.openmm.openmm.CustomManyParticleForce), since it should be easy to specify your force in terms of harmonic restraints on dihedrals, angles, and distances using this force.  For example, you might use the scheme from [Fig 2 of this paper by Roux](http://www.pnas.org/content/102/19/6825.full.pdf) to define your protein-ligand restraints.

**Comment by peastman** [comment]
> I'd check out CustomManyParticleForce

I think you probably meant CustomCompoundBondForce, not CustomManyParticleForce?

**Comment by jchodera** [comment]
Yes, my apologies! You want [`CustomCompoundBondForce`](http://docs.openmm.org/7.0.0/api-python/generated/simtk.openmm.openmm.CustomCompoundBondForce.html#simtk.openmm.openmm.CustomCompoundBondForce), which allows you to specify all of the atoms involved in the [restraint scheme](http://www.pnas.org/content/102/19/6825.full.pdf) by index.

**Comment by juanmit** [comment]
@jchodera @peastman Thanks a lot for commenting on my questions.  I will read more about these schemes and figure out which one works best for me. 

--Hongbin

**Comment by peastman** [comment]
Closing since the question has been answered.
