### ISSUE TITLE
Sporadic segfaults with simultaneous use of AmoebaMultipoleForce and CustomHbondForce

### ISSUE THREAD

**Issue by mvanvleet** [pandegroup/openmm#1654]
In the process of putting together a force field that uses both AmoebaMultipoleForce and CustomHbondForce, I'm experiencing sporadic segmentation faults when I try and run a simulation that uses both forces simultaneously. My test files can be found [here](https://github.com/pandegroup/openmm/files/556295/seg_fault_tests.zip); the test in each subdirectory is run with a 
```bash
 $ bash submit_all.sh 
```
command, which *should* calculate the interaction energies of a benzene dimer and each of the monomers separately.

I don't have any diagnosis for the problem, but the following observations may help:

1. When running these calculations with only the AmoebaMultipoleForce (see subdirectory 01_just_multipoles), I never experience segfaults.
2. Similarly, when running these calculations with only the CustomHbondForce (see subdirectory 02_just_hbond_force), I never experience segfaults.
3. However, when computing the energy of the benzene dimer with *both* the AmoebaMultipoleForce and the CustomHbondForce (see subdirectory 03_combined), I get (seemingly random) segfaults. Both the dimer calculation and the monomer calculations are prone to this segfault, though running the code repeatedly (shown below) causes different calculations to fail at different times. In some cases all calculations proceed smoothly.

```bash
 $ bash submit_all.sh
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7f2f91a6da20> > 18.5378279682 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f2f91a6da80> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x7f2f91a6da50> > -4.68109553417 kJ/mol
----
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x7f23763bea50> > 0.0 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f23763bea80> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7f23763bea20> > 8.98131728499 kJ/mol
----
submit.sh: line 35:   792 Segmentation fault      python run_benzene.py
$ bash submit_all.sh
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7f23efb99a20> > 18.5378279682 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f23efb99a80> > 0.0 kJ/mol
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x7f23efb99a50> > -4.68109553417 kJ/mol
----
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x7f1937b1da50> > 0.0 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7f1937b1da80> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7f1937b1da20> > 8.98131728499 kJ/mol
----
<simtk.openmm.openmm.CustomHbondForce; proxy of <Swig Object of type 'OpenMM::CustomHbondForce *' at 0x7fdb06434a50> > 0.0 kJ/mol
<simtk.openmm.openmm.CMMotionRemover; proxy of <Swig Object of type 'OpenMM::CMMotionRemover *' at 0x7fdb06434a80> > 0.0 kJ/mol
<simtk.openmm.openmm.AmoebaMultipoleForce; proxy of <Swig Object of type 'OpenMM::AmoebaMultipoleForce *' at 0x7fdb06434a20> > 8.97823172782 kJ/mol
----
```

I'm happy to provide whatever hardware/software information is needed to solve this issue.

Thanks in advance,
Mary

**Comment by peastman** [comment]
What platform and OS are you using?  And if it's the CUDA platform, what GPU and CUDA version?

**Comment by mvanvleet** [comment]
For these tests I was using the CPU platform on a Linux x86-64 machine.

I should check if I encounter the same problem on the CUDA platform; I'll get back to you on this.

**Comment by peastman** [comment]
It looks like it's getting confused by the virtual sites while building the system.  They all get `axisType` set to `ZOnly` but `multipoleAtomZ` set to -1, which leads to the segfault.  This is probably just another case that's never come up before, since AMOEBA doesn't use virtual sites.  Hopefully it won't be hard to fix.

**Comment by peastman** [comment]
Actually, it's a really obscure corner case.  It ought to be throwing exceptions in a couple of different places, so I need to add more error checking to catch the problem earlier.

When you specify atom types to define axes in a `<Multipole>` tag, those are matched against the atoms it's bonded to.  But of course, a virtual site doesn't have bonds in the standard sense.  This issue also comes up when defining exclusions: how do you identify the 1-2, 1-3, and 1-4 neighbors of a virtual site?  The convention we've selected is that a virtual site is considered to be bonded to the first atom it's defined based on.  That's the one specified by `atomName1` in the `<VirtualSite>` tag.  But in your case, that's a carbon.  Atom 2 is the hydrogen, which is what you say defines the Z axis in the `<Multipole>` tag.  But it doesn't consider the virtual site to be bonded to atom 2, only to atom 1.  And it really ought to throw an exception right then, when it fails to find a matching atom.

But anyway, the solution to your problem is easy.  Just modify the `<VirtualSite>` tags so the hydrogen is atom 1 instead of atom 2.

**Comment by peastman** [comment]
Wait--after updating my code to the latest from the repository, I can't even reproduce this anymore.  Are you sure this wasn't just the old problem with `ZOnly` mode?

**Comment by mvanvleet** [comment]
Peter, you're absolutely right. I'd forgotten to update my OpenMM build with the new ZOnly fix; once I did this the mysterious segfaults stopped :) My apologies for the inconvenience.

**Comment by peastman** [comment]
Ok, I'm slightly less insane than I though I might be then. :)  But I'll still add a bit of extra error checking.
