### ISSUE TITLE
DCDFile Overflow Crashes Simulations

### ISSUE THREAD

**Issue by rmcgibbo** [pandegroup/openmm#1659]
> This is a kind of complicated issue, and I think it needs some discussion. Could you open an issue describing the problem? I can see several possible ways of addressing it, but none of them is obviously right.

As requested, I'm opening this issue. I think the underlying problem is reasonably well described in https://github.com/pandegroup/openmm/pull/1658#issue-187146893.

To reiterate, a simulation using a `DCDReporter` will crash after 2**31-1 steps due to an overflow in DCDFile. Using a 2 fs timestep, this gets you to about 4 microseconds, so it's not particularly hard to trigger. (I'm surprised nobody else has reported this bug before).

**Comment by peastman** [comment]
A DCD file records the total length of the simulation it was generated from.  Different fields include the step size, the interval (in time steps) between saving frames, and the number of previous time steps from an earlier part of the simulation before the start of this file.

The error happens when writing the field that contains the total length of the simulation in time steps: `self._firstStep+self._modelCount*self._interval`.  I've been thinking about various ways of trying to address this while still keeping the information in the file as accurate as possible.  What about this as a possibility?  When the total length of the simulation is about to exceed what we can store, rewrite the header to have the interval between saves be 1.  For example, if you have a 2 fs time step and write a frame every 10,000 time steps, then instead record a time step of 20 ps and a frame written every time step.  That way, the total length of the simulation still gets stored correctly, which is probably the most important thing.

**Comment by rmcgibbo** [comment]
This would be fine for our use cases.

**Comment by jchodera** [comment]
You're not planning to write more than 2 billion frames to the file?  :)

**Comment by rmcgibbo** [comment]
In that case, we'd use more than one file.
