### ISSUE TITLE
Charge vector NonbondedForce vs CustomNonbondedForce

### ISSUE THREAD

**Issue by mlund** [pandegroup/openmm#1662]
When extracting a charge vector (or sigma; epsilon) from a system, see function below, I noticed

1. that `getPerParticleParameterName()` exists in `CustomNonbondedFoce` but not in `NonbondedForce` and
2. the charge returned by `getParticleParameters` has a unit in the case of `NonbondedForce`, but not in the case of `CustomNonbondedForce`

The code below works, but it would be nice (and safer) if one could skip the type checks and conversion.

```python
def getChargeVector( force ):
    ''' Get partial charges for all particles '''
    chargelist = []
    Zndx = -1 # index in particle parameters where to find charge
    if isinstance(force, NonbondedForce):
        Zndx = 0
    if isinstance(force, CustomNonbondedForce):
        for i in range(len( force.getParticleParameters(0) )):
            if force.getPerParticleParameterName(i)=='charge':
                Zndx=i
    if Zndx>=0:
        chargelist = []
        for i in range( force.getNumParticles() ):
            charge = force.getParticleParameters( i )[ Zndx]       
            if isinstance(charge, Quantity):
                charge = charge / elementary_charge
            chargelist.append( charge )
        return chargelist
    return None
```

**Comment by Lnaden** [comment]
`getPerParticleParameter` will not give you units because it does not know what units your parameters are in due to its generality. 

Based on how you formed the question, I'm assuming you built a `CustomNonbondedForce` to mimic a `NonbondedForce` energy function. However, the `CustomNonbondedForce` is not limited to only Lennard-Jones and Coulomb-like energy expressions. A perfectly valid energy expression could be 

```python
energy = " 42*charge1/r^14 + 7*charge2^2/(C*r^28)"
```
In this case, your units on the per-particle parameter "charge" would have to be kJ*nm^14/mol  I'm not sure when this energy expression would be used either, but it is a valid one. The `CustomNonbondedForce` class cannot figure out what units the per-particle parameters are simply because you can give it ANY energy expression.

OpenMM will strip the units off any parameter you pass in into the base units of OpenMM, but it assumes you the user know how those parameters are used in the energy expression afterwords.

**Comment by mlund** [comment]
Thanks, that makes sense - I indeed use a custom electrostatic potential.  I naively thought that charge could be extracted like in the `NonbondedForce`, but found that the (hard coded) parameter index had moved as `CustomNonbonded` obviously can have an arbitrary number of parameters. Having a `NonbondedForce::getPerParticleParameterName()` would provide a consistent interface for locating parameters (regardless of units).

**Comment by Lnaden** [comment]
The order that you add parameters to `CustomNonbondedForce` (or any `Custom*Force`) is consistent with the index its assigned. So if you need a lookup like that, you could create a dictionary where the key is your name for the parameter and its value is the index it was added/assigned by the `Custom*Force`.

e.g. 
```python
parms = {'charge':0, 'sigma':1, 'epsilon':2}

force.getParticleParameters(index)[parms['charge']] 
```

or some other scheme.

**Comment by mlund** [comment]
I'm generally loading from xml files and wouldn't know the order in advance. In my specific example, the order of charge, sigma, epsilon differed in the nonbonded an customnonbonded xml. Not a big deal as the above search, albeit inelegant, works. Thanks for your swift help!

**Comment by Lnaden** [comment]
Not a problem!

Could you go ahead and close this if its resolved for you?
