### ISSUE TITLE
A bug in amoeba multipole force?

### ISSUE THREAD

**Issue by yumipxd** [pandegroup/openmm#1688]
In line 339 and 348 of “openmm/plugins/amoeba/platforms/cuda/src/kernels/multipoleElectrostatics.cu” (and in 1512 and 1521 of  openmm/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp ), whether "fIZ" should be replaced by "fJZ" ?

**Comment by peastman** [comment]
It does look like it.  @andysim this is in your code.  Could you take a look at it?

**Comment by peastman** [comment]
It looks to me like this is a mistake, but one that doesn't actually change the results.  That's because the only place `fIZ` or `fJZ` ever gets used is in the sum `fJZ+fIZ`.  So if you add something to the wrong one, it doesn't matter.  The sum of the two is still the same.

**Comment by andysim** [comment]
You're correct, @peastman.  Because both variables are initialized [here](https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp#L1472-L1473), the code is correct, but misleading, as written.  I think I was part way through just removing the "I" and "J" from those variable names (that term is equal and opposite), but simply didn't finish it up.  The clearest way to write it is to replace the offending "fIZ" with "fJZ", as suggested by @yumipxd; that would be most consistent with the equivalent permanent multipole terms [here](https://github.com/pandegroup/openmm/blob/master/plugins/amoeba/platforms/reference/src/SimTKReference/AmoebaReferenceMultipoleForce.cpp#L1472-L1473).  Sorry for the confusion - I'll open a PR soon to clear this up.

**Comment by peastman** [comment]
Great, thanks.

**Comment by yumipxd** [comment]
I see what you mean，thank you，@peastman and @andysim
