### ISSUE TITLE
Poor performance converting vec3 lists to numpy arrays

### ISSUE THREAD

**Issue by tristanic** [pandegroup/openmm#1689]
Hi,

I've been running some timings on a live simulation, looking for bottlenecks. For my test structure (1438 residues, 50 timesteps between GUI updates) I'm currently seeing 2-3 frames per second - so roughly 300-500 milliseconds per frame. At each GUI update I get the positions and the forces (the latter to do a quick check for overly large forces indicating instability), and between the two of these, about 150-180 milliseconds is going simply into converting the two 21,400*Vec3 lists into numpy arrays. 

```
c = sim.context
%timeit state = c.getState(getPositions = True, getForces = True)

> 10 loops, best of 3: 35.1 ms per loop

state = c.getState(getPositions = True, getForces = True)
%timeit state.getPositions(asNumpy=False)

> The slowest run took 29.31 times longer than the fastest. This could mean that an intermediate result is being cached.
> 1000000 loops, best of 3: 1.53 µs per loop

%timeit state.getPositions(asNumpy=True)

> The slowest run took 74189.11 times longer than the fastest. This could mean that an intermediate result is being cached.
> 1000000 loops, best of 3: 1.54 µs per loop

p = state.getPositions(asNumpy=False)
import numpy
%timeit numpy.array(p._value)

> 10 loops, best of 3: 86.2 ms per loop
```

Filling the values directly in C++ into a n*3 numpy float64 array should bring the timing of this step down at least 100-fold. Would it be possible to add this as an option?

**Comment by peastman** [comment]
The way State is implement in Python isn't as efficient as it could be.  Instead of having SWIG wrap the C++ class (which would have its own issues),  we completely implement it in Python, then have C++ code to generate the Python object from the C++ object.  But we don't know which representation the user will request (Vec3 or numpy), and it would be wasteful to create both in advance.  So we create only one, and then if they request the other, it has to be converted.

A more efficient implementation would keep around the C++ State object.  Then it wouldn't convert the arrays until the first time you requested them, and we could have C++ code generate the requested representation.  I'm not sure how hard it would be to make that work, but I could look into it.

**Comment by tristanic** [comment]
That would be great! It's not particularly urgent for me right now (I have a great many other things to get done before worrying about that level of performance tweaking), but a potential 30-40% improvement in simulation speed would certainly be nice.

**Comment by axsk** [comment]
It's gread that we have this feature for getPositions. Is a similar thing possible (or already included) for setPositions?

**Comment by peastman** [comment]
`setPositions()` should already be pretty efficient, especially if you pass them in the form of a numpy array.

**Comment by axsk** [comment]
You are right, its really fast. I didn't assume it would take a numpy array. Thank you!
