### ISSUE TITLE
Running OpenMM OpenCL on Mesa and radeonsi

### ISSUE THREAD

**Issue by vedranmiletic** [pandegroup/openmm#1749]
Hello,

I am trying to get Mesa/Gallium/radeonsi/Clover/LLVM OpenCL stack to run OpenMM ([Freedesktop bug](https://bugs.freedesktop.org/show_bug.cgi?id=99764)) and Mesa already passes a couple of OpenMM OpenCL tests (IIRC a half of them or so, but would have to re-run to get the exact number). Regarding failing tests, I am pretty sure bugs are on Mesa's side, but I do need help from OpenMM side to understand where exactly is Mesa behaving in an unexpected way.

In case of TestOpenCLAndersenThermostat, the code will hang and eventually segfault in testTemperature() during OpenCLContext::~OpenCLContext() on `delete thread` line. However, if I set numSteps in testTemperature() to e.g. 500 (instead of default 5000), the test runs fine. I would guess Mesa is doing something OpenMM does not expect and would appreciate any hints what could that be.

I tried to look into GDB's backtrace, but it's very verbose and hard to read.

**Comment by peastman** [comment]
When you get a crash in the context destructor, that usually means something has corrupted memory.  So the real problem is probably at some earlier point, but it's hard to guess where.  If the corruption is happening on the CPU side, a tool like valgrind might help in tracking it down.  If it's happening on the GPU side that's harder, but maybe we can identify a particular kernel it's happening in.  If you have a list of tests that pass and ones that fail (including the error messages), that might provide some clues.

**Comment by vedranmiletic** [comment]
I will try to get those. Does the fact that reducing numSteps from 5000 to 500 provide any hints?

**Comment by peastman** [comment]
Just that it's consistent with memory corruption.  If you don't run it as long, it's likely to have messed things up less.

**Comment by vedranmiletic** [comment]
@peastman does https://bugs.freedesktop.org/show_bug.cgi?id=99764#c2 help?

**Comment by peastman** [comment]
That's not as bad as I thought it might be.  You can get the detailed error messages either by running the tests individually, or by running them all like this:

```
ctest --output-on-failure -R TestOpenCL.*
```

I suspect the GPU and/or OpenCL doesn't support 64 bit atomic operations?  That's probably responsible for a lot of the failures, since certain features require it.  For example,

```
$ ./TestOpenCLCustomManyParticleForce 
exception: CustomManyParticleForce requires a device that supports 64 bit atomic operations
```

So for the moment let's focus on the segfaults.  It looks like all of them are tests of integrators, so they involve running a simulation for some reasonably large number of steps.  Perhaps start by running TestOpenCLAndersenThermostat in valgrind?  Most likely that won't tell us anything useful, but it's an easy first thing to try.

**Comment by vedranmiletic** [comment]
First off, thanks for taking time to discuss this.

Regarding 64-bit atomics, this should be pretty straightforward (Clang and LLVM have the required parts in place) and I will get to it eventually, bug report is here: https://bugs.freedesktop.org/show_bug.cgi?id=99950

Regarding Valgrind, I have just ran it: https://gist.github.com/vedranmiletic/ada4583f26e115dc7e2d780bd7994026 (ignore error callback being called, that's wrongly handled in Clover https://lists.freedesktop.org/archives/mesa-dev/2017-February/145648.html but does not affect program runtime)

**Comment by peastman** [comment]
Valgrind is reporting lots of invalid reads, all of them inside `clReleaseMemObject()`, which is being called from the `OpenCLContext` destructor.  It's hard to know whether that's a real error, or an artifact of the analysis, or a side effect of an earlier error.  But it might be real, so it makes sense to start investigating there.  Can you track down what the invalid memory location is, and where it's getting that location from?

**Comment by vedranmiletic** [comment]
Nailed both that one and and issue with event handling. Patches will be coming to Mesa soon (first one has been already posted, and then another dev proposed a better solution [1]). There are still some tests failing (single/double), will look into those right away.

I will report back when I get all tests passing, and thank you for your help so far.

[1] https://lists.freedesktop.org/archives/mesa-dev/2017-March/147101.html

**Comment by peastman** [comment]
Glad to hear it.  It will be nice to have a fully open source OpenCL implementation.

**Comment by peastman** [comment]
Closing this, since the issue has been resolved.
