### ISSUE TITLE
ACE term not calculated with OBC2 and CHARMM force field

### ISSUE THREAD

**Issue by SimoneCnt** [pandegroup/openmm#1803]
I've been running some MD using the CHARMM force field and the OBC2 implicit solvent model. When the system is created by CharmmPsfFile.createSystem, the ACE term of the implicit solvent model is not computed. You can check this around line 1200 of file 
```wrappers/python/simtk/openmm/app/charmmpsffile.py```
which calls the ```GBSAOBC2Force``` function using ```None``` as third parameter instead of ```'ACE'```. 

I consider this a bug and I would suggest to set the default to use the ACE term. 
Also, I would like to have the possibility to activate/inactivate the ACE term with a switch in the createSystem function. It would be even nicer to have the surface tension term freely modifiable, not hard coded.

**Comment by peastman** [comment]
@swails was this an intentional behavior?

**Comment by swails** [comment]
I wrote that ages ago, but I believe I know the rationale behind it.  The AMBER file parsers did not make the nonpolar part specifiable -- it hardcoded `'ACE'`.  So to be consistent, I didn't expose that parameter either.

Since Amber doesn't have `'ACE'` as a nonpolar model (it only supports LCPO), the validation had to be done with no nonpolar contribution.

As to why I didn't change the default to use ACE instead of none at all, I don't remember.  Maybe I meant to but forgot, or maybe I thought `None` was a better default.  Those GB models are not well-studied with the CHARMM force field in the first place, and CHARMM FF developers will most likely tell you it's a brand-new and as-yet-untested force field regardless of whether or not you included a nonpolar contribution.  As such, I can't say I place much importance on whether or not this model is applied to GB simulations with the CHARMM force field (after all, I believe the parameters CHARMM uses with their own GB models actually differ from those parameters used for explicit solvent simulations -- this is not the case for Amber).

That said, check out #1805 and see if that scratches the itch here.

**Comment by SimoneCnt** [comment]
Seems fine to me.
Since the default  behavior with Amber and CHARMM is different, please make it clear in the documentation.
