### ISSUE TITLE
Maximum cutoff allowed for triclinic box

### ISSUE THREAD

**Issue by andrrizzi** [pandegroup/openmm#1831]
If I read the code correctly, currently OpenMM [forbids to create a context](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/NonbondedForceImpl.cpp#L97-L98) if any `v_ii` is less than the cutoff (`v_ii` here is the i-th component of the i-th box vector).

Shouldn't that condition check the norm of the box vectors rather than the single components? Or are there cases in which this condition fails?

**Comment by peastman** [comment]
The check is correct.  The particular restrictions OpenMM places on box vectors (see http://docs.openmm.org/7.1.0/userguide/theory.html#periodic-boundary-conditions) have the result that the box can always be interpreted as a rectangular, axis aligned box of size (v11, v22, v33).  The other elements of the vectors cause the periodic copies of the box to be staggered relative to each other, but don't affect the box size.  Also see http://onlinelibrary.wiley.com/doi/10.1002/(SICI)1096-987X(19971130)18:15%3C1930::AID-JCC8%3E3.0.CO;2-P/abstract if you want lots more information about this.

**Comment by andrrizzi** [comment]
Thanks for the reference, @peastman . I think I'm still a little confused. Does that mean that OpenMM changes the given box vectors internally through the transformation in Eq (7) to treat it as a rectangular box?

To give some context, I'm trying to determine automatically the maximum cutoff that I can apply to a system in my code. As a practical example, I'm starting with box vectors
```
[Quantity(value=(3.54607, 0.0, 0.0), unit=nanometer), Quantity(value=(0.0, 3.54607, 0.0), unit=nanometer), Quantity(value=(-1.7730299999999999, -1.7730299999999999, 2.50745), unit=nanometer)]
```
which should be reduced and satisfy the restrictions you linked. I'm computing the maximum cutoff using Eq (13) in the paper
```
max R_cutoff = 1/2 min(|K'|, |L'|, |M'|)
```
where `|K'|, |L'|, |M'|` are the norms of the reduced triclinic box vectors, which seem to be different than the vectors of the equivalent rectangle that are indicated by `U, V, W`. Here's the skeleton of my Python implementation
```python
box_vectors = system.getDefaultPeriodicBoxVectors()
min_box_dimension = min([np.linalg.norm(vector) for vector in box_vectors])
cutoff_distance = min_box_dimension * 0.99 / 2.0
for force in system.getForces():
    try:
        force.setCutoffDistance(cutoff_distance)
    except AttributeError:
        pass
```
but OpenMM raises
```
Exception: NonbondedForce: The cutoff distance cannot be greater than half the periodic box size.
```
However, I don't understand why there should be double-counting of particles under the maximum cutoff I'm allowing.

**Comment by andrrizzi** [comment]
Ah! I understand now that the transformation in Eq (7) under those condition is equivalent to just consider only the `v_ii` components, but according to Eq (13) the current condition checking the maximum allowed cutoff to should be too conservative. Unless I'm still missing something.

**Comment by peastman** [comment]
The reason for imposing that restriction is a bit different.  It's necessary to let us compute interactions efficiently.  When computing an interaction, we need to find the nearest periodic copy (if any is within the cutoff distance).  To really do that correctly, you need to consider all 27 nearest copies and check each one to determine which is closest.  That's really expensive.  So instead we do a much cheaper computation.  Let `a`, `b`, and `c` be the box vectors, and `delta` be the displacement between two particles (before applying periodic boundary conditions).  Now we want to modify it to be the distance between the two nearest copies of those particles.  We do it as follows:

```
delta -= round(delta.z/c.z)*c
delta -= round(delta.y/b.y)*b
delta -= round(delta.x/a.x)*a
```

That is guaranteed to give the correct result if 1) the box vectors satisfy all the requirements described in the manual, and 2) the nearest periodic distance is <= `min(a.x, b.y, c.z)/2`.  If it's further away than that, this calculation can give the wrong result.  So we restrict the cutoff distance to that.  That way, we know that *either* the calculation gave the right result, *or* the distance is beyond the cutoff, so we don't care about it.

**Comment by andrrizzi** [comment]
Thanks for the explanation, @peastman . However, why would a bigger cutoff affect 2) (i.e. the nearest periodic distance)? Shouldn't it only affect neighbor lists in that it would include more particles in the energy calculation? Thanks again for the patience.

**Comment by peastman** [comment]
I'm not sure what you mean.  The point is that, if the nearest periodic copy is further away than `min(a.x, b.y, c.z)`, the calculation shown above is not guaranteed to give the actual nearest periodic copy.  It's possible it will produce the displacement to the wrong periodic copy, one that isn't actually the nearest one.  That's why we set it as a limit on the cutoff distance.  If `delta` comes out closer than the cutoff, we know it's correct.  And if it's further away than the cutoff, we know the actual nearest copy is also further away than the cutoff, although we don't know for sure which copy it is.

**Comment by andrrizzi** [comment]
Oh, sorry, you're right. What I said before was nonsense. Would it be maybe possible to extend it to a more general scheme? For example, I've only verified this numerically, but intuitively something like this should work under the same conditions
```python
delta -= round(delta.dot(a)/|a|**2)*a
delta -= round(delta.dot(a)/|a|**2)*a
delta -= round(delta.y/b.y)*b
delta -= round(delta.x/a.x)*a
```

**Comment by andrrizzi** [comment]
Sorry, I sent the comment too soon. Edited now.

**Comment by peastman** [comment]
Do you have a proof that gives the right answer?  It isn't obvious to me that it does.  The key is that only `c` has a nonzero z component, and only `b` and `c` have nonzero y components.  So the first thing we do is subtract a multiple of `c` to make `|delta.z|<|c.z|/2`.  Once we do that, we know z isn't going to change.  (The other vectors have z components of 0.)  And we also know that any other multiple of `c` would lead to `|delta.z|>|c.z|/2`.  There is only one possible multiple of `c` we could subtract that has any chance of being within the cutoff.  Then we do the same thing with `b` (knowing that nothing else will affect y after that), and finally `a`.

But if we allow the cutoff to be greater than `|c.z|/2`, there's more than one multiple of `c` that could potentially lead to a result within the cutoff, so we need to check them all.

Also, the added cost is three dot products, so that's 9 multiplies and 6 adds.  (Though if we take advantage of the known 0 elements, it's really only 6 multiplies and 3 adds.)

**Comment by andrrizzi** [comment]
> Do you have a proof that gives the right answer?

Nope, sorry, I just derived geometrically, and verified it numerically, but I think I can work on a formal proof or find an existing reference. I'll have time to back to this next week.

> Though if we take advantage of the known 0 elements

Yeah, that's what I was thinking. You're right that it also involves 3 more additions on top of the 3 more multiplications (I'm assuming the vector `a/|a|**2` is precomputed for all particles in advance so you don't have the division step of the current algorithm).

**Comment by jchodera** [comment]
If this is indeed correct (@andrrizzi's numerical tests suggest it is), it's possible that this part of the kernel could be compiled in only if the cutoff satisfies `min(a.x, b.y, c.z) < r_cutoff < 1/2 min(|K'|, |L'|, |M'|)`, so it would only slow down large cutoffs. We only use large cutoffs for reprocessing subsampled trajectories as a heterogeneous long-range dispersion correction, so that would totally be fine for us.

**Comment by andrrizzi** [comment]
Ah, sorry, while working out the proof I realized this works only for a different set of conditions, but it's not general either, so there would be no point in implementing it. Thanks for the explanation, @peastman .
