### ISSUE TITLE
Additional virtual site types

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#1855]
As part of the ongoing evolution of the [SMIRNOFF SMARTS-based forcefield specification scheme](https://github.com/open-forcefield-group/smirnoff/blob/master/The-SMIRNOFF-force-field-format.md), there is a growing desire to support off-atom charge sites to represent lone pairs or sigma holes. While OpenMM already has a variety of supported virtual site geometries, it appears we are missing a few key geometries that would be necessary to support lone pairs and sigma holes.

The current proposal adds XML syntax that looks like this:
```XML
<!-- sigma hole for halogens: "distance" denotes distance along the 2->1 bond vector -->
<VirtualSite type="BondCharge" smirks="[Cl:1]-[C:2]" distance="0.30"/>
<!-- monovalent lone pairs: carbonyl -->
<!-- inPlaneAngle is angle charge site (X) makes with 1 and 2, i.e. X-1-2 -->
<!-- outOfPlaneAngle is angle charge site (X) makes out of the plane of 2-1-3 measured from 1 -->
<VirtualSite type="MonovalentLonePair" smirks="[O:1]=[C:2]-[*:3]" distance="0.30" outOfPlaneAngle="0" inPlaneAngle="120"/>
<!-- divalent lone pair: pyrimidine -->
<!-- single charge site lies in plane, bisecting the angle left by taking 360 degrees minus angle(2,1,3) -->
<VirtualSite type="DivalentLonePair" smirks="[*:2]~[#7X2:1]~[*:3]" distance="0.30"/>
<!-- trivalent nitrogen lone pair -->
<!-- charge sites lie above and below the nitrogen at specified distances from the nitrogen, along the vector perpendicular to the plane of (2,3,4) that passes through the nitrogen. If the nitrogen is co-planar with the connected atom, charge sites are simply above and below the plane-->
<!-- Positive and negative values refer to above or below the nitrogen as measured relative to the plane of (2,3,4), i.e. below the nitrogen means nearer the 2,3,4 plane unless they are co-planar -->
<VirtualSite type="TrivalentLonePair" smirks="[*:2]~[#7X3:1](~[*:4])~[*:3]" distance="0.30"/>
<VirtualSite type="TrivalentLonePair" smirks="[*:2]~[#7X3:1](~[*:4])~[*:3]" distance="-0.30"/>
```
As I see it, this would require a few additional types of `VirtualSite` subclasses in addition to [those already implemented](http://docs.openmm.org/7.1.0/userguide/theory.html#virtual-sites). For example, for "BondCharge" above, `TwoParticleAverageSite` won't work because we need to specify the displacement distance from atom 1 along the bond vector, rather than simply specify the fractional bond distance---this is due to the quantum chemical effects driving where this charge center is best placed. The other `type`s above have similar differences from existing virtual site types.

Does it sound practical for these additional virtual site types to be defined?

We're currently discussing this in https://github.com/open-forcefield-group/openforcefield/issues/41 (original thread [here](https://github.com/open-forcefield-group/smarty/issues/132)) if more detail is needed.

**Comment by davidlmobley** [comment]
I just want to chime in that (a) we really want this (it will enable a lot of exciting science), and (b) I'm monitoring this issue to help address any questions which come up.

**Comment by peastman** [comment]
Are you sure these can't be done with LocalCoordinatesSite?  They look to me as if they could.

**Comment by jchodera** [comment]
The `BondCharge` type certainly can't---it only has two atoms to define its reference frame.

I spent some time thinking about how exactly the `LonePair` types could be encoded as a `LocalCoordinatesSite`, and while I don't doubt that the virtual sites can be placed at an initial geometry that complies with the specification above, I don't think it would be possible to maintain the in-plane angle, out-of-plane angle, and distance from atom 1 to the specified values once the three atoms started moving. It might be close, but as I understand it from @cbayly13, it would then have the wrong physics. It's possible I haven't come up with the right clever solution to defining the coordinate system to ensure the angles and distance are maintained throughout the simulation, however.

**Comment by peastman** [comment]
> The BondCharge type certainly can't---it only has two atoms to define its reference frame.

That one trivially can.  Use the two atoms to define the x axis, and place the virtual site at the desired position along that axis.  You'll need to specify a third atom for the y axis, but it doesn't matter what atom you specify or where it is.  The result will be unaffected.

The trivalent one also looks trivial.  Specify the nitrogen, plus two other atoms in the plane to set the x and y axes.  Then put the virtual sites at the desired +z and -z positions.

The divalent one is a little more complicated, but if I understand it correctly you can do that one too.  Compute xdir to bisect 2-1 and 3-1, and ydir to be another direction within that plane.  Then the virtual site should have a fixed position in those coordinates.

I'm the least clear on the monovalent one.  A diagram might help.

**Comment by davidlmobley** [comment]
I'll chime in. The major caveat is that I haven't yet dug into virtual site handling in OpenMM so I'm taking your word for what can/can't be done presently:

>> The BondCharge type certainly can't---it only has two atoms to define its reference frame.

> That one trivially can. Use the two atoms to define the x axis, and place the virtual site at the desired position along that axis. You'll need to specify a third atom for the y axis, but it doesn't matter what atom you specify or where it is. The result will be unaffected.

Ah, that sounds like it should work, as long as `LocalCoordinatesSite` allows that. Great.

> The trivalent one also looks trivial. Specify the nitrogen, plus two other atoms in the plane to set the x and y axes. Then put the virtual sites at the desired +z and -z positions.

The problem here (unless it's not a problem) is that the nitrogen might or might not be in the same plane as the three connected atoms. Your statement says "two other atoms in the plane", but the trivalent nitrogen might or might not be co-planar with the other atoms. Specifically, it can have a tetrahedral geometry (picking a frame of reference, think of all three connected atoms being below the nitrogen atom and one of the charge sites being above the nitrogen atom), or it can have a planar geometry. You need the coordinates of all three connected atoms AND the nitrogen to determine where the charges should be. Specifically, you take the plane of atoms (2, 3, 4), which might or might be co-planar with the nitrogen, then you find a vector perpendicular to that plane that passes through the nitrogen and place the charge sites along that vector. So you need all four atoms. Can this be done at present?

Image/cartoon: 
![20170705_120810](https://user-images.githubusercontent.com/7132257/27880948-ac518d5e-617b-11e7-8b56-52582085a238.jpg)


> The divalent one is a little more complicated, but if I understand it correctly you can do that one too. Compute xdir to bisect 2-1 and 3-1, and ydir to be another direction within that plane. Then the virtual site should have a fixed position in those coordinates.

Yes, that actually sounds right to me. If the x direction is the bisector of 2-1 and 3-1, then where we want the charge site is in the -x direction a specific distance. So if we can do that with `LocalCoordinateSite` then we are set.

> I'm the least clear on the monovalent one. A diagram might help.

I have another meeting shortly, so I'm trying to attach a quick diagram before that but the quality may not be great.
![20170705_120810](https://user-images.githubusercontent.com/7132257/27880924-97e39696-617b-11e7-9048-91c987cb6a4c.jpg)
 But to say in words slightly better as well:

- We have a carbon with two connected atoms that we're worried about, an oxygen (O) and another atom, we'll call it B. 
- Put the carbon, C, at the origin, and define a coordinate system where the Z axis runs perpendicular to the plane of C, B, and O and the X and Y axes lie in the plane. Let the X axis run through B. 
- Define a charge site q at some distance d from the oxygen atom, with an in-plane-angle `B-C-q` of `inPlaneAngle` (theta2 in my diagram) where the charge site may lie out of the X-Y plane and this is the angle measured IN the X-Y plane
- The charge site also has an `outOfPlaneAngle` (theta1 in my diagram) that measure its inclination out of the plane. For carbonyls this will probably be zero, but it could be nonzero for other sites

Does that help?

**Comment by peastman** [comment]
> You need the coordinates of all three connected atoms AND the nitrogen

Ok, that requires something different.  LocalCoordinatesSite is positioned based on three atoms.  If you need to base it on four atoms, that will require a different class.

The monovalent case looks easy to handle.  Given the coordinate system you defined, isn't the virtual site just at a fixed location?  As long as theta1 and theta2 are constants.

**Comment by davidlmobley** [comment]
>> You need the coordinates of all three connected atoms AND the nitrogen

> Ok, that requires something different. LocalCoordinatesSite is positioned based on three atoms. If you need to base it on four atoms, that will require a different class.

Yes. We need the three non-nitrogens to define the plane, so yes, it has to be four atoms. What else would you need from us to know what needs implementing here? 

> The monovalent case looks easy to handle. Given the coordinate system you defined, isn't the virtual site just at a fixed location? As long as theta1 and theta2 are constants.

Yes, theta1 and theta2 would be constants. It's fixed given the coordinates of the other atoms, yes. Sounds like this can probably be done with LocalCoordinateSite then?

**Comment by peastman** [comment]
We need to decide what sort of virtual site to add to handle the four particle case.  I usually prefer general purpose features over specialized ones, so can we create something that will support this particular case, but also lots of other potential cases?

One possibility is just to generalize LocalCoordinatesSite to support more than three particles.  It would still compute the virtual site position in the same way, but the `origin`, `xdir`, and `ydir` vectors could be weighted averages of the positions of an arbitrary number of particles.  Would that work for you?

**Comment by davidlmobley** [comment]
@peastman - sorry for the delay, I was on the road yesterday. I took a moment to have a look at `LocalCoordinatesSite`, which is actually pretty awesome and flexible. I regret that I hadn't looked in detail at it before; as you point out, it does a lot of what we need! So regarding the four particle site:

> We need to decide what sort of virtual site to add to handle the four particle case. I usually prefer general purpose features over specialized ones, so can we create something that will support this particular case, but also lots of other potential cases?
>
> One possibility is just to generalize LocalCoordinatesSite to support more than three particles. It would still compute the virtual site position in the same way, but the origin, xdir, and ydir vectors could be weighted averages of the positions of an arbitrary number of particles. Would that work for you?

That sounds like it would be an excellent generalization. So it would basically work as present, except that instead of three-component vectors for origin, x, and y directions you'd have N component vectors where N is the number of particles... 

Let me think through (for my own sake) how this applies to the four-particle case (the trivalent nitrogen) I was worried about, since it's been a while since I was doing vector math on any regular basis... 

In the trivalent planar case, the existing `LocalCoordinatesSite` can handle it, as I think you said originally. I think then we make the nitrogen be at the origin, pick x and y to be vectors to two of the other particles (2 and 3 for example), and then Z ends up being perpendicular to the plane involving (N, 2, and 3) and y gets recomputed to be perpendicular to X and Z and will still lie in the plane of (N, 2, 3). 

The trivalent case is more tricky. Here's the first way I thought of doing it. **(Note: I've mostly ruled this one out but it's here for my notes.)** With the proposed extended version of `LocalCoordinatesSite`, my first thought was this: I'd make the origin be the (equally weighted) average of the coordinates of particles 2, 3, and 4 (the non-nitrogen particles) so it would lie in the plane of 2, 3, and 4. And then I'd pick the x axis to be the vector to one of the particles, e.g. particle 2. Then I'd pick the y axis to be the vector to another of the particles, e.g. particle 3. Z would then be computed as xdir x ydir, so it would be perpendicular to the plane, and ydir would be recomputed to be orthogonal to x and z but would (I believe) still lie in the plane. Then the virtual site would be placed along the Z axis some distance from the plane. I think this should work, though since I've made no mention of the position of the nitrogen atom, it relies on the fact that the three atoms are in fact co-planar and the nitrogen is perpendicular to the plane; presumably this won't always be the case because of motions in bond length/angle. Also, I can't measure the distance FROM the nitrogen atom when placing the charge site, which makes it harder to get the functionality I want.

Hmm. Another strategy would be to make the origin be the coordinates of N, the X direction be the direction to the (equally weighted) average of the coordinates of 2, 3, and 4 (so that it's the vector towards the plane) and then the Y direction could be set arbitrarily (such as the vector to particle 2). The Z direction would then be perpendicular to this, and Y would get recomputed to be orthogonal to X and Y. But we wouldn't actually use Y and Z; we'd just place the charge at the target distance along X. **That seems like it would do what we need, do you agree?** 

**So, the upshot is that I think your proposed extension of `LocalCoordinatesSite` would be great and will do what we need**, unless I'm missing something. @jchodera ?

**Comment by peastman** [comment]
Here's how I would do it: set xdir to 3-2 and ydir to 4-2.  That guarantees they'll both be parallel to the plane of atoms 2, 3, and 4, which means z will be perpendicular to that plane.  Then set the origin to the position of atom 1 (the N), and put the virtual sites at the desired +z and -z locations.

**Comment by davidlmobley** [comment]
Ah, yes, that sounds even better. 

What do we need to do to help get this implemented?

Thanks!

**Comment by peastman** [comment]
I'll take care of it.  I just needed confirmation that design would meet your needs.  @jchodera does that sound good to you too?

**Comment by jchodera** [comment]
> Here's how I would do it: set xdir to 3-2 and ydir to 4-2. That guarantees they'll both be parallel to the plane of atoms 2, 3, and 4, which means z will be perpendicular to that plane. Then set the origin to the position of atom 1 (the N), and put the virtual sites at the desired +z and -z locations.

This would indeed handle the `TrivalentLonePair` case!

> The divalent one is a little more complicated, but if I understand it correctly you can do that one too. Compute xdir to bisect 2-1 and 3-1, and ydir to be another direction within that plane. Then the virtual site should have a fixed position in those coordinates.

How would we define `xdir` to bisect the 2-1-3 angle using a linear combination of atom positions whose coefficients are constants while atom position (1,2,3) are not fixed in space? I'm not seeing how this is possible.

I think the `MonovalentLonePair` diagrams are flawed and that we don't yet have this correctly conceived. How do we ensure that the precise distance to the oxygen (atom 1) is constant even if the other atoms move?

**Comment by peastman** [comment]
Let `p1`, `p2`, and `p3` be the positions of the three atoms.  You can approximately bisect the angle by setting `xdir = 0.5*p2 + 0.5*p3 - p1`.  That's the direction pointing from `p1` to the midpoint between `p2` and `p3`.  If you want to bisect the angle more precisely, you need to adjust for any difference in the bond lengths.  If `L2` is the length of the 1-2 bond and `L3` is the length of the 1-3 bond, set `xdir = (L3/(L2+L3))*p2 + (L2/(L2+L3))*p3 - p1`.  I believe that should exactly bisect it.

**Comment by jchodera** [comment]
I believe that expression is correct, @peastman, but the coefficients depend on bond lengths that are not constant, and OpenMM's `LocalCoordinatesSite` is restricted to specifying constant coefficients. 

Is there a general way to extend `LocalCoordinateSite` or add a new virtual site type that would can permit *exact* implementations of the proposed schemes even when the atoms are mobile?

**Comment by peastman** [comment]
If you don't constrain the bond lengths it won't exactly bisect the angle, but it will be very close.  Typical bond length fluctuations are on the order of a few percent at most.  So `xdir` will generally be within a degree or two of the true bisector.

**Comment by jchodera** [comment]
I think this becomes a question of "which scheme gives the proper physics?" and "how much coupling between bond force constants and lone pairs are we willing to accept?"

@davidlmobley: Can you check with Christopher and see if this approximate definition is sufficient?

**Comment by peastman** [comment]
> I think the MonovalentLonePair diagrams are flawed and that we don't yet have this correctly conceived.

I still need more details on this.  If the diagram @davidlmobley posted is incorrect, can you provide a correct one?

**Comment by jchodera** [comment]
As I understand it, this is the geometry intended for `TrivalentLonePair`, though I think the definition we were using for `inPlaneAngle` was incorrect since it should not be `X-1-2` but `P-1-2` where point `P` is the projection of `X` into the `1-2-3` plane:
![fullsizerender](https://user-images.githubusercontent.com/3656088/28047415-ff7af298-65a6-11e7-881a-f30cabfb21e2.jpg)
@davidlmobley : Can you review and confirm this is correct?

**Comment by davidlmobley** [comment]
I am following up with @cbayly13 on the `DivalentLonePair` case, though I believe he's out of town this week so he may not be able to get back to us for a bit. I'm investigating the others now and hope to respond shortly.

**Comment by davidlmobley** [comment]
@jchodera - yes, you are correct, it seems my diagram/thinking was flawed on the monovalent lone pair case; it looks like I would have also had the distance measured relative to the carbon atom, which is incorrect. Your diagram seems to be correct. There is one correction, however, to your comment:

> As I understand it, this is the geometry intended for `TrivalentLonePair`...

should read
> As I understand it, this is the geometry intended for `MonovalentLonePair`...

It seems to me that this can fit within the same `LocalCoordinateSite` framework as is. Thinking through how it might work:
- Set origin at position of 1
- Set X to be the 1-2 vector
- Set Y to be the 2-3 vector
- Z will lie out of the plane
- Compute new Y perpendicular to X and Z
- Compute X, Y, Z coordinates of target site using theta1 and theta2 and trig (e.g. the y component is sin(180-theta1), unless I'm missing something -- which is possible since it's been a long travel day).

**Comment by jchodera** [comment]
> It seems to me that this can fit within the same LocalCoordinateSite framework as is.

I believe that is correct! I just wanted to make sure we agreed on the definition of all the positions.

**Comment by davidlmobley** [comment]
> I am following up with @cbayly13 on the `DivalentLonePair` case, though I believe he's out of town this week so he may not be able to get back to us for a bit. I'm investigating the others now and hope to respond shortly.

I followed up with Chris on this. His perspective is that he thinks the current proposed approach (where the site position may fluctuate a degree or two based on local bond geometry, as in https://github.com/pandegroup/openmm/issues/1855#issuecomment-313891654 ) is fine for an initial implementation, but that we will ultimately need to check how sensitive results are to this choice. That means that ultimately, we need an alternate virtual site to test this.

So, @peastman , I think we need to revisit this question:
> Is there a general way to extend `LocalCoordinateSite` or add a new virtual site type that would can permit exact implementations of the proposed schemes even when the atoms are mobile?

As you pointed out, in the case in hand we would (ultimately) want to:
> If L2 is the length of the 1-2 bond and L3 is the length of the 1-3 bond, set xdir = (L3/(L2+L3))*p2 + (L2/(L2+L3))*p3 - p1

Thanks!

**Comment by peastman** [comment]
We can always add new virtual site classes in the future.  I think it would be a new class, not an extension of LocalCoordinatesSite.  It would require a fairly different sort of calculation, one based on angles rather than linear combinations of atom positions.

So to summarize: the only addition we need right now is that I should extend LocalCoordinatesSite to work with arbitrary numbers of atoms, not just three.  With that change, you can implement all the site types described above, with the understanding that we might ultimately need to add another virtual site class if this implementation of the divalent case isn't accurate enough.

Shall I go ahead and start on that addition?

**Comment by jchodera** [comment]
I think we're all onboard with that plan, @peastman! Thanks!

**Comment by davidlmobley** [comment]
Yes, please!
