### ISSUE TITLE
Evaluating forces over whole trajectory

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1888]
Hi, this is more of a question than an issue. I was wondering what would be the best way to evaluate forces over a trajectory post-simulation.

This is the way I'd do it now. Was just wondering if I'm missing a more efficient method as it takes around 10s for 200 frames of 630 atoms.

```python
simulation = app.Simulation(psf.topology, system, integrator, platform, prop)
forces = []
for f in range(numFrames):
    simulation.context.setPositions(traj[f].positions)
    state = simulation.context.getState(getForces=True)
    forces.append(state.getForces())
```

**Comment by peastman** [comment]
That looks like the right way to do it.  What platform, hardware, and force field are you using?

**Comment by stefdoerr** [comment]
Ok if there is no faster alternative (i.e. loading the whole trajectory) I'll go with that.

Using CUDA, on a 1080(TI?) and CHARMM36 although I'll probably switch now to amber99 OBC to work faster without the waters.

**Comment by peastman** [comment]
Try switching to CPU.  For small systems, that will often be faster that CUDA.  A GPU is fast once it gets going, but there's a several microsecond overhead for every kernel you launch.  For a small system, the CPU can often do the whole calculation in less time than it takes to get the GPU kernel started.  And in this case it's especially bad because you have a lot of round trip communication for every force evaluation, so you're probably being limited by the speed of the PCIe bus.  The CPU platform doesn't have that issue.

**Comment by stefdoerr** [comment]
Ah right, I'll try that
