### ISSUE TITLE
Identifying NaN's in Systems heavy with Custom*Forces

### ISSUE THREAD

**Issue by Lnaden** [pandegroup/openmm#1904]
We are having problems figuring out exactly why some of our `System`s in YANK fail and would like assistance into why. We rely heavily on the `Custom*Force`s in OpenMM to do alchemical free energy calculations, but we are noticing some systems have a tendency to NaN along the way and cannot figure out why.

Attached is a simple test script along with all the files needed to load this system, although YANK uses replica exchange over many systems, we can reproduce this NaN reliably from a single system at a fixed set of parameters. 

Hardware and software configuration:
* This system was built from the AMBER force fields.
* GTX1080 GPU

Below is the list of things we have tried so far to isolate exactly what is causing this to NaN and the results from those attempts.

[alchemical-nan.zip](https://github.com/pandegroup/openmm/files/1317826/alchemical-nan.zip)

* Reducing the timestep by 1/2 (to 0.75 fs) removes the NaN, but such a low step is not feasible for production
* I originally thought it was the `CustomGBForce` since the example of [the GBSA OBC2 force as a `CustomGBForce`](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomGBForce.html#) does not exactly recreate the `GBSAOBCForce` at `r=0`, but that is a red herring as other test showed.
* Removing forces 1 at a time and propagating the system caused the system to NaN every time EXCEPT when the `NonbondedForce` was removed. In this system, that would be only receptor-receptor particle interactions. BUT
    * Only happens on CUDA
    * OpenCL always NaN's, no matter what force is stripped
* Platform precision has no affect on results
* Zeroing out our alchemical parameters, which should disable all the alchemical interactions, does not change the result
* Isolating each force into its own force group and seeing exactly which ones go to NaN is not helpful as this appears to be stochastic per run.
* From me viewing the trajectory, Hydrogen atoms on the receptor residues stretch too far, then in the next frame causes the residue to fly apart, then NaN shortly there after.
* Because this is an AMBER system, looked at receptor hydrogens which have a point charge, but not an `epsilon`, none of these hydrogens are the ones which fly away from the bullet above, and they are not close to the atoms which fly away. 

Any ideas as what to search for next would be appreciated, or if maybe if someone sees  something blatantly wrong with our setup let us know. I can probably get more examples of this from some other Systems as well, but it might take a bit.

Thanks in advance and let me know if you need other information
cc @jchodera @andrrizzi

**Comment by peastman** [comment]
Does it happen reasonably quickly?  If so, I'd try this.  After every time step, create a checkpoint.  You don't need to write it to disk, but keep the ~20 most recent checkpoints in memory.  Also check after every step to see if any forces have become nan.  As soon as one does, write out all your saved checkpoints to disk.  Now you have a detailed record of everything happening in the simulation for a short time before the error happened.  You can use that to examine individual forces in detail and see exactly what was happening.

This will hugely slow down your simulation, so it's only practical if the error happens quickly.  Otherwise, we'll have to consider other approaches.

**Comment by Lnaden** [comment]
It does happen quickly and I have done something very close to that as part of my testing. I have actually broken the energy down by `Force` step by step by putting them into their own force groups.

From what I see of that, the `NonbondedForce` takes a change of ~2500 kJ/mol, then the harmonic bond force grows each timestep after exponentially until the energy is order >> 10^9 then it NaN's. This is what I think I have seen when I was visualizing it where the hydrogens fly apart on a residue, but I can't figure out what causes the hydrogens to suddenly experience such a large force since they these hydrogens have both charge and epsilon.

I can post that plot if you think it helps.

**Comment by peastman** [comment]
From your description, it sounds like you don't think there's a bug, just a model that's unstable at that time step.  Is that correct?  So the question is to figure out what part of the model is causing the instability.

If it really is the harmonic bond force that's causing the problem, it should be easy to identify.  You can analytically calculate the expected period of each bond.  If any of them is shorter than about 10 time steps, it will be unstable.

**Comment by davidlmobley** [comment]
@Lnaden - do you have a ligand here which uses GAFF? And does it contain a neutral carboxylic acid or otherwise hydroxyls in close proximity to one another? 

There is a known issue with AMBER family forcefields where you can get crashes due to the polar hydrogens which have zero LJ radii (try doing a PMF for pairing of benzoic acid in water, for fun, if you like). The fix is to, er, NOT use nonzero LJ radii. I'm getting ready to try and roll this out in smirnoff99Frosst so I have never to deal with this again, validating it first, of course.

Update: I checked and I don't see any, but it's probably worth checking if you have any particles with sigma or epsilon of zero and if the problem goes away if you give them nonzero values.

**Comment by Lnaden** [comment]
I've finally been able to get back around to this. I've done more force breakdown and see what the problem is, and I don't think it actually has anything to do with the `Custom*Forces` I can see.

Non-water hydrogens, from either different residues or further away than the 1-4 exceptions, both bearing non-zero LJ radii, approach to < 0.12 nm from each other, `sigma` for these hydrogens is 0.265 nm. This causes a spike in the `NonbondedForce` due to electrostatic + repulsive vDW force contributions. At 1.5 fs, this causes the hydrogens to fly apart and crash the simulation. 

To @davidlmobley's point, this is on the protein and seems to mostly be caused by the LEU residue from the AMBER FF15SB. 

In the end, this does not look like its actually anything to do with the `Custom*Force` objects and I'll have to go back to the FF and see if I can better isolate what is happening here, unless someone has another idea as to why this might be happening. My concern is I don't know why this happens in implicit solvent more than explicit.

**Comment by Lnaden** [comment]
The LEU residue may only be the culprit in this case due to me using the same state as the starting point for debugging.

**Comment by jchodera** [comment]
Does adding a small LJ site to them avoid the crashes?

**Comment by Lnaden** [comment]
These are already non-zero LJ term hydrogens, so their sigma's are 0.265 nm and their epsilons are 0.066 kJ/mol

**Comment by Lnaden** [comment]
I'm going to close this for now and can re-open it if I find more information which would be more helpful.
