### ISSUE TITLE
Labeling of chains in mmCIF files: entity_id vs asym_id

### ISSUE THREAD

**Issue by JoaoRodrigues** [pandegroup/openmm#1907]
Hi there,

Reading/writing mmCIF files with multiple chains is a bit troublesome with OpenMM. I have a 16-chain PDB file that I converted to a mmCIF file using `PDBxFile.writeFile`. When I read this file I correctly get a topology with 16 chains, and the resulting `.cif` file labels the residues correctly. However, re-reading this mmCIF file produces a topology (and subsequent files) containing one chain only. 

I narrowed this down, I think, to a problem in the `PDBxFile` class, specifically in the mmCIF dictionary field it reads the chain information from to create `Chains` in the topology. While the PDB format chains are read to `asym_id`, the reader expects to have `entity_id` fields for chains. I am not super knowledgeable of the mmCIF format, but this should be somewhat consistent at least within OpenMM. I'd expect writing a file from one `Topology` to yield the same upon re-reading.

The fix could be as simple as using `asymIdCol` in the `Chain` creation if-clause, but I'm not sure how this would play with the format specifications... In Biopython we changed our mmCIF parser to use `auth.asym_id` since that matches the chains in PDB files, but again, my experience with these files is limited and this was based on a few observations. What is your opinion?

P.S. I can reproduce this easily, @peastman I can e-mail you a test file if necessary ..

**Comment by peastman** [comment]
Thanks!  I agree with your analysis.  And I see that http://mmcif.wwpdb.org/docs/pdb_to_pdbx_correspondences.html#ATOMP now recommends `auth_asym_id` as the equivalent for chain ID.  I think that may have changed since I originally wrote `PDBxFile`.

If you feel inclined to write a PR fixing this, that would be great.  If not, I'll try to fix it soon.  We should also add a test to `TestPdbxFile.py` that tests saving and reloading a structure with multiple chains.

**Comment by JoaoRodrigues** [comment]
Will do, perfect, thanks!

**Comment by peastman** [comment]
Fixed by #1908.
