### ISSUE TITLE
Using a barostat ignores enforcePeriodicBox

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#1910]
So the documentation of getState shows a flag for disabling the wrapping:
http://docs.openmm.org/6.3.0/api-c++/classOpenMM_1_1Context.html#a5c53803407b6c22454813f668c42a33e

I noticed that if I simulate my system with a barostat I get wrapped coordinates.
```C++
OpenMM::Force *barostat = new OpenMM::MonteCarloBarostat(sim->barostatpressure, sim->thermostattemp);
system->addForce(barostat);
[...]
OpenMM::State state = sim->context->getState( OpenMM::State::Positions | OpenMM::State::Energy, false );
```
If I don't add the barostat I get them unwrapped. Is this expected behaviour?

**Comment by swails** [comment]
Yes

**Comment by swails** [comment]
Several trajectory analysis programs (such as cpptraj) have an "unwrap" command that will undo the wrapping.

**Comment by stefdoerr** [comment]
Thing is I want to do it in C++ while running the sim. So I will have to look at the source code of cpptraj since there doesn't seem to be a C++ API.

Why does the barostat wrap though? (out of curiosity)

**Comment by swails** [comment]
@peastman will have to answer definitively, but the barostat requires coordinate scaling, which means it is a Force that modifies coordinates. Since there is not really any restriction on how those coordinates can be modified by a Force, I suspect that the Context has to basically discard the information on each atom that tracks what periodic cell the "original" image is in.

For reasons of numerical precision all coordinates are represented in their "wrapped" state and then unrolled prior to fetching from a Context if enforcePeriodicBox is set to False. If this unrolling information is invalidated or lost, then you're stuck with the "wrapped" representation. 

But like I said, @peastman would have the definitive answer. I'm just speculating.

**Comment by swails** [comment]
Why not just post process the trajectory after the simulation is over?

**Comment by stefdoerr** [comment]
Trying to work on acemd3 which uses openMM as backend.
We want it done automatically by acemd3 to keep compatibility with acemd2 and to not force the user to do it.
Also you might ctrl+c the simulation at some point and then you'd end up with a wrapped sim. Would be breaking the consistency.

If it's not too complicated I would prefer it done in openMM than to use cpptraj. The way you describe it it sounds more like an inconsistency of openMM than a necessity. Let's see if @peastman can chime in on it :)

**Comment by peastman** [comment]
Every time the barostat rescales the periodic box, it first wraps every molecule to that periodic box.  It does that because it's inherent to the whole concept of how the barostat works.  It scales *the volume of the periodic box*.  If some molecules were outside the box, you couldn't just rescale their coordinates.  If you did, they'd move the wrong amount.

This is distinct from the option on `getState()`.  That doesn't affect the positions stored internally, just the values returned in that call.  If the internal positions are already in a single periodic box (such as because a barostat put them there), it doesn't matter what setting you use for that option.

**Comment by swails** [comment]
But every box should be scaled identically, so why does it matter which image is scaled?

This explanation doesn't convince me why wrapping is necessary. Other programs don't require that.

**Comment by peastman** [comment]
It might be possible to change that, but that's how it works right now.  It would have to translate it to a single periodic box, then do the scaling, then translate it back again.

**Comment by swails** [comment]
Doesn't the gpu code already do that? Otherwise wouldn't you run into precision issues as particles diffuse to very large distances? (Especially if you are using single precision)

**Comment by giadefa** [comment]
@peastman could you point us to the code where the change should be done

**Comment by peastman** [comment]
The `ApplyMonteCarloBarostatKernel` class has a method called `scaleCoordinates()`:

https://github.com/pandegroup/openmm/blob/master/olla/include/openmm/kernels.h#L1266-L1278

Each platform has a subclass that provides an implementation of that method, which is where this happens.  For example, here's where it happens for the reference platform:

https://github.com/pandegroup/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceMonteCarloBarostat.cpp#L85-L90

The CUDA version is a bit more complicated, since there's both host and device code involved.  Here's the kernel code that moves each molecule into the first periodic box:

https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/kernels/monteCarloBarostat.cu#L27-L31

But in addition to that, it stores in host memory (*not* device memory) a set of integers for how many box widths each particle has been translated by.  To preserve the unwrapped positions, it would need to record how many box widths the kernel moved each particle by, send that information back to the host, and update the counts there (but only if the move is accepted).  Currently we don't try to do that.  We just set all the counts to 0:

https://github.com/pandegroup/openmm/blob/master/platforms/cuda/src/CudaKernels.cpp#L8195-L8196
