### ISSUE TITLE
GPU acceleration of energy evaluations from `Context`?

### ISSUE THREAD

**Issue by bmanubay** [pandegroup/openmm#1929]
Howdy folks,

Something I'm working on right now involves evaluating energies at new forcefield parameter states by changing those parameters in the `System` object, generating a new `context` and `state` and getting new energies from that (doing a lot of multistate reweighting with `pymbar` is why all the energy re-evaluations). Code snippet looks something like this:
```
def get_energy(system, positions, vecs):
    """
    Return the potential energy.
    Parameters
    ----------
    system : simtk.openmm.System
        The system to check
    positions : simtk.unit.Quantity of dimension (natoms,3) with units of length
        The positions to use
    vecs : simtk.unit.Quantity of dimension 3 with unit of length
        Box vectors to use
    Returns
    ---------
    energy
    """

    integrator = mm.VerletIntegrator(1.0 * femtoseconds)
    context = mm.Context(system, integrator)
    context.setPositions(positions)
    context.setPeriodicBoxVectors(*vecs)
    state = context.getState(getEnergy=True)
    energy = state.getPotentialEnergy()
    return energy
```
Is there some way I could accelerate this on a GPU? I figure there is, but I'm not sure where I'd feed in `platform` information here. Any incites are appreciated!

Best,

Bryce

**Comment by Lnaden** [comment]
If you define parameters in the System through a `Custom*Force`'s Global Parameters, you can just do `context.setParameter` function to update the global parameters in the existing context without having to re-instance a new context every time.

You would be able to apply positions/box vectors as needed, and that should be faster.

**Comment by Lnaden** [comment]
I also just realized you may have been asking a simpler question of "Can I do this computation on the GPU rather than the CPU." You can provide a `Platform` object to the `Context` args as the 3rd argument, assuming you pick a GPU platform of `CUDA` or `OpenCL`

**Comment by bmanubay** [comment]
Both of those are excellent answers, Levi! Thanks!

**Comment by peastman** [comment]
Since you didn't specify a platform, it automatically picked whichever it thought was fastest.  Assuming you have a GPU and the necessary libraries for CUDA or OpenCL installed, it was already using it.

That said, you might be better off *not* using the GPU.  Creating a new Context is expensive, so that may be taking more time than the energy evaluation.  Furthermore, creating a Context is much more expensive when using a GPU (on the order of 1 second for GPU compared to 0.1 seconds for CPU).  So specifying the CPU platform might end up being faster.

But it would be even better if you can avoid creating a new Context altogether.  Most Force classes have a method called `updateParametersInContext()` that lets you modify parameters on an existing Context.  Calling that method is much faster than creating a new Context.

**Comment by bmanubay** [comment]
Hmm, interesting fact. Thanks for the incite, Peter!! Much appreciated! I'll try that!

**Comment by peastman** [comment]
Closing this, since the question has been answered.
