### ISSUE TITLE
Context.getState randomly returns NaN forces on CPU

### ISSUE THREAD

**Issue by stefdoerr** [pandegroup/openmm#2012]
Hi, I was trying to use OpenMM 7.1.1 on CPU to evaluate forces, however it seems to randomly produce `NaN` forces after a few evaluations of the same state. 
I even tried it on different computers and it seems consistently broken. I cannot really make out the reason for this.

[alanine.zip](https://github.com/pandegroup/openmm/files/1793748/alanine.zip)

```python
from simtk.openmm import app
import simtk.openmm as mm
from simtk import unit
import numpy as np

pdb = app.PDBFile('a1e-solute.pdb')
forcefield = app.ForceField('amber99sbildn.xml', 'amber99_obc.xml')

system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.NoCutoff, ewaldErrorTolerance=0.0005)
integrator = mm.LangevinIntegrator(300*unit.kelvin, 1.0/unit.picoseconds, 5*unit.femtoseconds)

platform = mm.Platform.getPlatformByName('CPU')
properties = {}#{'CudaPrecision': 'mixed'} #, 'CudaDeviceIndex': '1'}
simulation_eval = app.Simulation(pdb.topology, system, integrator, platform, properties)
omm_context = simulation_eval.context

omm_context.setPositions(pdb.positions)
for i in range(1000):
    state = omm_context.getState(getEnergy=True, getForces=True)
    nrg = state.getPotentialEnergy().value_in_unit(unit.kilocalories_per_mole)
    force = state.getForces(asNumpy=True).value_in_unit(unit.kilocalories_per_mole / unit.angstrom)
    if np.any(np.isnan(force)):
        print('Found NaN', i)
```
Gives me:
```
Found NaN 19
Found NaN 86
Found NaN 179
...
```

**Comment by stefdoerr** [comment]
Tested just now on a clean conda install of OpenMM 7.2.0. Gives me NaNs as well

**Comment by peastman** [comment]
I just sent a PR (#2016) that fixes the problem.  It was uninitialized memory in the CPU implementation of GBSAOBCForce.  The code is vectorized, and if there weren't enough particles to fill the whole vector, it didn't bother to initialized the memory for the remaining elements.  Normally that's fine, because they don't affect any results.  Except that if any of those elements happen to be NaN, that ends up propagating to the whole vector.
