### ISSUE TITLE
details about virtual sites implementation?

### ISSUE THREAD

**Issue by jmichel80** [pandegroup/openmm#2045]
Hi, 

I'm wondering if someone can point me to the relevant bits of source code in OpenMM to understand how the non-bonded energies involving virtual sites are computed?

Specifically I would like to understand how the code knows which atoms to skip when evaluating pairwise non-bonded terms involving a virtual site (for instance the 'M' site in a TIP4PEw water and the O, H1, H2 atoms of the same water molecule). Is it necessary to define a bond between a virtual site and a regular atom to generate an exclusion list?

Thanks

Julien

**Comment by peastman** [comment]
I assume you're asking about what happens when you use a ForceField to create a System?  The code involved is different depending on how you create the System, but it usually works in roughly the same way.

[Here is the code](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L2342-L2344) to generated the nonbonded exceptions:

```python
bondIndices = _findBondsForExclusions(data, sys)
nonbonded = [f for f in sys.getForces() if isinstance(f, mm.NonbondedForce)][0]
nonbonded.createExceptionsFromBonds(bondIndices, self.coulomb14scale, self.lj14scale)
```

`NonbondedForce` has a method called `createExceptionsFromBonds()`.  You pass it a list of bonds (which doesn't need to match the set of bonded force terms in the molecule), and it adds the exceptions needed for 1-2, 1-3, and 1-4 interactions.  That list of bonds is generated by `_findBondsForExclusions()`, which you'll find [here](https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1297-L1324).  It contains code for handling virtual sites, along with other special cases.

**Comment by jmichel80** [comment]
Thanks that’s helpful. If i understand correctly the code virtual sites used to model lone pairs in OpenMM should be bonded to at least one atom, and inherit the exclusions list of the atoms they are bonded to.

I’m trying to work out how v-sites could be used with OpenMM to model e.g. sigma holes in halogen bonds and it wasn’t immediately clear to me if there is a clear and consistent definition of the way exclusions should be defined in that case. 

Specifically If you model a v-site between a C and Cl atom along a C-Cl bond should the v-site be bonded to C,Cl, or both?

**Comment by peastman** [comment]
> should the v-site be bonded to C,Cl, or both?

The word "bonded" can mean a lot of different things.  Are you referring to CONECT records in a PDB file?  `<Bond>` tags in a template definition in a force field?  Entries in the list passed to `createExceptionsFromBonds()`?  Force terms added to a `HarmonicBondForce`?  All these things are separate and serve different functions.

Generally speaking, vsites should not be bonded in any sense except for `createExceptionsFromBonds()`.  And that one depends on exactly what pattern of exclusions you want the vsite to follow.  Could you give more details on exactly what you want to achieve?  What interactions should be excluded for the vsite?  And how are you creating the System—with ForceField or by some other mechanism?

**Comment by djcole56** [comment]
Hi, just to chime in here on what we would like to achieve. Julien is following up a conversation we had about implementing an atoms-in-molecule based force field. These have a few more vsites than are generally found in force fields so, as you say, the exclusions need a bit more thought - see Fig 4 here:
https://pubs.acs.org/doi/abs/10.1021/acs.jctc.6b00027

The vsites generally fall into 2 categories - either lone pairs or sigma holes (the next generation FF will follow this more closely and will be simpler than the figure cited above).

For a lone pair, I think it makes sense to pretend there is a bond to the O,N or S atom so that it has the same exclusion rules as a normal atom (eg it would contribute to the torsional rotation barrier via 1,4 interactions).

For a sigma hole, again it makes sense to me to 'bond' it to the halogen and build the exclusion list in the same way. That seems the most convenient way to do it and I can't see any disadvantage. The nature of the AIM force field always associates a vsite to a specific heavy atom.

This is how we set it up in the BOSS monte carlo code, and the discussion above (and our own experience so far) suggests this is achievable in OpenMM using the exceptions lists.

Thanks
Danny

**Comment by jmichel80** [comment]
Following up to answer @peastman 's last question, we would be constructing exclusion lists for v-sites using our own C++ interface to OpenMM by passing data from Sire rather than by using openmm/app/forcefield.py  . 

We are been using v-sites to support TIP4P simulations for some years now but not in a general way. 
I don't expect programming difficulties to generalise support for v-sites in our code, but I think it is useful to start this thread to discuss and record the various ways exclusions could/should be defined for v-sites.

**Comment by peastman** [comment]
Ok, since you're building it yourself there are two options.  One is that you can explicitly set every exclusion you want by calling `addException()` on the NonbondedForce.  This gives you complete control to create any pattern of exceptions you want.  The other is to use `createExceptionsFromBonds()`.  That's really just a shortcut to handle the most common case (exclude 1-2 and 1-3 interactions, scale 1-4 interactions).

Assuming you use the latter approach, the list of bonds you pass to it determines how the vsites get handled.  Suppose you have a lone pair on an atom.  How should it interact with other atoms?  If the parent atom is separated by two bonds from some other atom (a 1-3 pair), should the lone pair be treated as a 1-3 interaction with that other atom (so they don't interact) or a 1-4 interaction (so they do interact, though possibly scaled down)?  For the former case, include a bond between the lone pair and every atom its parent is bonded to.  For the latter case, just include a single bond between the lone pair and the parent atom.

**Comment by jmichel80** [comment]
@peastman thanks ! very clear.
