### ISSUE TITLE
Poor Performance of Custom Reporter: getState & getPositions Bottleneck 

### ISSUE THREAD

**Issue by capslockwizard** [pandegroup/openmm#2052]
I am trying to perform steered MD and store the forces every step. So I've implemented my own custom reporter but the performance is really poor (GPU usage is barely 4%, without the reporter I get ~100%). 

In my custom reporter I call state.getPositions(asNumpy=True) in the report function. Profiling tells me that calling this function takes up ~50% of the wall time while the getState function takes up the remaining ~50% of the time. Basically, these 2 functions are taking up all the time and not the simulation itself.

Is there a more efficient way of doing this?

**Comment by peastman** [comment]
What version of OpenMM are you using?  The implementation of States in Python changed in 7.2 in a way that makes it much cheaper.  `getPositions(asNumpy=True)` should be very fast.

That said, querying forces every step is going to be slow no matter how you do it.  Each time you call `getState()` it needs to run the force computation and transfer all that data back across the PCIe bus.  While the data is being transferred, the GPU is otherwise sitting idle.  Then you do whatever you do with the force, while the GPU is still idle.  Finally you call `step()` again, but it takes time to get the first kernel set up and ready to execute, and since the GPU's work queue is empty, it has nothing else to be doing during that time.

Still, 4% GPU usage sounds way too low unless you're doing a whole lot of work in Python, like writing all the forces out to disk.  What method did you use to profile it?

**Comment by capslockwizard** [comment]
I ran the simulation and profiling on OpenMM 7.1.1 where it took ~100 s for 100 steps.

When I repeated the the same thing on OpenMM 7.2 it only took ~3 s. Now the simulation is using ~50% of the GPU as reported by nvidia-smi.

The forces are not written out to disk every step. Instead it is appended to a string in memory and is written out to disk at the end of the simulation. 

The only computation that I am doing is compute the dihedral angle from the atom coordinates and the force of the dihedral potential. See: [DihedralForceReporter.zip](https://github.com/pandegroup/openmm/files/1937123/DihedralForceReporter.zip). Can you recommend anything else that I can do to improve the performance?

Profiling was performed using Jupyter's "prun" magic command in Jupyter notebook.

**Comment by peastman** [comment]
That's more like it!

If you're getting 50% GPU usage even while querying forces every step, that's probably about as good as you're going to do.

**Comment by capslockwizard** [comment]
Thanks!
