### ISSUE TITLE
Wrapping Problems When Applying CustomCentroidBondForce

### ISSUE THREAD

**Issue by Yuan-Yu** [pandegroup/openmm#2107]
I have ran a simulation with a CustomCentroidBondForce.

The COM of the peptide (yellow) and COM of the oxygen atoms (bead) representing the lipid heads of the membrane's upper layer were bonded and constrained by the `CustomCentroidBondForce` with `setUsesPeriodicBoundaryConditions(False)`.

In the trajectory file (dcd), most of the molecules were wrapped except for these 2 groups.

Is this the expected behavior?
![side](https://user-images.githubusercontent.com/8809778/42028130-02a15c38-7afe-11e8-9246-e84087d5366c.gif)

**Comment by peastman** [comment]
Wrapping is applied to whole molecules.  It will never split a single molecule in half.  It translates the entire molecule to put its centroid inside the box, which means some atoms can stick out beyond the edge of the box.

If two atoms are connected by any bonded force, including CustomCentroidBondForce, it treats them as a single molecule.  So that's what's happening here: it's viewing the entire upper layer of the membrane as a single molecule (for purposes of wrapping atom coordinates).  That isn't necessarily a problem, at least for short simulations.  But as time goes on and the individual lipids diffuse further away, it will hurt both accuracy and speed.

**Comment by Yuan-Yu** [comment]
Thanks for your help!
