### ISSUE TITLE
Extend NonbondedForce API to query/set global parameters

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#2117]
Since #2105 added the ability to specify global parameters to `NonbondedForce` to control the blending of offsets, it is critical we expose some common functionality for querying which parameters are available and setting their defaults. The `Custom*Force` objects do this through the following methods:
```python
force.getNumGlobalParameters()
force.getGlobalParameterName()
force.getGlobalParameterDefaultValue()
force.setGlobalParameterDefaultValue()
force.setGlobalParameterName() # this is less important?
```
I propose we also extend the `NonbondedForce` API with these methods.

Practically, our [`openmmtools`](http://github.com/choderalab/openmmtools) layer depends on [these API methods](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py#L746-L768) for inspecting which alchemical parameters are available for control. This API consistency among forces that can be modified with global context parameters turns out to be a very powerful way for writing alchemical (or other) codes with OpenMM, so it would be great to preserve this consistency.

cc: https://github.com/choderalab/openmmtools/issues/359 https://github.com/choderalab/perses/issues/476

**Comment by peastman** [comment]
That API doesn't make sense for NonbondedForce, because the set of parameters is already determined by the offsets.  If you want a list of all parameters in a force, that's easy to get.

```python
parameters = set([force.getParticleParameterOffset(i)[0] for i in range(force.getNumParticleParameterOffsets())])
parameters = parameters.union(set([force.getExceptionParameterOffset(i)[0] for i in range(force.getNumExceptionParameterOffsets())]))
```

All offset parameters have a default value of 0.

**Comment by jchodera** [comment]
There's a few reasons why it does make sense:
* It is enormously painful if the API for dealing with global context parameters is inconsistent among `Force` classes. Right now, every other force that exposes global context parameters uses the same API. API consistency is super important to allowing the same code using the library to still work when the API is extended. In this case, it broke our code.
* We often want offset parameters to have a *different* default value from zero.
* The idioms you suggest above, while compact, are not obvious. We want the API to be obvious in addition to consistent.
* The implementation could be completely confined to the C++ layer, so it wouldn't be complex to implement or require new implementations for each platform.

**Comment by jchodera** [comment]
You might also take a look at [our general code from `openmmtools`](https://github.com/choderalab/openmmtools/blob/master/openmmtools/alchemy.py#L746-L768). This quickly becomes a mess of special cases if we break API consistency for global parameters, which *also* then breaks the ability to use this general code to work with different versions of OpenMM. You can work around that with more exception handling, but you end up with a mess---all because we broke API consistency at the OpenMM layer.

**Comment by jchodera** [comment]
Our best alternative here to avoid crazy special cases is essentially to make a subclass of `NonbondedForce` that implements this API and use that instead of `NonbondedForce`, which seems like a poor approach since we could avoid that by just putting the consistent API into `NonbondedForce` directly.

**Comment by peastman** [comment]
Consistency works more than one way.  You're comparing this to custom force classes, but it isn't one, and it defines parameters in a different way.  You're asking for an API that is inherently inconsistent with how the class actually works.

If you want an API like you described, then we need to separate the  definition of parameters from the definition of offsets.  You would first call `addGlobalParameter()` for each parameter you want.  Then when you add the particle offsets, you would specify the index of the parameter you want each one to depend on.  Is that the interface you want?

> The implementation could be completely confined to the C++ layer, so it wouldn't be complex to implement or require new implementations for each platform.

It's the other way around.  Changes in the Python layer don't require new implementations for each platform.  Changes in the C++ layer *do* require changes to each platform.

**Comment by jchodera** [comment]
> If you want an API like you described, then we need to separate the definition of parameters from the definition of offsets. You would first call addGlobalParameter() for each parameter you want. Then when you add the particle offsets, you would specify the index of the parameter you want each one to depend on. Is that the interface you want?

I think the additional consistency with the `Custom*Force`s would be useful, even if it requires one extra step. 

If I had my dream API, I'd go one step further and rework the API a bit to accommodate lepton expressions so that we could do
```python
nbforce.addGlobalParameter('lambda_electrostatics', 1.0)
nbforce.addParticleParameterOffset('(1-lambda_electrostatics^2)', particle_index, delta_charge, delta_sigma, delta_epsilon)
...
```
which would make this ridiculously flexible, but is likely a huge headache to make efficient on the GPU.

At the very least, the addition of `addGlobalParameter()` would serve a few useful goals:
* Simplify programming errors in which a simple typo might lead an offset with a misspelled parameter name would lead to the silent creation of a new parameter, rather than reuse of a previously-declared parameter
* Allow setting of a default value for the parameter when the `Context` is created

@andrrizzi @pgrinaway @Lnaden: You're major users of these features---what do you think?

> It's the other way around. Changes in the Python layer don't require new implementations for each platform. Changes in the C++ layer do require changes to each platform.

The management of these parameters prior to creation of a `Context` looked like it was fully handled by [`NonbondedForce.h`](https://github.com/pandegroup/openmm/blob/master/openmmapi/include/openmm/NonbondedForce.h), [`NonbondedForce.cpp`](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/NonbondedForce.cpp), and [`NonbondedForceImpl.cpp`](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/NonbondedForceImpl.cpp).

**Comment by pgrinaway** [comment]
From my end, I think all that is needed to ensure that the OpenMMTools API that John cited continues to work are corresponding methods on the `NonbondedForce` object as John originally notes. Basically, I would just need the ability to:

1) Query for global parameters that the force contains
2) Set the default for those parameters

ideally in a way that is consistent with other forces that support global parameters. I fully admit that I might be missing something obvious here, but it seems to me that this change wouldn't require modification of platform-specific code any more than the other methods to retrieve and set parameters do (besides `updateParametersInContext` obviously).

**Comment by Lnaden** [comment]
I mostly agree with what @pgrinaway says here. I think what we ultimately need is a way to query the `NonbondedForce` object to get what offset/global parameter names are present in the force, and have some way to change their default values. 

As I understand, the `getParticleParameterOffset` call creates a new Offset Parameter it keeps track of every time its called. So there exists 1 stored offset per Offset Parameter, per particle offset by that Parameter. At the `Force` object level, Parameter `MyParm` assigned to Particle A is independent of Parameter `MyParm` assigned to Particle B; and `NewParm` assigned to Particle A is also independent of `AnotherParm` also assigned to Particle A, similar to how the global parameters with the same name between different `Custom*Force`s don't know of each other, but at the particle and parameter level. Once cast to the `Context` object, the Offset Parameters of the same name get converted to the same parameter, and that parameter can be controlled through a `Context.setParameter(...)` call and its value can be tracked through the `Context.getParameter(...)` call. Please correct me if I understand any of this wrong, @peastman! 

The complaint @jchodera, @pgrinaway, and myself have is that spinning up a Context from an API and pre-Context preparation standpoint is not always feasible or reasonable, and the current API-way of accessing the Offset parameters is obtuse and not in line with what users have come to enjoy in the `Custom*Force` objects

I don't know why each offset needs to be tracked separately instead of each particle individually tracking its own offsets, I would guess for actual platform implementation though this is important. However, what if instead of doing a full overhaul of how the `NonbondedForce` Offsets work, we instead just add to the API helper functions to replicate the `Custom*Force` calls that does not change the implementation of the Parameters or the Platforms.

Would it be possible to add a map the `NonbondedForce` keeps track of which maps between a set of known offset parameter names and default values?

* `addParticleParameterOffset` checks for the existence of the `parameter` in the map keys and calls its default value, else, creates the parameter in the map, assigns new default value. Similar function for the `addExceptionParameterOffset`, but use the same parameter names.
* Create the `setParticleParameterOffsetDefaultValue` and `getParticleParameterOffsetDefaultValue` where the `set` function loops over all existing particle parameter pairs and sets the default value. Admittedly, this is a mouthful of a function and a bit inefficient due to the loop, but would require minimal changes and does not change the underlying functionality at all.

Under this framework, we might need to think about a function to access a particle, fetching all its offsets and/or accessing a single Offset Parameter and accessing all of its particles.

@jchodera @pgrinaway would this solve the API hooks you want?
@peastman does this sound feasible?

Or is this just a silly idea all around?

**Comment by pgrinaway** [comment]
Thanks @Lnaden , I think to summarize what we need for the OpenMMtools framework is just the method calls related to global parameters:

`getGlobalParameterDefaultValue`
`getGlobalParameterName`
`getNumGlobalParameters`
`setGlobalParameterDefaultValue`

so that the API for global parameters meaningfully matches the API for global parameters in Custom*Forces.

**Comment by peastman** [comment]
> However, what if instead of doing a full overhaul of how the NonbondedForce Offsets work, we instead just add to the API helper functions

There's no need for workarounds.  Let's just figure out what the API should be and implement it cleanly.  Does the design I described above work for you?  Do you see any problems with it?

**Comment by andrrizzi** [comment]
I think the solution described above (separating definition of parameters from its use) would work very well in our case.

To add some more context, the fundamental reason we need this is that our framework needs to be able to take two `System` objects and compare their alchemical state. With `Custom*Force`s, we can set the `lambda_electrostatics` global variable default values and compare them, but (if I understand the API correctly) there's currently no workaround for this with the new (awesome) feature as the default value of the offset parameters is hardcoded to 0, and it is only settable in the `Context`.

**Comment by peastman** [comment]
Does the implementation in #2119 work for everyone?

**Comment by pgrinaway** [comment]
Looks like that harmonizes with the other global parameter-bearing forces, so I'm +1 on it. Thanks a lot!
