### ISSUE TITLE
NaNs in energy (but not force) in some alchemical systems

### ISSUE THREAD

**Issue by pgrinaway** [pandegroup/openmm#2185]
I build an alchemical system (serialized info is attached), and when I slightly increment the context parameter `lambda_sterics`, the energy becomes very large and eventually nan after a few steps. However, it returns from NaNdyland multiple times (sometimes even going back to a reasonable value), continuing to integrate just fine with the `LangevinIntegrator`. To run the attached example, just run `python reproduce.py` in the directory with the serialized system, state, and integrator (also in the zip file)

This is happening on CUDA 10, and with the `CustomNonbondedForce` (there is only one here). I just ran this with commit `76780ee`. The GPU was a GTX Titan. Thanks for the help, and let me know what else I can do!

cc @andrrizzi @jchodera 

[reproduce.tar.gz](https://github.com/pandegroup/openmm/files/2462182/reproduce.tar.gz)

**Comment by jchodera** [comment]
@peastman : Thanks!

@pgrinaway : It does look to me like this may be a completely separate issue from the NaN bug we're seeing with YANK. In this case, setting the `lambda_sterics` ten times smaller to `0.0001` results in stable simulations, but `0.001` does not, and it only happens if the `CustomNonbondedForce` `lambda_sterics` is changed. This suggests to me that there must have been some change in our functional form that may have made the energies very sensitive near `lambda = 0`. We should be able to quickly get to the bottom of this.

**Comment by jchodera** [comment]
@pgrinaway : I think I've spotted your problem! In your `CustomNonbondedForce`, you are creating intermediate variables `dummyA` and `dummyB` that are supposed to be 1 if the A or B state is a dummy atom (`epsilon = 0`), but only one should ever be a dummy atom. However, the energy as a function of `lambda` was basically increasing linearly with high slope near `lambda = 0`.
![image](https://user-images.githubusercontent.com/3656088/46711743-96252480-cc1b-11e8-98c5-76f495240ff0.png)
The logic you used was this:
```
dummyA = select(step(2*epsilonA - epsilonA), 0, 1);dummyB = select(step(2*epsilonB - epsilonB), 0, 1)
```
The idea is that `2*epsilonA - epsilonA` should evaluate to 0 if `epsilonA = 0`, which you would want to select the last case `z` in `select(x,y,z)`.

However, the problem is that `step(x)` is defined such that this only happens if the argument `x` is *less than* zero, not exactly zero. From [the docs](http://docs.openmm.org/latest/api-python/generated/simtk.openmm.openmm.CustomNonbondedForce.html#simtk.openmm.openmm.CustomNonbondedForce):
"step(x) = 0 if x is less than 0, 1 otherwise."

Instead, I think you want to subtract off a small amount to have `step(0) = 1`:
```
dummyA = select(step(2*epsilonA - epsilonA - small), 0, 1);dummyB = select(step(2*epsilonB - epsilonB - small), 0, 1)
```
where `small` would have to be smaller than your smallest nonzero `epsilon`.

Alternatively, you can use `delta(x)` which is 1 only if `x` = 0:
```
dummyA = delta(epsilonA); dummyB = delta(epsilonB);
```
The `delta(x)` option is probably simplest, and I've confirmed it works!
![image](https://user-images.githubusercontent.com/3656088/46711721-80affa80-cc1b-11e8-8c75-e0d4c5213cde.png)

**Comment by pgrinaway** [comment]
Wow, thanks! I suppose we changed that when we switched to SAMS and didn't see it as often.
@peastman sorry about the confusion + thanks for your time!

**Comment by pgrinaway** [comment]
I'll look more into this, but in the updated system I see the same. Maybe it's something on my side again.

cc @jchodera 
[reproduce2.tar.gz](https://github.com/pandegroup/openmm/files/2465801/reproduce2.tar.gz)

**Comment by pgrinaway** [comment]
Actually, to add one thing: when I'm running this (at least on OpenCL) I get this pattern of energies after incrementing the `lambda_sterics` parameter to 0.001 (I don't change it further)

```
-18162.798864067936 kJ/mol #initial
-197860793.86136407 kJ/mol #after changing lambda_sterics to 0.001
23718506390.138638 kJ/mol #after 1 step
187835858838.13864 kJ/mol #after 2 steps
832444825494.1387 kJ/mol #etc
866892775318.1387 kJ/mol
901895753301910.1 kJ/mol
6757508186006.139 kJ/mol
```

I think it's a little unusual that the energy is first deeply negative after changing the parameter, but maybe this is again on my side. Just posting it in case it helps someone.

**Comment by peastman** [comment]
A large negative energy is exactly what you'd get if, for example, two atoms are attracting each other very strongly.  That would produce a huge force, causing the simulation to immediately blow up.

**Comment by jchodera** [comment]
It turns out that this blows up with 76780ee but works fine with f6cbe7d. 

We don't think there should be two unshielded atoms attracting each other strongly. I wonder if the offset bugfix introduced in https://github.com/pandegroup/openmm/pull/2176 may have caused some sort of unanticipated weird issue here.

**Comment by peastman** [comment]
Ok, I'll take a look and see if I can figure out what's going on.

**Comment by peastman** [comment]
Found it!  There is indeed an indexing error related to parameter offsets for exceptions.  I'll get the fix in shortly.

**Comment by pgrinaway** [comment]
Thanks! My script seems to run fine with your recent patch @peastman !
