### ISSUE TITLE
charmm36 fails to patch, but amber14 works

### ISSUE THREAD

**Issue by jjgoings** [pandegroup/openmm#2220]
Hi,

I'm using OpenMM 7.3.0 on my MacBook. May be related to #2047.

Using PDBFixer I downloaded and prepared a PDB (crambin, no solvent) [1EJG.pdb](https://github.com/pandegroup/openmm/files/2644717/1EJG.pdb.txt)

When I do 
```
from simtk.openmm.app import *

forcefield = ForceField('amber14-all.xml')
#forcefield = ForceField('charmm36.xml')

pdb = pdbfile.PDBFile('1EJG.pdb')

unmatched = forcefield.getUnmatchedResidues(pdb.topology)
print(unmatched)

system = forcefield.createSystem(pdb.topology)
```

I get no error and all residues appear to be matched. When I change tot the `charmm36.xml` force field, i.e.
```
#forcefield = ForceField('amber14-all.xml')
forcefield = ForceField('charmm36.xml')
```

I get unmatched residues along with the error

```
[<Residue 0 (THR) of chain 0>, <Residue 2 (CYS) of chain 0>, <Residue 3 (CYS) of chain 0>, <Residue 15 (CYS) of chain 0>, <Residue 25 (CYS) of chain 0>, <Residue 31 (CYS) of chain 0>, <Residue 39 (CYS) of chain 0>, <Residue 45 (ASN) of chain 0>]
Traceback (most recent call last):
  File "minimal.py", line 12, in <module>
    system = forcefield.createSystem(pdb.topology)
  File "/Users/jjgoings/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1118, in createSystem
    unmatchedResidues = _applyPatchesToMatchResidues(self, data, unmatchedResidues, bondedToAtom, ignoreExternalBonds)
  File "/Users/jjgoings/miniconda3/lib/python3.6/site-packages/simtk/openmm/app/forcefield.py", line 1579, in _applyPatchesToMatchResidues
    unmatchedResidues.remove(residue)
ValueError: list.remove(x): x not in list
```

It appears that CHARMM36 cannot automatically patch the terminal residues and cysteines properly, while AMBER14 (and AMBER99SB) can. Why might this be the case, and how can I proceed?

Thanks!

**Comment by peastman** [comment]
Thanks!  I see the problem.  It's because residues 2 and 3 are both CYS residues that form disulfide bonds.  It correctly identifies the patches to create the bonds (2 to 39 and 3 to 31).  But then it sees that residues 2 and 3 are also bonded to each other, gets confused, and tries to also apply a patch to them.

**Comment by peastman** [comment]
This is fixed in #2222.  Could you try it and see if it works for you?

Note that `getUnmatchedResidues()` doesn't take patches into account.  It's an experimental method that doesn't handle some advanced features.  So it reports all the CYS residues being unmatched, but at least it doesn't throw an exception.  And `createSystem()` handles everything correctly now.

**Comment by jjgoings** [comment]
Okay, thanks. 17725b6 no longer throws an error in `createSystem()`. 

Other than not having an error thrown, is there anything else I should check to ensure that the patches are correctly applied?

That is good to note about `getUnmatchedResidues()`.

**Comment by peastman** [comment]
If you have any doubts, the best thing to do is to compute the energy both with OpenMM and CHARMM and make sure they agree.

**Comment by jjgoings** [comment]
Sounds good, I’ll mark this closed. Thanks for your help!
