### ISSUE TITLE
Possible bug when computing distances in CustomCentroidBondForce

### ISSUE THREAD

**Issue by ajsilveira** [pandegroup/openmm#2291]
The function distance(g1,g2) in CustomCentroidBondForce is yielding a wrong distance for periodic systems when using platforms CUDA or OpenCL. It works fine for platforms
Reference and CPU. I am using OpenMM 7.3.1. The following script reproduces the issue. 
The pdb is here https://gist.github.com/ajsilveira/d479d0a29452620f6b94fe7f1a62e1bd

```
import os
import numpy as np
from simtk import openmm, unit
from simtk.openmm import app

pdb = app.PDBFile('pdb_for_testing.pdb')
forcefield = app.ForceField('amber14/tip3p.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME)

g1 = [0, 1, 2]
g2 = [3, 4, 5]
g1_positions = [pdb.positions[index]/unit.nanometer for index in g1]
g2_positions = [pdb.positions[index]/unit.nanometer for index in g2]
distance = np.linalg.norm(np.mean(np.asarray(g1_positions), axis=0) - np.mean(np.asarray(g2_positions), axis=0))
print('Actual distance', distance)

r = openmm.openmm.CustomCentroidBondForce(2, 'distance(g1,g2)')
r.addGroup(g1)
r.addGroup(g2)
r.addBond([0,1], [])

cvforce = openmm.CustomCVForce('r')
cvforce.addCollectiveVariable('r', r)
system.addForce(cvforce)

platform = openmm.Platform.getPlatformByName('CUDA')
integrator = openmm.CustomIntegrator(0)
simulation = app.Simulation(pdb.topology, system, integrator, platform)
simulation.context.setPositions(pdb.positions)
for name in ['Reference', 'CPU', 'OpenCL', 'CUDA']:
    platform = openmm.Platform.getPlatformByName(name)
    integrator = openmm.CustomIntegrator(0)
    context = openmm.Context(system, integrator, platform)
    context.setPositions(pdb.positions)
    print(name, cvforce.getCollectiveVariableValues(context)[0])

```

**Comment by jchodera** [comment]
I can confirm I can independently reproduce this issue with OpenMM 7.3.1 and CUDA 9.1:
```
[chodera@lilac:ana-issues]$ python run-test.py 
Actual distance 1.748344335523056
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 5.0819525718688965
CUDA 5.0819525718688965
```
@peastman : Any idea what might be going on here?

**Comment by jchodera** [comment]
I should note some lines in the script above are extraneous. Here's a more minimal example:
```python
import os
import numpy as np
from simtk import openmm, unit
from simtk.openmm import app

pdb = app.PDBFile('pdb_for_testing.pdb')
forcefield = app.ForceField('amber14/tip3p.xml')
system = forcefield.createSystem(pdb.topology, nonbondedMethod=app.PME)

g1 = [0, 1, 2]
g2 = [3, 4, 5]
g1_positions = [pdb.positions[index]/unit.nanometer for index in g1]
g2_positions = [pdb.positions[index]/unit.nanometer for index in g2]
distance = np.linalg.norm(np.mean(np.asarray(g1_positions), axis=0) - np.mean(np.asarray(g2_positions), axis=0))
print('Actual distance', distance)

r = openmm.openmm.CustomCentroidBondForce(2, 'distance(g1,g2)')
r.addGroup(g1)
r.addGroup(g2)
r.addBond([0,1], [])

cvforce = openmm.CustomCVForce('r')
cvforce.addCollectiveVariable('r', r)
system.addForce(cvforce)

for name in ['Reference', 'CPU', 'OpenCL', 'CUDA']:
    platform = openmm.Platform.getPlatformByName(name)
    integrator = openmm.CustomIntegrator(0)
    context = openmm.Context(system, integrator, platform)
    context.setPositions(pdb.positions)
    print(name, cvforce.getCollectiveVariableValues(context)[0])
```

**Comment by jchodera** [comment]
Switching from `PME` to `NoCutoff` changes all distances to be the same:
```
[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 1.748344335523056
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 1.7483444213867188
CUDA 1.7483444213867188
```
On the other hand, retaining `PME` and setting `CustomCentroidBondForce.setUsesPeriodicBoundaryConditons(True)` also generates another set of incorrect distances:
```
[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 1.748344335523056
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 3.390462636947632
CUDA 3.390462636947632
```

**Comment by jchodera** [comment]
If the particle groups only contain _one_ atom
```python
g1 = [0]
g2 = [3]
```
then the distances agree across platforms:
```
Actual distance 2.5321687404278572
Reference 2.5321687404278572
CPU 2.5321687404278572
OpenCL 2.5321686267852783
CUDA 2.5321686267852783
```
As soon as they have two atoms per group
```
g1 = [0, 1]
g2 = [3, 4]
```
the distances diverge:
```
[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 2.1467765667390726
Reference 2.1467765667390726
CPU 2.1467765667390726
OpenCL 4.785242557525635
CUDA 4.785242557525635
```

**Comment by jchodera** [comment]
I think I see the issue: If the atoms within each group are bound together into molecules by adding zero-energy `HarmonicBondForce` terms:
```
# Add zero energy bonds to make molecules                                                                                                                                                                                                                                       
bondforce = openmm.HarmonicBondForce()
for (i,j) in [ (0,1), (1,2), (3,4), (4,5) ]:
    bondforce.addBond(i, j, 0.0, 0.0)
system.addForce(bondforce)
```
the distances now agree:
```
[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 1.748344335523056
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 1.7483441829681396
CUDA 1.7483443021774292
```
@peastman: Could you describe a bit about what's going on here, and why the behavior differs when particles are grouped into molecules or not?

Is position wrapping being applied when particle positions are set on OpenCL and CUDA? If so, why do the numbers still disagree when `setUsesPeriodicBoundaryConditions` is `True`?

It seems like we at _least_ need to document the platform differences that lead to this divergent behavior, but this is so surprising that we probably want to make some changes to ensure consistent behavior.

**Comment by jchodera** [comment]
Increasing the box dimensions by 100 A in each dimension also causes the numbers to get much more wrong:
```
python run-[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 1.748344335523056
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 12.414776802062988
CUDA 12.414776802062988
```
If I translate the system by +30 A in each dimension prior to calling `context.setPositions()`, 
```python
pdb.positions = pdb.getPositions(asNumpy=True) + 30*unit.angstroms
```
then I get all platforms to agree:
```
[chodera@lilac:ana-issues]$ python run-test.py
Actual distance 1.7483443355230566
Reference 1.748344335523056
CPU 1.748344335523056
OpenCL 1.7483441829681396
CUDA 1.7483443021774292
```
It seems pretty clear that the CUDA and OpenCL platforms are erroneously wrapping the coordinates via the box vectors on calling `context.setPositions()`. 

We should revisit both when this should occur and ensure that it happens the same way for all platforms.

Also, I still don't have an explanation for why this would lead to differences between platforms when `setUsesPeriodicBoundaryConditions` is set to `True`. Even if the positions are wrapped, this should still recover the correct distances on all platforms.

**Comment by peastman** [comment]
I think I see what's going on.  It's a pathological case involving interactions between the CustomCVForce, the CustomCentroidBondForce, and periodic boundary conditions.  I need to think about what I can do to make the behavior more consistent.  Let me try to explain roughly what's happening.

By specifying PME you tell it that it's a periodic system.  In a periodic system, particle positions are really only defined up to a translation by an arbitrary box vector.  Effectively, each "particle" represents an infinite grid of particles repeating through space.  It's undefined which of those infinite copies will get used internally for computing forces.  The OpenCL and CUDA platforms take advantage of that, internally translating particle positions to keep things inside a single periodic box.  That's essential for maintaining accuracy in single precision.

Normally this doesn't matter, because forces only depend on the displacements between particles, not absolute positions.  But CustomCentroidBondForce is an exception.  If you add a lattice vector to a subset of the particles in a group, the centroid of that group changes by an amount that isn't a lattice vector.  That means the distances between centroids (taking periodic boundary conditions into account) change.

Usually this isn't a problem, because it doesn't break up molecules when translating particles.  It makes sure that all the particles in a molecule get translated by the same amount.  And usually CustomCentroidBondForce is used on whole molecules or pieces of molecules.  So all the particles in a group get translated by the same amount, and the centroid gets translated by a valid lattice vector, which doesn't change periodic distances between centroids.  Your system is unusual because each "group" consists of three independent atoms that aren't bonded to each other.

In terms of the implementation, there's even more going on than that.  The CustomCVForce is complicating things.  If you added the CustomCentroidBondForce directly to the System the problem wouldn't appear.  The details are very complicated, and I need to think about how to handle it.
