### ISSUE TITLE
Clarification on Ewald cutoffs and 1-4 scaled interactions

### ISSUE THREAD

**Issue by proteneer** [pandegroup/openmm#2304]
What is the correct treatment of a 1-4 interaction that is scaled by 0.5 but outside of the cutoff radius? If I'm reading ReferenceLJCoulombIxn.cpp correctly, the Ewald code completely skips exceptions from the calculation. Instead, the ReferenceLJCoulomb14.cpp is instead used to compute the 1-4 scaled exceptions, even if it's outside of the cutoff. 

Is this the correct intended behavior?

**Comment by peastman** [comment]
Nonbonded exceptions need special treatment with Ewald.  To understand what's going on you need to keep the following principles in mind.

1. There are no cutoffs with Ewald.  All interactions out to infinity get included.  Yes, we split the calculation into direct space and reciprocal space parts, but that's just for computational efficiency.  They need to sum to the full set of interactions without cutoffs.

2. Exceptions only apply to the two specific atoms that are in the same molecule.  Remember, each "atom" represents an infinite set of atoms repeating through space.  Two atoms that are bonded to each other have their interaction reduced, but they each interact at full strength with all the other periodic copies of the other atom.  Those atoms are in different molecules.

3. You can't exclude interactions from two specific atoms (but not their periodic copies) from the reciprocal space calculation.  There just isn't any way to do it.

So exceptions get included in the reciprocal space part whether you want them to or not.  Then you have to do two different things in direct space.  1) Subtract off the part of the interaction that was incorrectly included in the reciprocal space calculation.  2) Add in the full interaction (with no cutoff, because there aren't supposed to be any cutoffs) using the scaled parameters specified by the exception.

**Comment by proteneer** [comment]
Thank you for the detailed response, I think I understand this now. In my particular implementation of exceptions and inclusions, I'm using an N^2 scale_matrix, where dij=0 if it's an exception, dij=0.4 if it's a 1-4 scaled interaction, and dij=1.0 for all other interactions. So I'm going to implement this in two passes:

1) Conventional Ewald assuming no exceptions and no exclusions (i.e. not using the scale matrix at all), where the cutoff is solely used to determined which parts are done in direct space, and which parts are done in reciprocal space. 

2) Independent of any cutoffs, correct by the erf (alphaEwald*(1-scale_matrix)*interaction energy). Essentially, exceptions are weighted with 1.0, 1-4 interactions with 0.6, and all other terms are 0). 

Does this sound reasonable?

**Comment by proteneer** [comment]
On a related note - it also looks like proper non-truncated treatment of the r^-6 term in LennardJones is only supported via PME (and not Ewald).

**Comment by peastman** [comment]
Mostly yes.  The one thing to be aware of is that you may lose a bit of accuracy, because you'll be adding and then subtracting a large number for each 1-2 interaction.  If you can contrive to just never add those in at all, you'll gain a bit of precision.

> it also looks like proper non-truncated treatment of the r^-6 term in LennardJones is only supported via PME (and not Ewald).

Correct, NonbondedForce doesn't have a LJEwald option, just LJPME.

**Comment by proteneer** [comment]
Thanks Peter! I've implemented the scheme above:

https://github.com/proteneer/timemachine/pull/76/files

Really excited to see what we can do with this capability soon :)
