### ISSUE TITLE
ewaldErrorTolerance has extreme effect on overall speed on GPU

### ISSUE THREAD

**Issue by gitkol** [pandegroup/openmm#2330]
Hi, we noticed something with ewaldErrorTolerance that might be worth mentioning. We tested this with several systems and all show the same behavior. This particular system is a standard protein in TIP3P water and Amber force field, about 50,000 atoms. Here is the simulation setup.
# System Configuration
nonbondedMethod = PME
nonbondedCutoff = 0.8*nanometers
ewaldErrorTolerance = 5e-4
constraints = HBonds
rigidWater = True
constraintTolerance = 1e-5
# Integration Options
dt = 8*femtoseconds
temperature = 300*kelvin
collisionFreq = 1/picosecond
friction = 1/picosecond
pressure = 1.0*atmospheres
barostatInterval = 25
# Simulation Options
steps = 1000000
platform = Platform.getPlatformByName('CUDA')
platformProperties = {'Precision': 'mixed'}
# Prepare the Simulation
topology = pdb.topology
positions = pdb.positions
system = forcefield.createSystem(topology, nonbondedMethod=nonbondedMethod, nonbondedCutoff=nonbondedCutoff, constraints=constraints, rigidWater=rigidWater, ewaldErrorTolerance=ewaldErrorTolerance, hydrogenMass=3*amu)
# Thermostat, barostat
system.addForce(AndersenThermostat(temperature, collisionFreq))
system.addForce(MonteCarloBarostat(pressure, temperature, barostatInterval))
# Integrator
nonbonded = [f for f in system.getForces() if isinstance(f, NonbondedForce)][0]
nonbonded.setReciprocalSpaceForceGroup(1)
integrator = MTSIntegrator(dt, [(1,1), (0,2)])
integrator.setConstraintTolerance(constraintTolerance)
# Define simulation
simulation = Simulation(topology, system, integrator, platform, platformProperties)
simulation.context.setPositions(positions)

The following table shows overall speed in ns/day on GTX 1080 Ti varying ewaldErrorTolerance, MTS ratio of near-far split, time step, and whether or not using HMR with H-mass=3amu.
    ewaldErrorTolerance
1e-5    5e-5    1e-4    5e-4
                                              MTS(1:1), noHMR, 2fs
15.9    28.0    42.6    67.7 ns/day
                                              MTS(1:1), HMR3, 4fs
37.0    65.3    103     170
                                              MTS(2:1), HMR3, 4fs
57.2    98.1    141     213

We analyzed all these simulations with Michael Shirts' physical validation package testing whether the equipartition principle holds for the whole system as well as separately for the protein and water, and found that every single simulation was acceptable for all practical purposes. Moreover, there was virtually no noticeable difference between simulations using different ewaldErrorTolerance values. So, it seems that ewaldErrorTolerance is the single most important parameter to tune with overall speed-up by a factor of ~4 and that is great, but I just wonder if that is too good to be true. Why would overall speed be extremely dependent on a single PME parameter? In Desmond we set Ewald tolerance to 1e-10 by default and loosening it doesn't seem to have noticeable effect.

Any comments or clarification is highly appreciated.

Thanks,

   Istvan

**Comment by peastman** [comment]
It's important to understand exactly what the `ewaldErrorTolerance` parameter is doing.  This is described at http://docs.openmm.org/latest/userguide/theory.html#coulomb-interaction-with-particle-mesh-ewald.  I don't know how the parameter in Desmond is defined, but some MD codes have "Ewald tolerances" that really are just a shorthand for specifying alpha.  The parameter in OpenMM does a lot more than that.  By reducing the tolerance, you cause it to use a larger grid, which of course makes the simulation slower.

Also note that the grid size depends on the nonbonded cutoff.  The idea is that you pick the error tolerance based on how accurate you want the forces to be, and then the cutoff distance becomes a free parameter you can adjust to optimize performance.  You're using a cutoff of 0.8 nm, which is on the small side.  With CUDA, I usually find the performance is better with a cutoff around 0.9 or 0.95 nm.  When you increase the cutoff, it automatically reduces the size of the reciprocal space grid, shifting work from reciprocal space to direct space while keeping the accuracy of the results constant.

> Moreover, there was virtually no noticeable difference between simulations using different ewaldErrorTolerance values.

The largest tolerance you considered was 5e-4, which also happens to be the default value.  We picked that as the default because it's accurate enough for many purposes while keeping things as fast as possible.  If you were to try larger values, you should see the results start to get worse.

**Comment by gitkol** [comment]
Thanks for the clarification, Peter. `ewaldErrorTolerance` is more than a single parameter then :) and that explains it. Great that I can typically use 5e-4.
