### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bdice** [pandegroup/openmm#2346]
Hi! I was trying to find the license information for this package. I searched the repository and documentation but wasn't able to find anything.

After googling, I found this page: https://simtk.org/plugins/moinmoin/openmm/License
Is this the correct / up-to-date license?

Would it be possible to make the software's license more visible to users and developers, perhaps via a `LICENSE.txt` in the root of the repository and/or in the docs? Thanks!

**Comment by Lnaden** [comment]
Different parts of the OpenMM code are licensed under different licenses, which is why there isn't just one file. You should be able to find what you need here:

https://github.com/pandegroup/openmm/tree/master/docs-source/licenses

And some additional info in the user guide:

http://docs.openmm.org/latest/userguide/library.html#license

**Comment by bdice** [comment]
Great, thanks for clarifying!

**Comment by jchodera** [comment]
It *would* be useful to confirm to standards and have a LICENSE file at the root level of the repo.
