### ISSUE TITLE
CutoffNonPeriodic should not use reaction-field electrostatics

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#397]
When a cutoff is used in a non-periodic system, reaction-field electrostatics should not be used.

I may be reading the code wrong, but this seems to suggest that reaction-field electrostatics are used whenever a cutoff is employed:
https://github.com/SimTk/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp#L590-L591
Also, the tests (specifically, `testCutoff()` in `TestReferenceNonbondedForce`) test the `CutoffNonPeriodic` condition against reaction-field electrostatics:
https://github.com/SimTk/openmm/blob/master/platforms/reference/src/SimTKReference/ReferenceLJCoulombIxn.cpp#L590-L591

**Comment by peastman** [comment]
I believe the conclusion of this discussion was not to change the behavior, so I'm closing it.

**Comment by jchodera** [comment]
I don't think this is quite settled.  There have also been numerous reports that GBSA with a cutoff behaves very, very oddly, and part of that problem may be that `CutoffNonPeriodic` uses a reaction-field treatment of Coulomb electrostatics while the [GBSAOBCForce is not adapted to use a reaction-field treatment](http://docs.openmm.org/6.2.0/userguide/theory.html#generalized-born-term) for `CutoffNonPeriodic`.

**Comment by swails** [comment]
If we were picking the defaults today, I think that RF with `CutoffNonPeriodic` is marginally worse than no RF since I think it's more common to use GB in that scenario than no implicit solvent model at all.

The main reason IMO for keeping the current default is that it's been this way for a long time already.  And of all nonbonded schemes to use, `CutoffNonPeriodic` is probably the stupidest choice for `NonbondedForce`.  Combine that with the fact that all of the existing parsers already do the right thing, and I think this whole decision is rather unimportant.  So I'm solidly +/-0 on changing this (I don't think it matters, and in that case inertia probably wins).

**Comment by jchodera** [comment]
> Combine that with the fact that all of the existing parsers already do the right thing

Ah!  I had forgotten about that line:
https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/internal/amber_file_parser.py#L1095

I'll keep looking for the issues with GB cutoffs then...

**Comment by peastman** [comment]
ForceField also disables RF if you add a GBSAOBCForce to the system:

https://github.com/pandegroup/openmm/blob/master/wrappers/python/simtk/openmm/app/forcefield.py#L1267-L1272

**Comment by swails** [comment]
I think all `System` creators do.  I checked Amber, Gromacs, and CHARMM (Desmond doesn't offer implicit solvent options at all), and as @peastman pointed out, so does ForceField.

**Comment by JoaoRodrigues** [comment]
Not to resurrect a dead issue, but I just wanted to add a potential use case where this (having the automatic RF correction) leads to very confusing results.

I wanted to calculate the pairwise energy of a particular pair of atoms and I found that setting `force.setReactionFieldDielectric(1.0)` _still_ applies a correction to the energy. In CpuNonbondedForce.cpp, the total energy in case we specify `CutoffNonPeriodic` and a small cutoff, say 1 nm, is given by `energy += (float) (chargeProd*(inverseR+krf*r2-crf));`, where krf is indeed 0.0 but not crf. This is quite different from, for example, running the `pairwise`  command on cpptraj, which gives the 'proper' energy without any correction.

As OpenMM is a _library_, it should not, in my opinion as a user, do this sort of decisions under the hood. I agree with @jchodera that there should be a way to absolutely disable the RF correction, even if it's the stupidest thing in the universe. I can use a `CustomNonbondedForce` to go around this, or just use a NoCutoff, but it means I'll suffer quite a bit with performance, either from the unoptimized kernels or because I'll have to go about calling `setParticleParameters` and `updateParametersInContext` for pair of atoms... 

Sorry if this sounds a bit like a rant, but I spent two days figuring out why the NonbondedForce of a two atom system was not matching what I had on paper and what I wrote from a CustomNonbondedForce.

**Comment by proteneer** [comment]
@JoaoRodrigues  I'm literally debugging this right now and ran into the same behavior. I'm +1 on disabling the rf correction.

**Comment by proteneer** [comment]
What's more insane is that we *do* turn off the crf offset when computing the 1-4 exceptions

**Comment by peastman** [comment]
> What's more insane is that we do turn off the crf offset when computing the 1-4 exceptions

It's not just the offset.  Reaction field isn't applied to 1-4 interactions.  Nor are cutoffs, nor periodic boundary conditions.  That's because they're fundamentally bonded interactions, not nonbonded.  Likewise, if you use PME, the exception is only applied to the two particular bonded atoms.  The interactions of each one with all the infinite periodic images of the other are computed with the standard parameter values.
