### ISSUE TITLE
Is there some strategy that could reduce code duplication in unit tests?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#651]
Currently, all unit tests are implemented separately for each `platform`.  Most, but all, of this code is an exact duplication for each `platform`, with only a few lines changed to invoke the appropriate `Platform` class.

Is there some way that the common code could be extracted into a common `unit-testing/` directory and compiled separately for each platform, with only the platform-specific tests remaining within each `platform/` directory?  This might significantly aid code maintenance down the road.

Also, it would be useful to annotate each unit test with a human-readable description of what exactly is tested in each test component.  For example, many of the tests currently have unilluminating names like `testTemperature()` that essentially require reading the whole function in detail to comprehend what is being tested and how.  A simple statement like

> Ensure average of instantaneous kinetic temperature for 8 charged LJ particles matches control temperature when an Andersen thermostat is used over 150 ps simulation.

would significantly speed comprehension.

**Comment by peastman** [comment]
I've been thinking about how to do this.  A very simple approach would be to move most of the test content into header files that would be \#included in each file.  For example, the full content of TestCudaHarmonicAngleForce.cpp would look something like this

```C++
#include "CudaTests.h"
#include "TestHarmonicAngleForce.h"

void runPlatformTests() {
}
```

CudaTests.h would declare the `Platform` object, and provide code for processing command line arguments and setting the precision mode based on them.  TestHarmonicAngleForce.h would contain the test functions, as well as the `main()` function that invoked them.  It would also invoke `runPlatformTests()`, so that each platform could add its own tests beyond the generic ones.  Does that sound reasonable?

There will still be some cases where tests need to be duplicated, since they have subtle variations between platforms.  But that will hopefully represent only a small fraction of all tests.

**Comment by jchodera** [comment]
This sounds like a great idea.

**Comment by peastman** [comment]
I converted a couple of tests to work this way.  Take a look at https://github.com/pandegroup/openmm/compare/master...peastman:tests.  Does it look ok?  Any suggestions for changes?  It's going to be a lot of work to convert everything, so I want to pin down all the details of how it should work first.

**Comment by jchodera** [comment]
This looks so much cleaner!  

It looks like the platform tests are now as simple as:
```
#include "ReferenceTests.h"
#include "TestHarmonicBondForce.h"

void runPlatformTests() {
}
```
where the `runPlatformTests()` function must be implemented for each platform, though it can be empty.  The `main()` is in the `TestHarmonicBondForce.h` header, and the `ReferenceTests.h` defines the `Platform` to be used for tests of the `Reference` platform.

Others may have input into ways to make this even more minimalistic, but I couldn't think of anything that would obviously improve on this.

It does look like a lot of work, but I think this will shrink the codebase by a great deal, and potentially catch any weird inconsistencies that might sneak in between platforms.  

Definitely +1 on this.

**Comment by jchodera** [comment]
Whoops, apologies for reproducing essentially your proposed structure above---I had swapped it out of memory!

**Comment by jchodera** [comment]
Nicely done!
