### ISSUE TITLE
Subtle issue with MonteCarloBarostat random number seed

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#763]
This may be more of a cautionary tale than an actual issue (unless someone can think of a clever way to address this), but I recently tried to run 100 replicates of an NPT argon fluid using a scheme like this:
```
create System
add barostat to system
for replicate = 1..100
   create Langevin integrator
   create Context
   set initial positions
   simulate
```
This scheme led to an odd synchronization effect in which it appeared that the `MonteCarloBarostat` was using the same sequence of random numbers, inducing synchronization on the density trajectory, similar to what has been previously observed by [Voter](http://dx.doi.org/10.1063/1.1667473) and [Roitberg](http://dx.doi.org/10.1021/ct800573m).

Restructuring this to add a new barostat each replicate eliminated this effect:
```
create System
or replicate = 1..100
   make new deep copy of System
   add barostat to system
   create Langevin integrator
   create Context
   set initial positions
   simulate
```
This is obvious in hindsight, since creating a barostat assigns a new random number seed to it, but I just wonder if there is something we might want to do in order to avoid this kind of (subtle) bug in the future.

**Comment by rmcgibbo** [comment]
Integrators are only permitted to bind to, at maximum, one context. It would be conceivable that a similar restriction could be applied to `Force`s containing prng seeds, but I haven't thought through the implications of this enough to know if it would be desirable.

**Comment by swails** [comment]
> Integrators are only permitted to bind to, at maximum, one context. It would be conceivable that a similar restriction could be applied to Forces containing prng seeds, but I haven't thought through the implications of this enough to know if it would be desirable.

Integrators are fundamentally different here.  The `Integrator` subclass does all of the work for a particular `Context`.  By contrast, `Force`s don't actually _do_ any of their own calculation -- it is the `ForceImpl` objects that get created by the `ContextImpl` that actually do the work and must be uniquely bound to a single `Context`.

A force can create as many `ForceImpl` instances as it wants (and `ForceImpl` cannot modify its parent `Force`, as indicated by the `const Force&` reference in its private variable list).

The random number generator is stored and initialized inside of the `MonteCarloBarostatImpl` class -- see [here](https://github.com/pandegroup/openmm/blob/master/openmmapi/src/MonteCarloAnisotropicBarostatImpl.cpp#L63).  The problem is that the random generator is seeded from the `owner` object -- which means that multiple `MonteCarloBarostatImpl` instances generated from the same `MonteCarloBarostat` will have the same seed.

@jchodera -- my suggestion would be to explicitly call `MonteCarloBarostat.setRandomNumberSeed` after each time you create a `Context` (or `Simulation`), and the same to `AndersenThermostat.setRandomNumberSeed` if you use that thermostat -- the `LangevinIntegrator` is unique to a `Context`, so there is no worry there.

A few comments here:

1. Perhaps we could change things so that a call to `MonteCarloBarostat.createImpl` assigns its random seed to the resulting `MonteCarloBarostatImpl` instance and then changes its own seed so the next time it's called the seed will be unique (do we care about thread safety here?).
2. If we don't do 1 (also for the other stochastic Forces), we should document the requirement to use `setRandomNumberSeed` to ensure unique streams when using the same Force object in the manual as well as perhaps a note in the API docs through Doxygen.

I would personally prefer 1, since most people should use different seeds for each Context, it's easy to forget to do this, and it may be very difficult to notice that this synchronization is happening.

**Comment by rmcgibbo** [comment]
Good analysis. Updating the random seed on `createImpl` seems like a simple
& low-friction way to avoid a potential 'gotcha' from these APIs.

**Comment by swails** [comment]
> This may be more of a cautionary tale than an actual issue (unless someone can think of a clever way to address this), but I recently tried to run 100 replicates of an NPT argon fluid using a scheme like this:
> 
```
> create System
> add barostat to system
> for replicate = 1..100
>    create Langevin integrator
>    create Context
>    set initial positions
>    simulate
```

To be explicit, do this:

```
create System
add barostat to system
for replicate = 1..100
    create Langevin integrator
    create Context
    barostat.setRandomNumberSeed(random.randint(1, 10000))  # new line
    set initial positions
    simulate
```

No need for a `deepcopy` here.

(I meant to post this a couple days ago... seems I forgot)

**Comment by peastman** [comment]
I'm not sure of what's a good solution to this, but I don't like the idea of silently modifying the Force object in createImpl().  Remember that createImpl() is a const method, and for good reason.  Otherwise, you would get really strange and surprising behaviors.  For example, if you created a System and then serialized it to XML, you would get a different serialized system depending on whether you did that before or after creating a Context.  If you did it after, you would actually be serializing a different System from the one you just created the Context for, and it wouldn't be able to reproduce the results from the Context you just created.

**Comment by jchodera** [comment]
Thanks for the thoughtful discussion, everybody!

I certainly like the idea of adding to the API docs as well as the manual so that users have a better appreciation of the issues here and how to avoid running into trouble.  I'm happy to put together a PR to do this.

Longer-term, I think a more general solution might be to implement the `CompositeIntegrator` scheme @peastman suggested at one point that would allow multiple integrators to be active at once, potentially chained.  Then, `MonteCarloBarostat` be implemented as an `Integrator` rather than a `Force`, and all of the objects with random number seeds that would affect integration would be full-fledged integrators. Since this would require some fundamental changes, this is clearly longer-term.

For the short term, what about a solution involving adding a method to `Context` that would simply use the already-in-place `osrngseed()` approach to generate new random seeds for everything that has a random number seed attached to it?  The usage would be, for example,
```
context = Context(system, integrator)
context.setPositions(positions)
context.generateNewRandomSeeds()
# now we're ready to run a fully independent simulation
```
This would save the user from having to come up with a new way to generate unique random seeds, since it could simply use the same `osrngseed()` scheme currently used under the hood on `createImpl()`, and it wouldn't break any existing code where the user might *want* to maintain random seeds.  Our little discussion in the manual could suggest that users should use `context.generateNewRandomSeeds()` if they want to ensure the next simulation they run is really independent of the previous simulation they used the same `Context` or `System` to run.

**Comment by swails** [comment]
> I'm not sure of what's a good solution to this, but I don't like the idea of silently modifying the Force object in createImpl(). Remember that createImpl() is a const method, and for good reason. Otherwise, you would get really strange and surprising behaviors. For example, if you created a System and then serialized it to XML, you would get a different serialized system depending on whether you did that before or after creating a Context. If you did it after, you would actually be serializing a different System from the one you just created the Context for, and it wouldn't be able to reproduce the results from the Context you just created.

Good points.  Here's another idea -- `MonteCarloBarostat` _has_ no default seed.  If the random generator seed is 0, the call to `MonteCarloBarostat.getRandomNumberSeed` uses `osrngseed` to generate one -- no changes to the underlying `Force`, but a much better chance that each `ForceImpl` gets a unique seed by "default".

This way, if someone explicitly calls `getRandomNumberSeed` in their code, this change has no effect.  Otherwise, the "default" behavior is "better" -- and the same could be done for all stochastic forces.

**Comment by swails** [comment]
I submitted PR #765 demonstrating my idea.

**Comment by swails** [comment]
@peastman merged the PR and the other features are open issues, so I think this can be closed.

**Comment by jchodera** [comment]
Thanks, everybody!
