### ISSUE TITLE
Possibility of supporting zero-length bond constraints?

### ISSUE THREAD

**Issue by jchodera** [pandegroup/openmm#810]
We have a use case where it would be extremely convenient if OpenMM had the potential to support zero-length bond constraints so that several (noninteracting) particles would be slaved to occupy the same point in space.

A simple experiment suggests that zero-length bond constraints don't seem to work.  A minimization linking two LJ particles (with an exclusion) failed to get anywhere.

Is this possible with some other scheme supported by OpenMM, such as virtual sites?

Alternatively, is there some way to make the constraint code able to support this kind of thing, or is this more than a numerical stability change (e.g. something that needs a new type of constraint theory)?

**Comment by rmcgibbo** [comment]
Can you move them to the same point in space and then set the mass to zero
to freeze them out?

**Comment by jchodera** [comment]
These particles have to evolve dynamically, and there are multiple particle sets that must have this property, so that wouldn't work.

I wonder if a virtual site defined by a single point would work.

**Comment by swails** [comment]
> On Feb 15, 2015, at 2:56 PM, Robert T. McGibbon <notifications@github.com> wrote:
> 
> Can you move them to the same point in space and then set the mass to zero
> to freeze them out?

But what happens when that parent atom moves? :)

**Comment by swails** [comment]
> On Feb 15, 2015, at 3:43 PM, John Chodera <notifications@github.com> wrote:
> 
> These particles have to evolve dynamically, and there are multiple particle sets that must have this property, so that wouldn't work.
> 
> I wonder if a virtual site defined by a single point would work.

Try a 2-site virtual site where the weights are 1 and 0. That should always put it on the one atom.

**Comment by peastman** [comment]
A virtual site is exactly what you want, just as @swails described.

Mathematically, a "zero length constraint" is completely different from an ordinary distance constraint.  A distance constraint eliminates one degree of freedom, but a constraint requiring two particles to be coincident eliminates three degrees of freedom.  If you try to treat it as a distance constraint but set the length to 0, you get a singular matrix.

**Comment by jchodera** [comment]
Thanks!  Will give this a try.

**Comment by jchodera** [comment]
Actually, does anybody have any suggestions for where to look at for examples of two-site virtual sites?  The API reference seems to be a little underwhelming:
http://docs.openmm.org/6.2.0/api-python/classsimtk_1_1openmm_1_1openmm_1_1VirtualSite.html

**Comment by swails** [comment]
I support them in ParmEd.  Here is my two-site class that returns the information needed by the OpenMM class: https://github.com/ParmEd/ParmEd/blob/master/chemistry/topologyobjects.py#L1038-L1116 -- the nice thing (I think) here that you get that's "extra" compared to the OMM doxygen docs is the little ASCII diagram that I put.  I would argue it's kind of an example, since you can see how I use the existing geometry to define the weights you would need to feed to the OMM class (although it, too, is a class that might be better served by having its own example).

Here is where I convert my class into OpenMM's variant, complete with function call: https://github.com/ParmEd/ParmEd/blob/master/chemistry/structure.py#L1518-L1544

A small demo.  You can really do this with *any* two particles:

```Python
from simtk.openmm import app
from simtk import openmm as mm, unit as u

# .... create your system and whatnot
system.setVirtualSite(12, mm.TwoParticleAverageSite(10, 11, 0.0, 1.0))
```

In this example, you are turning atom 12 in to a virtual site (if you are starting from an Amber prmtop or some other class that doesn't already have the dummy particle, just add one to the end of the resulting `System` and use that index).  Atom 10 can really be anything.  It doesn't matter in this case.  Atom 11 is the one where you want atom 12 to always be coincident with.

In your particular case, the weight of 0 means that the particle's position is equal to 0 times the position of the first particle (10) plus 1 times the position of the second particle (11) -- making it completely coincident with particle 11.

Have a look at the signs that I return for my weights in my `TwoParticleExtraPointFrame` based on whether the point will be constrained *between* the vector separating the two atoms in the frame or *beyond* the vector separating the two atoms in the frame (and the fact that they always sum to 1).

Another thing you can do is actually *use* ParmEd to create your structure (if you use either a CHARMM PSF or Amber prmtop file), add a new `ExtraPoint` particle to whatever residue you want it attached to, create a Bond between it and the other atom with a length of 0, and let ParmEd create the OpenMM `System` for you.

**Comment by jchodera** [comment]
Thanks, everybody!  This is just what we needed.
