### ISSUE TITLE
GBSAGBnForce parameter range

### ISSUE THREAD

**Issue by pgrinaway** [pandegroup/openmm#923]
Hi,

I'm currently trying to sample new parameters for various GB models, but I run into an error (below) when I sample within a range that I'd expect to work (minimal example below). If the radius is set to less than 0.19A, the code seems to work. But above that (such as at 0.2A), the following error is produced:

```
libc++abi.dylib: terminating with uncaught exception of type OpenMM::OpenMMException: ReferenceDiscrete1DFunction: argument out of range
/Users/grinawap/anaconda/bin/python.app: line 3: 38570 Abort trap: 6           /Users/grinawap/anaconda/python.app/Contents/MacOS/python "$@"
```

I assume this results from the computation of an `index` inside the implementation of the force, but I'm not sure what the bounds of this should be. Many apologies if I've simply missed the documentation for these GBSA implementations, but I could not seem to locate it in the manual or dev guide.

Thanks so much for your help!

```python
import simtk.openmm as openmm
import simtk.openmm.app.internal.customgbforces as customgbforces
import simtk.unit as units
import numpy as np

system = openmm.System()
system.addParticle(1)
system.addParticle(1)

gbnforce = customgbforces.GBSAGBnForce()
system.addForce(gbnforce)

#bad radius: set to 0.15 to avoid failure
radius = 0.20 * units.angstroms
gbnforce.addParticle([0.1, radius, 0.05])
gbnforce.addParticle([0.1, radius, 0.05])
positions = [[0.0,0.0,0.0],[1.0,1.0,1.0]]

timestep = 2*units.femtoseconds
collision_rate = 10 / units.picoseconds
temperature = 300*units.kelvin

integrator = openmm.LangevinIntegrator(temperature, collision_rate, timestep)
context = openmm.Context(system, integrator)
context.setPositions(positions)
state = context.getState(getEnergy=True)
print(state.getPotentialEnergy())
```

**Comment by swails** [comment]
The GBneck force uses an interpolation table to evaluate energies and forces related to the neck component.  The lookup table, taken from the Amber source code, interpolates from 1 to 2 Angstroms in 0.04 A increments for both atoms (so a 21x21 table).  So that said, I'm not sure why either 0.15 *or* 0.2 Angstroms would work (it might explain why 0.15 *nanometers* works and 0.2 doesn't, although that range should be inclusive).

So all of your radii should be between these two values.  On a related note, GBn2 is quite a bit better than GBn.

Note that there is no error checking for this class, since it just creates and returns a `CustomGBForce`, and that object doesn't know anything about these limits.

**Comment by pgrinaway** [comment]
+1, thanks for the explanation. That seems to work.

**Comment by peastman** [comment]
Would it be better to actually interpolated between values in the table?  It would be pretty easy to change the functions to Continuous2DFunction instead of Discrete1DFunction.  But if that isn't what Amber does, we should probably stay consistent with that.

**Comment by swails** [comment]
> Would it be better to actually interpolated between values in the table? It would be pretty easy to change the functions to Continuous2DFunction instead of Discrete1DFunction.

I'd thought about it before.

> But if that isn't what Amber does, we should probably stay consistent with that.

And that's why I didn't change it.

As an aside, this is a very common mistake to make, and one that we should have a better error message for.  I'll open an issue and get it done.
