### ISSUE TITLE
Buckingham Potential

### ISSUE THREAD

**Issue by alexW432** [pandegroup/openmm#973]
Hi,
I’m trying to implement a Buckingham potential into openMM using the CustomNonbondedForce. However I’m not sure if I need to add the perParticleParameters. Are there any references I could use for adding custom non bonded forces? This is what I have added so far:

force = CustomNonbondedForce('A*exp(-r/rho) - C/r^6')
force.addGlobalParameter('A', 1)
force.addGlobalParameter('rho', 1)
force.addGlobalParameter('C', 1) 
for i in range(system.getNumParticles()):
                     force.addParticle(i, ())
system.addForce(force)

however when run it says, add.Particle was given 3 arguments instead of 2. Also I wish to run this for Water only. 

Many thanks,
Alex

**Comment by swails** [comment]
I can't say that I've ever actually tried using a `CustomNonbondedForce` without any per-particle parameters before (as you're doing here).  If OpenMM is complaining about getting 3 instead of 2 arguments, I would suggest taking out the empty tuple in `force.addParticle` and see if that helps.

**Comment by leeping** [comment]
Hi Alex,

I'm guessing that you would need per-particle parameters to implement a working Buckingham potential for water.  This is because the oxygen parameters are likely to be different from the hydrogen parameters.  Since I don't know all the details of your application, I could be wrong (for example, if you're modeling water molecules as single particles.)

- Lee-Ping

**Comment by peastman** [comment]
The extra argument it's complaining about is the "i".  CustomNonbondedForce.addParticle() only takes one explicit argument, the list of parameters.  (Every Python method implicitly gets a reference to "self" as an argument, which is why it says you're passing three and there should only be two.)  Call it as

    force.addParticle(())

**Comment by jlmaccal** [comment]
Alex,

Have a look at the documentation for `addParticle`. It states:

```
addParticle(CustomNonbondedForce self, vectord parameters) -> int

Add the nonbonded force parameters for a particle. This should be called once for each particle in the System. When it is called for the i'th time, it specifies the parameters for the i'th particle.
   Parameters:
    - parameters the list of parameters for the new particle
```

As you can see, you shouldn’t be passing it the index as a parameter. You should be calling it once per-particle with a list or tuple of parameters.

As Lee-Ping suggests, you likely want to make `A`, `C`, and `rho` into `perParticleParameter`s so that they can be set separately for each atom in the system.

**Comment by swails** [comment]
> The extra argument it's complaining about is the "i".

Oh duh.

**Comment by alexW432** [comment]
Thank you, removing the 'i' worked perfectly.
